### ISSUE TITLE
typegoose forces named collections in mongodb

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#103]
I like typegoose

so I opt'd to use this typegoose abstraction which consolidates some of the mongoose model issues

typegoose classes are stored in the class name as plural

User gets persisted to Users in mongodb... see following dump from https://github.com/bitjson/typegoose-objects-array

-------- cut here ------
C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\server\mongoose\typegoose.examples\typegoose-objects-array>node test1.js
Trying to save a User without using the existingMongoose option.
Setup complete.
(node:9648) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect
()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:9648) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mon
goosejs.com/docs/promises.html
{ _id: 5a963e8f7a1ec925b066b3a6,
  emailAddress: 'ovechkin@nhl.com',
  password: 'hearttrophyplayer',
  __v: 0 }

OK something got persisted and when I got  mongo I see this

> db.users.find()
{ "_id" : ObjectId("5a963e8f7a1ec925b066b3a6"), "emailAddress" : "ovechkin@nhl.com", "password" : "hearttrophyplayer", "__v" : 0 }
>

it got stuffed into a Users collection

is this typegoose, mongoose or mongo ?

-------- cut here ------

I prefer to have a table named User which would be the User table where by objects of a User would live.
I would like to formulate my REST urls

/api/user  - for all users
/api/user/1    - user with id 1

if anyone can comment on what juncture the table for users turns plural that would be great.

I would like the ability to name my own table to be user instead of users so I can model my rest call urls as above.

thank you

**Comment by Ben305** [comment]
You can already set the collection name using the schema options.
