### ISSUE TITLE
typegoose 4.0 broken

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#105]
docs do not seem to be updated for 4.0 release unless they need no update

objects are being persisted to db

but without properties

any feedback appreciated

**Comment by Ben305** [comment]
Can you provide a sample? My projects are working fine with 4.0.

**Comment by nhhockeyplayer** [comment]
private async create(ctx: Koa.Context) {
        const data = ctx.request.body;

        let u = await UserModel.create({
            _id: mongoose.Types.ObjectId(),
            emailAddress: data.emailAddress,
            password: data.password
        });

        this.renderCtx
            .renderSuccess(
                ctx,
                HttpStatus.CREATED,
                'users',
                u.toString());
    }


response from REST client in webstorm
User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.

debugger console follows

"C:\Program Files\nodejs\node.exe" --inspect-brk=63640 C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\dist\server\server.js cross-env NODE_ENV=development nodemon --watch 'server/**/*' -e ts,tsx --exec 'ts-node' ./server/server.ts
Debugger listening on ws://127.0.0.1:63640/800ff62a-bd39-45a4-b49f-7797fbaa356c
For help see https://nodejs.org/en/docs/inspector
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize]
Server running on port 3000
MongoDB connection success Bluebird. MongoDB is running. 
{"method":"POST","url":"/api/user","query":{},"remoteAddress":"::ffff:127.0.0.1","host":"localhost:3000","userAgent":"Apache-HttpClient/4.5.2 (Java/1.8.0_152-release)","errorMessage":"User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.","errorStack":"ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.\n    at new ValidationError (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\error\\validation.js:27:11)\n    at model.Document.invalidate (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1725:32)\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1597:17\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\schematype.js:785:9\n    at process._tickCallback (internal/process/next_tick.js:150:11)","statusCode":500,"responseTime":56}

  ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.
      at new ValidationError (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\error\validation.js:27:11)
      at model.Document.invalidate (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1725:32)
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1597:17
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\schematype.js:785:9
      at process._tickCallback (internal/process/next_tick.js:150:11)

{"method":"POST","url":"/api/user","query":{},"remoteAddress":"::ffff:127.0.0.1","host":"localhost:3000","userAgent":"Apache-HttpClient/4.5.2 (Java/1.8.0_152-release)","errorMessage":"User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.","errorStack":"ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.\n    at new ValidationError (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\error\\validation.js:27:11)\n    at model.Document.invalidate (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1725:32)\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1597:17\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\schematype.js:785:9\n    at process._tickCallback (internal/process/next_tick.js:150:11)","statusCode":500,"responseTime":5}

  ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.
      at new ValidationError (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\error\validation.js:27:11)
      at model.Document.invalidate (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1725:32)
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1597:17
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\schematype.js:785:9
      at process._tickCallback (internal/process/next_tick.js:150:11)

Debugger attached.
Debugger listening on ws://127.0.0.1:63640/800ff62a-bd39-45a4-b49f-7797fbaa356c
For help see https://nodejs.org/en/docs/inspector

Process finished with exit code 1

**Comment by nhhockeyplayer** [comment]
import {prop, Typegoose} from 'typegoose';
import * as mongoose from 'mongoose';

mongoose.connect('mongodb://localhost:27017/api');

export class User extends Typegoose {
    @prop({ required: true })
    emailAddress: string;
    @prop({ required: true })
    password: string;
}

export const UserModel = new User().getModelForClass(User);

**Comment by nhhockeyplayer** [comment]
the .create method on the model isnt taking

i saw in the debugger after await, undefined

but the data coming in from koa is fine I see the data in my data object

**Comment by nhhockeyplayer** [comment]
thank you for the help I will try to clean up troubleshooting better with a github project eventually

just trying to shake this out

I like it

does the create return an object to async off of ?

**Comment by nhhockeyplayer** [comment]
originally I saw objects being persisted to the database with ID and no properties

found out I need to get rid of new and use create

but now using create nothing gets persisted

**Comment by nhhockeyplayer** [comment]
my UserModel seems to be undefined when making the create call

so life cycle of the model is undefined for some reason

**Comment by Ben305** [comment]
Please provide a sample repository, that makes it a lot easier

**Comment by nhhockeyplayer** [comment]
Its looking like timing of where the mongoose.connect (...) is placed

I could put it in the model
I could put it in my router at the top
I could put in my router constructor

QUES: where is the ideal place to put mongoose.connect(...)

does it get bootstrapped somehow into typegoose beforehand so proper binding takes place ?

**Comment by nhhockeyplayer** [comment]
I have searched github for a starter project using koa2 typescript for async/await

and found none

thats what I am working on now

but this typegoose package could use a descent starter project on github to accomodate

**Comment by nhhockeyplayer** [comment]
here is latest output

MongoDB connection success Bluebird. MongoDB is running. 
{"method":"POST","url":"/api/user","query":{},"remoteAddress":"::ffff:127.0.0.1","host":"localhost:3000","userAgent":"Apache-HttpClient/4.5.2 (Java/1.8.0_152-release)","errorMessage":"User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.","errorStack":"ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.\n    at new ValidationError (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\error\\validation.js:27:11)\n    at model.Document.invalidate (C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1725:32)\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\document.js:1597:17\n    at C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\api\\node_modules\\mongoose\\lib\\schematype.js:785:9\n    at process._tickCallback (internal/process/next_tick.js:150:11)","statusCode":500,"responseTime":9}

  ValidationError: User validation failed: emailAddress: Path `emailAddress` is required., password: Path `password` is required.
      at new ValidationError (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\error\validation.js:27:11)
      at model.Document.invalidate (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1725:32)
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\document.js:1597:17
      at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\mongoose\lib\schematype.js:785:9
      at process._tickCallback (internal/process/next_tick.js:150:11)

Debugger attached.
Debugger listening on ws://127.0.0.1:63927/03ed2772-078a-40ad-94ae-a7e5c2173ef4
For help see https://nodejs.org/en/docs/inspector

**Comment by nhhockeyplayer** [comment]
this is the router

import * as Koa from 'koa';
import IRouter from '../isomorphic/IRouter';

import * as Router from 'koa-router';
import RenderCtx from '../isomorphic/RenderCtx';

import * as HttpStatus from 'http-status-codes';
import * as mongoose from 'mongoose';
import {UserModel} from './model/User';
import * as Bluebird from 'bluebird';

class UserRouter implements IRouter {
    private static connectString = process.env.MONGODB_URI || 'mongodb://localhost/api';

    private Router = new Router({
        prefix: '/api',
    });
    private renderCtx = new RenderCtx();

    constructor() {
        (<any>mongoose).Promise = Bluebird;
        mongoose.connect(UserRouter.connectString, {server: {poolSize: 15}})
            .then((): void => {
                console.log("MongoDB connection success Bluebird. MongoDB is running. ");
            })
            .catch((err): void => {
                console.log("MongoDB connection error. Please make sure MongoDB is running. " + err);
                process.exit();
            });
    }

    // We need use bind for transmission context
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
    public router(): Router {
        return this.Router
            .post('/user', this.create.bind(this));
    }

    private async create(ctx: Koa.Context) {
        const data = ctx.request.body;

        let u = await UserModel.create({
            _id: mongoose.Types.ObjectId(),
            emailAddress: data.emailAddress,
            password: data.password
        });

        this.renderCtx
            .renderSuccess(
                ctx,
                HttpStatus.CREATED,
                'users',
                u.toString());
    }
}

export const userRouter: UserRouter = new UserRouter();

**Comment by nhhockeyplayer** [comment]
Hi Ben, 

I pushed what I have so far

if you can take a look that would be terrific

I will continue to shake it out

https://github.com/nhhockeyplayer/api

- cheers

KEN

**Comment by nhhockeyplayer** [comment]
to reproduce I am running server.ts as follows

webstorm IDE
1. launch server.js from dist dir within a node.js debug configuration
and debugging node in webstorm debugger breakpoints work great
2. REST Client to post user.json at root dir

**Comment by nhhockeyplayer** [comment]
so its looking like create call is not binding properties for my koa2 project

im signing off for now

will check back in next 12 hours

thanks for any feedback

**Comment by Ben305** [comment]
I cloned your repo but I can't get it running. But I saw something in _user.router.ts_:

```
let u = await UserModel.create({
  _id: mongoose.Types.ObjectId(),
  emailAddress: data.emailAddress,
  password: data.password
});
```

You should remove the line `_id: mongoose.Types.ObjectId()`, because the __id_ field is filled automatically.

**Comment by pdalfarr** [comment]
@Ben305  I know I am out of topic, but I just want to share this with you:
https://snyk.io/test/npm/typegoose

"Remediation: Upgrade to lodash@4.17.5"

Thanks a lot for Typegoose: amazing!

**Comment by nhhockeyplayer** [comment]
Ok here is latest
I removed the required=true as follows

export class User extends Typegoose {
    @prop()
    emailAddress: string;
    @prop()
    password: string;
}
export const UserModel = new User().getModelForClass(User);

now objects are persisting but only have the id no properties are being persisted

> db.users.find()
{ "_id" : ObjectId("5a972214faaf4926c8a6b312"), "__v" : 0 }
>

**Comment by nhhockeyplayer** [comment]
Ben

running my project is very simple
properties are not holding water

is this going to be patched?

If not I will have to pass on typegoose

I want to use it but right now its not holding water

I provided a repo

build normally
ng build

then use a commans prompt and go into src/server and execute tsc
that will compile the server and output the compilation to the dist folder
at this point use webstorm to launch a node.js debug configuration pointing to server.js
thats it
run...and debug...steps thru code beautifully

ignore the client stuff

webstorm has a REST Client tool to post ./api/user.json
you have to specify application.json for the contenttype in the REST Client tool

If you can help I would be greatful

**Comment by nhhockeyplayer** [comment]
Ben you said your projects are all running fine.
can you post one for access?

the tests for typegoose appear to work from their own private dir
nothing is holding up beyond that

even keyword model is conflicting
I cant import
or get any predictable runtime here

**Comment by nhhockeyplayer** [comment]
the promise coming back from model.create(...) has undefined properties for the model

the pre hooks did persist createdAt updatedAt properties though

User.ts
@pre<User>('save', (next) => {
    if (!this.createdAt) {
        this.createdAt = this.updatedAt = new Date();
    }
    next();
})
export class User extends Typegoose {
    @prop()
    emailAddress: string;
    @prop()
    password: string;
    @prop()
    createdAt?: Date;
    @prop()
    updatedAt?: Date;
}
export const model = new User().getModelForClass(User);


user.router.ts
    private async create(ctx: Koa.Context, next) {
        const data = ctx.request.body;

        let u = await model.create([{
                emailAddress: data.emailAddress,
                password: data.password
            }])
            .then((result) => {
                this.renderCtx
                    .renderSuccess(
                        ctx,
                        HttpStatus.CREATED,
                        'users',
                        result);
            })
            .catch((err) => {
                this.renderCtx
                    .renderFaild(
                        ctx,
                        HttpStatus.CONFLICT,
                        'users',
                        err);
            });
    }

I'll start pairing down the package.json something with mongoose maybe

**Comment by nhhockeyplayer** [comment]
koa body was coming in as array
I was treating it as object
therefore it was never making it into the model on create
