### ISSUE TITLE
platform potential here

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#106]
In 2006 java.net founder created trails. I was a committer. Trails since then turned into Tynamo.
http://www.tynamo.org/
https://github.com/tynamo
A turnkey out of the box fullstack with backend, middletier and default extensible frontend CRUD user interface component portfolio edit, list, view, table... and more.
Enviably one of the sweetest code bases on the planet. Having been there and done that it was slow as a dog.

Notably however, the whole trails/tynamo fullstack was written with custom annotations (decorators) and Property Descriptors on classes methods and properties. Hence ClassDescriptor, MethodDescriptor, PropertyDescriptor, and PropertyDescriptor was a base class to many KINDs of sub descriptors of many useful things... checkout the codebase on above github link. Hibernate decorators OneToOne, OneToMany ManyToOne and ManyToMany made collecting entities a breeze but I see only half witted attempts as these relationship models in other frameworks that just dont come close to modeling the natural world. These descriptors knew its code (end result was an app that knew itself and knew what to do inside/out in everything) by reflection and bootstrapped a ton of value into the resulting app providing a canned user interface and an event driven middle tier. Koa2 would be the async/await candidate for enterprise. 

Typegoose is alarmingly close and I regard this piece of code probably the nicest I seen on the planet for node.js. Nice job Akos I been waiting to see this happen and your the first.

Issues of inheritance and extensibility would all need to be buried and nailed.

Tynamo security (known as tapestry-security) is another sweet decorator based deliverable within tynamo that automates authorization, authentication and notably Instance based security and Property based security all using decorators.

I wanted to send the thought to encourage the Typegoose team to consider bundling this up with angular5 since it's already married to mongoose for a turn key out of the box fullstack advocating a default canned set of components driven by these property descriptors which are identified during bootstrap and rendered per-property as they are encountered during runtime within front end components such as edit view list table etc..

**Comment by hasezoey** [comment]
> I wanted to send the thought to encourage the Typegoose team to consider bundling this up with angular5 

will not be done, typegoose is just a typescript wrapper for mongoose, and nothing more, and angular is a frontend, typegoose & mongoose is for a backend

so a "won't fix"
-> this can/could be closed

@Ben305 could you apply the label "wont fix" & close this?
