### ISSUE TITLE
findOrCreate plugin fails on unique properties

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#107]
decided to try
const findOrCreate = require('mongoose-findorcreate');

on a User model

        let u = await model.findOrCreate({  // creates but does not find
                emailAddress: ctx.request.body[0].emailAddress,
                password: ctx.request.body[0].password,
                gender: ctx.request.body[0].gender,
                role: ctx.request.body[0].role,
                createdAt: new Date(),
                updatedAt: new Date()
            })

emailAddress was modeled to be unique

    @prop({ index: true, unique: true, required: true })
    emailAddress: string;

the @plugin(findOrCreate) fails to find the entity after its created

console debugger output as follows
KOA CREATE Failure Object OID hex===> 5a97cad90796530b043e9971 { BulkWriteError: E11000 duplicate key error collection: api.users index: emailAddress_1 dup key: { : "alexander.ovechkin@nhl.com" }

cannot operate unique and/or index props

i see same thing for simple User.find(...)

**Comment by Ben305** [comment]
Please file an issue for the plugin, this is not related to typegoose.
