### ISSUE TITLE
need support to force collection name

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#109]
User models keep ending up in users collection

according to this post, mongoose allows for forcing the name of the collection
https://stackoverflow.com/questions/7486528/mongoose-force-collection-name

this gives flexibility on modeling REST urls to the developer

Please add support to override or specify collection name

**Comment by Ben305** [comment]
You can do that already:

```typescript
export const MyModel: ModelType<MyModel> = new MyModel().setModelForClass(MyModel, {
	existingMongoose: mongoose,
	schemaOptions: {collection: 'my_collection_name'}
});
```
