### ISSUE TITLE
Add missing SchemaType Options (unique, index, etc).

### ISSUE THREAD

**Issue by joseluisgarciaott** [szokodiakos/typegoose#11]
I'm not quite sure why there is an agrupation of the "allowed" SchemaType Options (required, enum, default, min, max, etc) in the code (BasePropOptions, ValidateNumberOptions, etc). I guess you want TS to ensure what is being sent in the @**prop**() and @**arrayProp**() annotations... right?

The annoying part of this is that we should add the missing SchemaType Options manually :cry: 

I've already tested adding **unique** and **index** in the BasePropOptions:

```
export interface BasePropOptions {
  unique?: boolean; // Unique is always boolean!
  index?: boolean; // Same here.
...

```
...and they work just fine. Would you like a PR for this? This is another simple addition ;)

**Comment by szokodiakos** [comment]
Hello!

Yes unfortunately I haven't covered all options yet, and yes all PR is appreciated! :)

**Comment by teddis** [comment]
Hi, I'm trying to find out why Typegoose is not creating a unique index on a new model for me. I'm assuming it works for you! Everything in my code looks correct and the property is defined as:
``` 
@prop({ index: true, unique: true })
sessionId?: string; 
```
I'm using Mongoose 5.2.5, MongoDB 3.6.6, and Node 9.2.1. My model references an existing collection. I dropped the collection and it rebuilt with only _id index. I guess I'll have to debug, but hoping someone can tip me off to any other config I'm forgetting or wasn't documented? Thanks.

**Comment by teddis** [comment]
Nevermind. I discovered I had to call `model.createIndexes()` after compiling the model to ensure the index is built. I think it would be helpful for others to add this to your README.
