### ISSUE TITLE
need custom ID support

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#110]
OIDs are a common commercial data property

typegoose and mongoose are creating them implicitly under the hood

I would like to emulate my own custom ID number of range [0..n] and have it be autoincrement on newly created models. 

therefore

/api/user - returns all users
/api/user/10 - returns user of ID 10

and makes for simple REST urls

**Comment by Omegahorus** [comment]
One solution (not the best, but working) is to ignore the fields `_id` and `id`. Instead, use a custom field 'userID' where you can set your values as you wish (make them unique). Then you can search für Users with specific userID
Regards.

**Comment by Ben305** [comment]
You can disable the __id_ already using the schema options passed to mongoose:

See http://mongoosejs.com/docs/guide.html:
```
var childSchema = new Schema({ name: String }, { _id: false });
```
