### ISSUE TITLE
question: does typegoose support query middleware config via decorators?

### ISSUE THREAD

**Issue by marcelh-gh** [szokodiakos/typegoose#111]
class decorators (on the model) for save/validate etc. hooks work just fine.

since the schema is generated by Typegoose I am not sure where to configure a hook for query middleware (like update/find etc. hooks).

I tried to just use a class decorator but it never gets executed.

BTW: Typegoose is awesome! especially since 4.0 :-)

**Comment by Ben305** [comment]
Check README.md and have a look for ```@pre```

**Comment by marcelh-gh** [comment]
Thx. I was using the @pre decorator successfully already :-)
Like I described, it worked for save/validate hooks...
It seems, this is a Mongoose issue, not a Typegoose one. I was using the `updateOne `method. Apparently that does not have any pre/post hooks.
When I use the `update `method instead, it works just fine.

So the answer to my original question seems to be: Typegoose does not distinguish between query and document middleware. The class decorators work for both.

**Comment by marcelh-gh** [comment]
Ok. I checked the Mongoose docs again. There actually is middleware for `updateOne `with pre/post hooks.
The respective entry is just missing in the Typegoose hooks.d.ts. 
I'll open an issue for that.
