### ISSUE TITLE
problem with @arrayProp for arrays of subdocuments

### ISSUE THREAD

**Issue by marcelh-gh** [szokodiakos/typegoose#116]
**_from the docs:_**

> arrayProp(options)
> The arrayProp is a prop decorator which makes it possible to create array schema properties.
> 
> The options object accepts required, enum and default, just like the prop decorator. In addition to these the following properties exactly one should be given:
> 
> items: This will tell Typegoose that this is an array which consists of primitives (if String, Number, or other primitive type is given) or this is an array which consists of subdocuments **(if it's extending the Typegoose class).**

**Question**:

Is the bold faced part to be understood so that subdocuments for arrays must be based on classes which themselves extend the Typegoose class?

I am asking this because the arrayProp decorator works just fine for me as long as the array contains primitive types.
But as soon as I use any another class for a small subdocument (not extending Typegoose), I get errors like this:

>  throw new TypeError('Undefined type `' + name + '` at `' + path +
>     ^
> 
> TypeError: Undefined type `undefined` at `required`
>   Did you try nesting Schemas? You can only nest using refs or arrays

**Comment by marcelh-gh** [comment]
the issue seems only to come up when using `required `together with `items `for the arrayProp decorator

**Comment by babakyakhchali** [comment]
close #116

**Comment by marcelh-gh** [comment]
@Ben305 could you please have a look at this? I pretty sure it's a bug... thx :-)

**Comment by Ben305** [comment]
Please provide a repository that reproduces the problem. I will take a look then.

**Comment by marcelh-gh** [comment]
@Ben305 here you go.... let me know if you need additional explanation...
[repo for investigation of issue #116](https://github.com/marcelh-gh/typegoose-arrayprop-bug)

**Comment by marcelh-gh** [comment]
@Ben305 hi...did you have a look at my repo? can you confirm it's a bug? thanks

**Comment by mhoc** [comment]
+1'ing this issue as well; its definitely only `@arrayProp()` with `items` and `required` both set. If `required` is removed, it works fine.

**Comment by marcelh-gh** [comment]
@szokodiakos could you have a look at my repo and confirm this is a bug? thanks a lot!
[repo for investigation of issue #116](https://github.com/marcelh-gh/typegoose-arrayprop-bug)

**Comment by mhoc** [comment]
I've possibly discovered another related issue which I've documented in a repo here https://github.com/mhoc/typegoose-arrayprop-bug

Essentially, if you have a class representing a sub-document, and that sub-class has an `@arrayProp` with either `required` (which this issue outlines) or even a `default` parameter, the schemas fail to compile. This is true whether that sub-class `extends Typegoose` or not. 

```
class C {
  @prop()
  value: string;
}
class B {
  @arrayProp({ default: () => [], items: C })
  c: C[];
}
class A extends Typegoose {
  @prop()
  b: B
}
```

Not totally sure if this is a bug or if this is a misuse of the library.

**Comment by MateuszKicinski** [comment]
Any news on that ?

**Comment by FSM1** [comment]
I keep running into these circular reference errors. Any information on how to resolve this?

**Comment by RyannGalea** [comment]
> Essentially, if you have a class representing a sub-document, and that sub-class has an `@arrayProp` with either `required` (which this issue outlines) or even a `default` parameter, the schemas fail to compile. This is true whether that sub-class `extends Typegoose` or not.

Any news on this? I am trying to have default values on an 'arrayProp()' but it doesn't work

**Comment by visheshd** [comment]
I just bumped into the same issue. Goes away if I don't specify `default`.

**Comment by hasezoey** [comment]
is this still a problem?

---

@marcelh-gh 

(in tsSubDoc.ts)
```ts
@arrayProp({ items: tgSubDocDetails })
details?: tgSubDocDetails;
```
shoudnt it be an array? also `tgSubDocDetails[]`?

**Comment by hasezoey** [comment]
i tested you repo, updated all dependencies, modified what said above, how it should be, and modified this below to work with above
```ts
@staticMethod
static async register(this: ModelType<tgDocTest>, newDoc: InstanceType<tgDocTest>) {
    newDoc.lastname = "Test";
    newDoc.arrayOfStrings = ["one", "two", "three"];
    newDoc.subdoc = {
        date: new Date, details: [{ value2: 5 }]
    };
    newDoc.arrayOfSubDocs = [{
        date: new Date, details: [{ value2: 1 }]
    }, {
        date: new Date, details: [{ value2: 2 }]
    }];
    return this.create(newDoc);
}
``` 

and couldnt see any executing error, in db
```json
{
  "_id": "5d422667ce22b774f443eaa4",
  "arrayOfStrings": [
    "one",
    "two",
    "three"
  ],
  "optionalArrayOfSubDocs": [],
  "arrayOfSubDocs": [
    {
      "_id": "5d422667ce22b774f443eaa9",
      "date": "2019-07-31T23:38:15.278Z",
      "details": [
        {
          "_id": "5d422667ce22b774f443eaaa",
          "value2": 1
        }
      ]
    },
    {
      "_id": "5d422667ce22b774f443eaa7",
      "date": "2019-07-31T23:38:15.278Z",
      "details": [
        {
          "_id": "5d422667ce22b774f443eaa8",
          "value2": 2
        }
      ]
    }
  ],
  "lastname": "Test",
  "subdoc": {
    "_id": "5d422667ce22b774f443eaa5",
    "date": "2019-07-31T23:38:15.275Z",
    "details": [
      {
        "_id": "5d422667ce22b774f443eaa6",
        "value2": 5
      }
    ]
  },
  "__v": 0
}
```

i would say this somehow got fixed
@Ben305
