### ISSUE TITLE
How should SchemaTypes Mixed and Buffer be used via Typegoose

### ISSUE THREAD

**Issue by NikoMix** [szokodiakos/typegoose#122]
Could you please extend the Documentation a bit, for how to use buffer and datatype mixed?

Would be awesome!

**Comment by matanelgabsi** [comment]
I don't know if this is how you should use it, but this example works:
```
class File {
  @prop({ required: true })
  data: InstanceType<Buffer>;
}
```

This however, will not (due to the line `const instance = new Type();` in props.ts):
```
class File {
  @prop({ required: true })
  data: Buffer;
}
```

**Comment by trayhem** [comment]
Using a Uint8Array instead of a Buffer worked for me.

```
class File {
  @prop({ required: true })
  data: Uint8Array;
}
```

**Comment by neckaros** [comment]
This was a pain to solve.

Best solution i found so far is to use the mongoose Binary type:
```
import { ObjectId, Binary } from 'bson';
...

export class MediaImage extends Typegoose {
    @prop()
    small: Binary;
    @prop()
    medium: Binary;
}
```

you make a binary with:
`image.small = new Binary(yourBuffer);`

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed as "stale"
