### ISSUE TITLE
how do we define a virtual function in typegoose

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#124]
is there a way to integrate a virtual function into the typegoose schema definition?

**Comment by nhhockeyplayer** [comment]
this was precipitated by mania surrounding _id and id within mongoose

and it seems these modeling issues are now buried for good

see
https://github.com/szokodiakos/typegoose/issues/121

**Comment by nhhockeyplayer** [comment]
I am reopening this because mongoose insists on storing models using _id

and thats whats landing in the mongodb

my exercising of @prop id was a side show it had no affect as it does not sync with the mongoose objectId as denoted by _id

this needs to be resolved with virtual function support in typegoose

**Comment by hasezoey** [comment]
this can be closed, because i cant find any problem with `.id` or `._id` (with the latest mongoose & typegoose)

@Ben305
