### ISSUE TITLE
need support to override mongoose pluralization of collection names

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#125]
to override mongoose default pluralization of collection names we do this

var userModel = mongoose.model('user', userSchema, 'user');

the third parameter if not specified allows mongoose to pluralize all collection names from user to users by default

I see no support to override this mongoose schema in typegoose

if anyone knows how thank you please advise of wokraround or if this is somehow built in please advise

otherwise this is a request for feature

**Comment by Ben305** [comment]
You can already set the collection name using the schema options.

**Comment by nhhockeyplayer** [comment]
Ben can you provide an example?
