### ISSUE TITLE
PRE hook.ts      aot compiler bug

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#127]
ERROR in server\model\User.ts(12,2): Error during template compile of 'User'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'pre'
    'pre' references 'pre'
      'pre' is not initialized at ..\typegoose\lib\hooks.ts(3,22).

how do we get around this AOT issue

here is my model

import {InstanceType, plugin, pre, prop, Typegoose} from 'typegoose';
import * as mongoose from 'mongoose';

const findOrCreate = require('mongoose-findorcreate');

@pre<User>('save', (next) => {
    if (!this.createdAt) {
        this.createdAt = this.updatedAt = new Date();
    }
    next();
})
export class User extends Typegoose {

    @prop()
    _id?: mongoose.Types.ObjectId;
    @prop({required: true, match: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/})
    emailAddress: string;
    @prop({required: true})
    password: string;

    @prop()
    createdAt?: Date;
    @prop()
    updatedAt?: Date;
}
export const model = new User().getModelForClass(User);

**Comment by Ben305** [comment]
You should quote the regular expression...

**Comment by nhhockeyplayer** [comment]
this happens on all my models
