### ISSUE TITLE
Exporting model should be more like Typescript

### ISSUE THREAD

**Issue by eassymo** [szokodiakos/typegoose#129]
instead of
`const UserModel = new User().getModelForClass(User);`

we should use something like
```
export class UserModel extends ModelClass<User> {
}
```
more appropiate.

**Comment by hasezoey** [comment]
this is not in scope, because typegoose wants to wrap the class(/schema) creation of mongoose, and does not want to modify any functionality of mongoose model functions

@Ben305

**Comment by hasezoey** [comment]
@Ben305 Bump to close
