### ISSUE TITLE
Can typegoose support schema option get and set ?

### ISSUE THREAD

**Issue by zhengyhn** [szokodiakos/typegoose#130]
Hi,
     We use typegoose and it help us a lot. Now I want to migrate our old model definition to typegoose. But I found typegoose do not support schema option [get](http://mongoosejs.com/docs/api.html#schematype_SchemaType-get)    and [set](http://mongoosejs.com/docs/api.html#schematype_SchemaType-set).  Can this be support? And I would like to sending a pr, thank you.

**Comment by kyle-mccarthy** [comment]
@zhengyhn Have you tried to do this using [instance methods](https://github.com/szokodiakos/typegoose#instancemethod)?

**Comment by zhengyhn** [comment]
@kyle-mccarthy , I don't think the instance methods can solve my problem. What I need is calling a method automatically when doing find or update operation. I don't know how to implement it using instance methods.

**Comment by hasezoey** [comment]
this is included in v6.0.0

@Ben305 this can be closed
