### ISSUE TITLE
peerDependencies

### ISSUE THREAD

**Issue by clementSabattie** [szokodiakos/typegoose#133]
Hello, 

I got `node_modules/typegoose/lib/hooks.d.ts(1,23): error TS2688: Cannot find type definition file for 'mongoose'.`

simply solved by adding @types/mongoose in my package.json

It should be in your peerDependencies.

**Comment by Y0hy0h** [comment]
I have the same error when I have a fresh install of the package from npm (version 5.2.1). If I run `npm run build` inside the `typegoose` folder, everything works fine.

Apparently, the `/// <reference types="mongoose" />` at the top of the `.d.ts` files causes this issue. Rebuilding on my machine (Ubuntu 16.04) makes those go away and everything work.
