### ISSUE TITLE
Hibernate Decorators

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#134]
FEATURE REQUEST

Hibernate decorators 

- OneToOne
- OneToMany
- ManyToOne
- ManyToMany 

still used heavily in the field today

make collecting entities a breeze

relationships

would a real treasure to the field 

If decorators such as these could articulate proper ID modeling across entities

win win for back end and frontend

**Comment by nhhockeyplayer** [comment]
An additional feature to consider in this domain would be graph decorators

- dots and lines
or
- nodes and vertices
or
- nouns and relationships

an implied graph database would grow from these decorator constructs

Dots and lines By Richard J Trudeau 
this was my freshman discrete mathematics course
and this science is just making it to the field with graph databases
but we can implement this right on the mongodb middle tier

**Comment by hasezoey** [comment]
@Ben305 this can be closed
