### ISSUE TITLE
how to handle methods added by plugins - example in Typegoose doc not working

### ISSUE THREAD

**Issue by marcelh-gh** [szokodiakos/typegoose#135]
In the Typegoose documentation it says, the typing info for such methods needs to be provided manually withing the Typegoose class.

The provided example does not work though. Just having a method declaration without body causes an error with the compiler. Could you please provide a working example?

This solution does not seem very nice - having to declare all methods provided by plugins again within the Typegoose class.
Is there a better way? Especially if the plugin is written in TypeScript as well?

**Comment by martinratinaud** [comment]
Hi, @marcelh-gh. How did you solve this ?

**Comment by ctrlplusb** [comment]
Pinging @marcelh-gh I am also super interested in this. Composing available type information exposed by plugins would be awesome.
