### ISSUE TITLE
Using existing connection hangs on query

### ISSUE THREAD

**Issue by ssilve1989** [szokodiakos/typegoose#136]
I have defined a typegoose model in another package and am trying to use it as follows.
(some pieces omitted for brevity)

Snippet in TypeScript:
```typescript
import { Position } from '@studio/core';
import mongoose = require('mongoose');

async function subscribe(connection: mongoose.Connection) {
  const model = new Position({}).getModelForClass(Position, {
    existingConnection: connection,
  });

  try {
    console.log('fetching...');
    const data = await model.find({}).exec();
    console.log(data);
  } catch (e) {
    console.error(e);
  }
}

mongoose
  .connect(MONGO_URL)
  .catch(reason => {
    console.error(reason);
    process.exit(1);
  })
  .then(() => {
    subscribe(mongoose.connection);
  });

```

the promise will hang never complete. Is there something wrong here or a bug with using an existing connection?

If i instead just use the typegoose model to get the schema and create another model, it works, but thats completely unnecessary

```typescript
  const schema = new Position({}).getModelForClass(Position, {
    existingConnection: connection,
  }).schema;
  const model = mongoose.model('Positions', schema, 'positions');
```

**Comment by darbio** [comment]
@ssilve1989 what was your solution?

**Comment by hasezoey** [comment]
@darbio please know that his repository is discontinued, if you have issues try upgrading to `typegoose/typegoose@6.x`
