### ISSUE TITLE
[QUESTION] what is the benefit of the Ref type

### ISSUE THREAD

**Issue by marcelh-gh** [szokodiakos/typegoose#140]
@szokodiakos 
Hi! Could you please explain the benefit of the Ref type as it is defined by Typegoose as T or string ? Maybe you have code examples where it is used to process an unpopulated/ populated reference property?

As far as I can see, Mongoose returns something like `ObjectID {_bsontype: "ObjectID", id: Buffer(12)}` for an unpopulated reference property - so not a string.
Therefore I don't see why Typegoose defines Ref<T> as T | string ...

Thanks a lot & best regards,
Marcel

**Comment by Ben305** [comment]
I think you're right, it should be 

```typescript
type Ref<T> = T | ObjectID;
```

**Comment by Ben305** [comment]
Fixed in v5.2.1
