### ISSUE TITLE
@arrayProp Not Working With Enums?

### ISSUE THREAD

**Issue by spyter** [szokodiakos/typegoose#145]
I am having issues getting enums to work with **@arrayProp**. 

I originally mentioned this in #143, but after further investigation, I do not think it's related to that issue so I created a separate one for clarity. 

Below is an example of what I am doing. Has anyone else had this issue? Am I doing something wrong?

```
enum Test {
    One,
    Two,
    Three
}

@arrayProp({ items: Test, enum: Test })
public tests?: Test[];
```

^^ It appears that _items_ is undefined in **prop.ts** line **191**. I am only having this issue with enums.

**Comment by Ben305** [comment]
Try this:

```typescript
@arrayProp({ items: String, enum: Test })
public tests?: Test[];
```

**Comment by spyter** [comment]
@Ben305 This works for me. 

Thank you!! Very much appreciated!
