### ISSUE TITLE
[Suggestion] Allow refs to be something other than ObjectID types

### ISSUE THREAD

**Issue by mattjennings** [szokodiakos/typegoose#146]
https://github.com/szokodiakos/typegoose/blob/2ffe774a1fd357fd35a1ed79322fa581c262b866/src/prop.ts#L86-L93

Ran into a CastError when referencing schemas that use `_id` as a number instead of ObjectID. Other valid types are Number, String, and Buffer

I _might_ be able to take a stab at it this weekend.

**Comment by mattjennings** [comment]
Created a pull request https://github.com/szokodiakos/typegoose/pull/148

**Comment by hasezoey** [comment]
@Ben305 this can be closed because all the PR's for this got closed / merged (into v6.0.0)
