### ISSUE TITLE
[Enum] Typescript strings Enum as Function: Number?

### ISSUE THREAD

**Issue by nartc** [szokodiakos/typegoose#156]
![Console.log(UserModel.schema)](https://user-images.githubusercontent.com/25516557/40522239-7f9c2166-5f95-11e8-92c6-21937d268c20.png)
![UserRole.ts](https://user-images.githubusercontent.com/25516557/40522243-83650c40-5f95-11e8-88d5-4b526a7f5503.png)

As title and as the pictures, has anyone ever been into this situation? How'd you suggest resolving this issue?

Update: Looks like it works if I take out the `required` option. Is this intentional?

**Comment by hasezoey** [comment]
if you still have this error / can reproduce it, could you provide the relevant model & how it is saved?

**Comment by nartc** [comment]
@hasezoey I haven't been using Typegoose for a while but this is something I can provide a reproduce step really quickly. I'll update with more information soon.

**Comment by hasezoey** [comment]
Note: "type: Function: Number" is because mongoose cant take `string`(the primitive) only `String`(the class), and because class(/constructor) is a function, it is a "Function: Number". correct me if i'm wrong

**Comment by hasezoey** [comment]
> Is it possible to use refs with string types?

i couldnt reproduce this and i dont know how you call / use it...

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "questions - solved" / "not an issue with typegoose" / "its handeled in typegoose"
