### ISSUE TITLE
How to set timestamps?

### ISSUE THREAD

**Issue by DakshMiglani** [szokodiakos/typegoose#160]
well, usually in mongoose schema. we can do the following to add timestamps:

```
const Schema = new mongoose.Schema({
...
}, { timestamps: true})
```

but how do i do the same in this?

**Comment by DakshMiglani** [comment]
@DakshMiglani, this can be done like this:

`export const UserModel = new User().getModelForClass(User, { schemaOptions: { timestamps: true } });`

**Comment by letsbelopez** [comment]
How would you make schemaOptions required for a Model Class? I can't think of a way to do it.
I can force a model to have a property by implementing an interface but how do I force a Model to have a schemaOptions?

**Comment by hasezoey** [comment]
> How would you make schemaOptions required for a Model Class

what do you mean with this? schema Options cannot be forced in the sense like when calling `getModelForClass` (or buildSchema or anything like it)

but in version 6.0.0, you can make a base model where you can set a default value, that all classes that extend it inherit
