### ISSUE TITLE
Typegoose has issue to integrate with Oclif

### ISSUE THREAD

**Issue by cbou** [szokodiakos/typegoose#165]
This is my first project with TS so please excuse if I shouldn't post this issue here.

I can't achieve to make Typegoose working with Oclif. I always get the issue 

```(node:85955) Error Plugin: test-typegoose: There is no metadata for the "name" property.Check if emitDecoratorMetadata is enabled in tsconfig.jsonor check if you've declared a sub document's class after usage.
module: @oclif/config@1.6.33
task: toCached
plugin: test-typegoose
root: /Users/charles/Repositories/1001reviews/s/test-typegoose
See more details with DEBUG=*
 ›   Error: command hello not found
```

What I did was:

```bash
npx oclif multi test-typegoose
cd test-typegoose
npm install typegoose -S;
npm install mongoose reflect-metadata -S
```

I added   ` "experimentalDecorators": true` and `"emitDecoratorMetadata": true` to `tsconfig.json`.

I added the file `model.js`

```ts
import { prop, Typegoose, ModelType, InstanceType } from 'typegoose';
import * as mongoose from 'mongoose';

mongoose.connect('mongodb://localhost:27017/test');

class User extends Typegoose {
  @prop()
  name?: string;
}

const UserModel = new User().getModelForClass(User);

// UserModel is a regular Mongoose Model with correct types
(async () => {
  const u = new UserModel({ name: 'JohnDoe' });
  await u.save();
  const user = await UserModel.findOne();

  // prints { _id: 59218f686409d670a97e53e0, name: 'JohnDoe', __v: 0 }
  console.log(user);
})();
```

And import it with `import {model} from '../model.ts';`.

**Comment by hasezoey** [comment]
> Error: command hello not found

not an issue with typegoose, because nothing with `hello` was given in the issue, if you still have this issue, please try typegoose 5.9+ and what `test-typegoose` is for a file / how its called, i dont see any problem with the model

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale"

if anyone still encounters this problem in version 5.9 and up, please open a new issue in the new repo
