### ISSUE TITLE
First example fails

### ISSUE THREAD

**Issue by teddis** [szokodiakos/typegoose#171]
Excited to try this but fails out of the gate. Bad sign. Get:

```
Debugger attached.
/Users/ted/src/orderscape/foodiebot/node_modules/typegoose/lib/prop.js:95
        throw new errors_1.NoMetadataError(key);
        ^

Error: There is no metadata for the "name" property.Check if emitDecoratorMetadata is enabled in tsconfig.jsonor check if you've declared a sub document's class after usage.

```
I've enabled `emitDecoratorMetadata` in tsconfig.js. using Mongoose 5.2.5, Node 9.2.1, Mongodb 3.6.6, Typescript 2.7.2.

**Comment by teddis** [comment]
sorry pilot error, wasn't fully compiled

**Comment by HarelAshwal** [comment]
Can you explain how you resolved it? 
It doesn't work for me (event with full compilation...)

tsconfig
`{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "noImplicitAny": false,
        "skipLibCheck": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "lib": [
            "es2017",
            "dom"
        ]
    },
    "exclude": [
        "node_modules",
        "client"
    ]
}`

package.json
`
{
  "name": "test-typegoose",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^5.4.11",
    "typegoose": "^5.5.0"
  }
}
`

**Comment by teddis** [comment]
@HarelAshwal Sorry, it's been too long. Good luck, I hope you can resolve it.
