### ISSUE TITLE
mongoose.useDb() multiple databases

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#175]
I want to use the (useDb feature)[https://github.com/Automattic/mongoose/wiki/3.7-%28unstable%29-Release-Notes#connection-pool-sharing] but I'm not sure how to do it with Typegoose.

I tried the following:
```
  const db2 = mongoose.useDb(myDatabaseName)

  const RoomModel = new Room().getModelForClass(Room, {
    existingConnection: db2 // tried existingMongoose too
  })

  const room = new RoomModel()

  await room.save()
```

This works the first time, a database is created if it didn't exist and the save is successful. But if I do another call where `myDatabaseName` is different, it will execute the call on the first database.

How do I get Typegoose to work dynamically with multiple databases?

**Comment by Christilut** [comment]
Had some time to look into this again and figured out a working solution:

```js
export async function addRoom(args: IAddRoomArgs) {
  const newConnection = mongoose.connection.useDb(args.organizationId)

  const NewModel = newConnection.model('Room', RoomModel.schema) as ModelType<Room>

  const room = new NewModel()

  await room.save()

  return room
}
```

**Comment by Christilut** [comment]
Generic version:

```ts
import * as mongoose from 'mongoose'
import { ModelType, InstanceType } from 'typegoose'

export function getModelForDb<T>(databaseName: string, model: InstanceType<T>): ModelType<T> & T {
  const db = mongoose.connection.useDb(databaseName)

  const DbModel = db.model(model.modelName, model.schema) as ModelType<T> & T

  return DbModel
}

```

**Comment by joravkumar** [comment]
It's not working in my case. 
Can you please Explain how to use this with an example and how to make connection with using of typegoose.

**Comment by hasezoey** [comment]
@joravkumar this repo & project got moved to a [new location](https://github.com/typegoose/typegoose) please open a new issue if you still encounter it

**Comment by rohitpotato** [comment]
@hasezoey @Christilut Is ```usedb``` the most performant way to go for implementing multi tenancy?

**Comment by Christilut** [comment]
I didn't use it at scale, only with a few users at a time but I didn't notice any problems

**Comment by sudarshankj** [comment]
Use the following options to limit excessive memory consumption.

const useDbOptions = {
   // makes sure that connections are reused for existing tenants
    useCache: true,
    // no listeners are attached on the main connection. 
    noListener: true
}
 mongoose.connection.useDb(databaseName, useDbOptions);
