### ISSUE TITLE
Incorrect ref data

### ISSUE THREAD

**Issue by next-direction** [szokodiakos/typegoose#176]
Hi, today I stumbled over a strange behaviour including refs. I defined them like in the documentation but meta data in background was not set correctly in my case.

Problem is this code in `src/props.ts`:

```javascript
const ref = rawOptions.ref;
  if (ref) {
    schema[name][key] = {
      ...schema[name][key],
      type: mongoose.Schema.Types.ObjectId,
      ref: ref.name,
    };
    return;
  }

  const itemsRef = rawOptions.itemsRef;
  if (itemsRef) {
    schema[name][key][0] = {
      ...schema[name][key][0],
      type: mongoose.Schema.Types.ObjectId,
      ref: itemsRef.name,
    };
    return;
  }
```

In my case, `ref.name`/`itemsRef.name` was not defined, I had to use `ref.modelName` instead.

**Comment by hasezoey** [comment]
i think this can be closed, because its old and these function got reworked (multiple times?)

@Ben305

**Comment by hasezoey** [comment]
@Ben305 Bump to close
