### ISSUE TITLE
How to create an index on Ref<T> property

### ISSUE THREAD

**Issue by rasikas** [szokodiakos/typegoose#177]
Can you explain how to create an index on Ref<T> property of a document.
Ex:
~~~ts
class User extends Typegoose {
  @prop()
  name?: string;

  @prop({ required: true })
  age: number;

  @prop()
  job?: Job;

  @prop({ ref: Car, required: true }) // How to add an index to this field.
  car: Ref<Car>;
}
~~~

I tried with this
~~~ts
  @prop({ ref: Car, required: true, index: true }) // How to add an index to this field.
  car: Ref<Car>;
~~~

But in the database it doesn't create an index for the `car` property.

Thanks

**Comment by aljazerzen** [comment]
This should work. 

By default Mongoose creates indices only right after connecting (if you have `autoIndex` enabled). If you connect to database then drop collection or something then indices will not be created again. 

In this case you have to call:
```
UserModel.createIndexes();
```

**Comment by ChrisLahaye** [comment]
Use the index decorator, its in the docs

**Comment by hasezoey** [comment]
this can be closed because of no feedback given from the original author if `@index` fixed it and no one other has had this issue

@Ben305
