### ISSUE TITLE
npm deployment key in travis config

### ISSUE THREAD

**Issue by devdoomari3** [szokodiakos/typegoose#178]
Is there any way to keep your deployment key hidden?
(travis must have something for this...)

I can see your npm deployment key right inside .travis.yml :(

**Comment by hasezoey** [comment]
its not a problem, because this key is stored securely at travis.com and the key in the config is just an auth key to access it, so not a problem

this can be closed
@Ben305

**Comment by hasezoey** [comment]
btw in version 6.0.0 / my fork, it got changed to be environment variables instead for a `secure:`
