### ISSUE TITLE
Populated items from an Array of Ref

### ISSUE THREAD

**Issue by fairydhwen** [szokodiakos/typegoose#179]
How can i retrieve populated items from an arrayPro Ref<Item> ?

I posted all the details on https://stackoverflow.com/questions/51825036/add-items-to-an-array-of-ref-with-typegoose

**Comment by fairydhwen** [comment]
Ok, i found it : 
```
    async findAll(): Promise<Player[]> {
        let players = await this.playerModel.find().exec();
        let playersWithItems = new Array<Player>();
        for(let p of players) {
            playersWithItems.push( await p.populate({path: 'items', model: 'Item'}).execPopulate());
        };
        return playersWithItems;
    }
```

**Comment by ONeville** [comment]
More concise:

`  
async findAll(): Promise<Player[]> {
       const players = await this.playerModel.find().exec();
       return players.map(async p => await p.populate({ path: 'items', model: 'Item' }).execPopulate())
 }

`
However loosing performance.
