### ISSUE TITLE
Object is not a primitive type nor a Typegoose schema

### ISSUE THREAD

**Issue by Pikachews** [szokodiakos/typegoose#18]
Is there any way to use typegoose with fields of type 'any' or 'object'?

**Comment by szokodiakos** [comment]
Currently you can only add primitives and Typegoose descendants. This is would be a good addition to the library.

**Comment by vinczedani** [comment]
Hi @Pikachews 
In my experience, you can add typescript class as part of the Schema, but you can not create instanceMethod or staticMethod on the subDocument.
Example code:
```
export class Job {
  @prop()
  title?: string;

  @prop()
  position?: string;

  @prop({ required: true, default: Date.now })
  startedAt: Date;
}

export class User extends Typegoose {
...
  @prop()
  job?: Job;

  @arrayProp({ items: Job })
  previousJobs?: Job[];
...
@instanceMethod 
  addJob(this: InstanceType<User>, job: Partial<Job> = {}) { 
    this.previousJobs.push(job); 
 
    return this.save(); 
  } 
}
```
This works fine for me. I hope it answers your question.
Cheers,
Daniel
