### ISSUE TITLE
How to define an index

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#180]
Hi Folks,

I have a mongoose document with two fields

_id
emailAddress

My schema works fine and entities are going in and out of mongodb good

But I want to create an index so that whenever an entity gets created it ensures those two properties combined are unique... 

Currently the ONLY uniqueness of this collection is for the _id

I want uniqueness to carryover onto the emailAddress

rightnow I can create documents withsame emailAddress and I dont want that to happen

what I want is if one document gets created on an emailAddress I want the uniqueness to be for the _id and emailAddress combined

any help is appreciated

I referred to this post
https://stackoverflow.com/questions/16061744/mongoose-how-to-define-a-combination-of-fields-to-be-unique
but still a bit wishy washy with typegoose since there are no ".index" calls i the codebase

thank you

**Comment by xurei** [comment]
I believe you can use this :
```
    @prop({required: true, unique: true, index: true})
    emailAddress: string;
```

**Comment by aljazerzen** [comment]
@xurei is right. You do not need compound indexes (indexes ensuring uniqueness of combination of fields. Link you provided shows how to declare them with mongoose)

Compound index would prevent the app from adding an two entries with the same `_id` and `emailAddress`, but `_id` is already unique, so this would never happen. You could however add two entries with different `_id`s but same `emailAdress`es. 

I believe this can be closed.

**Comment by nhhockeyplayer** [comment]
Im not sure this is working
has anyone had luck using indexes?
