### ISSUE TITLE
Can't install 5.3.0 version from npm

### ISSUE THREAD

**Issue by tc9011** [szokodiakos/typegoose#185]
I tried to use `validate`, but it is not assignable to parameter of type `PropOptionsWithValidate` in 5.2.1 version. It's a new feature in 5.3.0 version.

I found that the latest version in npm is 5.2.1,  can you fix this problem? thank you

**Comment by mihael998** [comment]
I have got version 5.4.0. and I still cannot use option "validate" in the prop decorator

**Comment by hasezoey** [comment]
@Ben305 this can be closed because versions above 5.3 are released on npm
