### ISSUE TITLE
getModelForClass() does not use options in its cache; move the options somewhere else ?

### ISSUE THREAD

**Issue by xurei** [szokodiakos/typegoose#186]
The `getModelForClass()` function takes a `GetModelForClassOptions` argument, but this argument is never used in the cache mechanism.

Hence, if you call `getModelForClass` with different options, the cache will not notice it and the returned Model won't be the one expected.

I guess it doesn't much make sense to create two different Model from the same class. I suggest that the `GetModelForClassOptions` should be placed somewhere else.

The ideal thing for me would be something like this :
```typescript
@modelOptions({
    existingMongoose: /* ... */, 
    existingConnection: /* ... */,
    schemaOptions: /* ... */, 
})
export class Entity extends Typegoose { /* ... */ }
export const Model = new Entity().getModelForClass(Entity); //No more option allowed here
```
This way, you cannot use differents options anymore on the same class and you can use `getModelForClass()` multiple times without fear.

The alternative would be to use the options as keys in the cache. But it seems useless from my point of view.

What do you think ? I'm willing to write a PR if this makes sense to everyone.

**Comment by hasezoey** [comment]
as with version 6.0.0 model options are moved to the `@modelOptions` decorator

@Ben305 This can be closed
