### ISSUE TITLE
Self-containing class: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Pikachews** [szokodiakos/typegoose#19]
If you have a class that contains itself, you get a maxed call stack error.
For example,
```
class Thing {
    @arrayProp({ items: Thing })
    other: Thing[];
}
```

**Comment by szokodiakos** [comment]
Hey! Thanks for the heads up, I haven't thought about this yet. I will add a bug label and will try to code the solution if I will have the time.

**Comment by ardyfeb** [comment]
same here

**Comment by hasezoey** [comment]
@Ben305 this can be closed in favor of https://github.com/hasezoey/typegoose/issues/42
