### ISSUE TITLE
Class / Model Function is not a function

### ISSUE THREAD

**Issue by xAvarice** [szokodiakos/typegoose#195]
ES6
```
User.find({}, (err, users) => {
	users.forEach(user => {
		console.log(Object.getOwnPropertyNames(user));
	})
});
```

Output
` ['$__', 'isNew', 'errors', '_doc', '$init' ]`

Class
```
import RequestHandler from 'core/common/http/RequestHandler';
import ProxyAgentManagement from 'core/common/http/ProxyAgentManagement';
import Request from 'request-promise';
import { prop, Typegoose, InstanceType, instanceMethod } from 'typegoose';

class User extends Typegoose {
	@instanceMethod
	bootstrap() {
               ....
	}
}

const UserModel = new User().getModelForClass(User);
export default UserModel;
```

Is the 	@instanceMethod decorator in the readme supposed to be 	@instanceMethod()?
I read in another issue that it isn't even required any more?

**Comment by hasezoey** [comment]
it is `@instancemethod` not `@instancemethod()`

> I read in another issue that it isn't even required any more?

this was never said, just considered to be in branch `feature/4`, which never finished

---

-> is this still a problem?

**Comment by hasezoey** [comment]
As with version 6.0.0 `@instanceMethod` (& `@staticMethod`) are deprecated in favor of `schema.loadClass` (native from mongoose)

@Ben305 This can be closed
