### ISSUE TITLE
Feature request: Add "trim" and "select" options to @prop decorator

### ISSUE THREAD

**Issue by nicky-lenaers** [szokodiakos/typegoose#197]
Currently, I can't do:

```ts
@prop({
  trim: true
})
```

or

```ts
@prop({
  select: true
})
```

Especially the latter one is one that is required by my setup, as it is used by GraphQL functions to resolve certain types.

Mongoose actually has e.g. the `trim` option, see excerpt [taken from docs](https://mongoosejs.com/docs/schematypes.html):

> String
lowercase: boolean, whether to always call .toLowerCase() on the value
uppercase: boolean, whether to always call .toUpperCase() on the value
**trim: boolean, whether to always call .trim() on the value**
match: RegExp, creates a validator that checks if the value matches the given regular expression
enum: Array, creates a validator that checks if the value is in the given array.
minlength: Number, creates a validator that checks if the value length is not less than the given number
maxlength: Number, creates a validator that checks if the value length is not greater than the given number

I'd like to request implementation for this feature, thanks!

**Comment by alexandrucancescu** [comment]
I also need the select, I think this should already be part of the package as it only requires passing one more option to mongoose. Thanks a lot, great work!

**Comment by marcinkumorek** [comment]
As for `select` you can add it, and it will work. 
But you'll have to either:
- add `// @ts-ignore` above the line with `select`
- update `BasePropOptions` in `/lib/prop.d.ts`

**Comment by neckaros** [comment]
Hello,
having access to lowercase and uppercase would also be great!

Thanks

**Comment by neckaros** [comment]
I send a pull request with tests and update in schema: #217 

Could you please merge it @szokodiakos if it is ok with you?

**Comment by vsternbach** [comment]
> As for `select` you can add it, and it will work.
> But you'll have to either:
> 
> * add `// @ts-ignore` above the line with `select`
> * update `BasePropOptions` in `/lib/prop.d.ts`

Actually, it's not working with select, it still returns this prop on create

**Comment by a1p4ca** [comment]
`select` is still not implemented.

**Comment by shilangyu** [comment]
`select` is a pretty important feature and is still missing

**Comment by hasezoey** [comment]
@a1p4ca  @shilangyu now it is, when the merge is accepted

**Comment by shilangyu** [comment]
Is this the correct implementation of select? Currently if i set select to false this field isnt even added to the database, AFAIK select should just exclude this field from queries (`User.find()` for example) unless i explicitly tell them to. This works in mongoose

**Comment by hasezoey** [comment]
@shilangyu select, as many other parameters are just passed-through to mongoose, in my case it added it to the database, but just not returned it, show it should...?

as a Note: i dont know use cases, or the right respone it should give, so i just took what i got and passed it through to mongoose, and in the tests i tested against what i thought was right, please correct me/it when i was wrong

**Comment by shilangyu** [comment]
Example use case is passwords, i want it to be stored in the database however i dont want it to be returned after a query (i explicitly select a password when authenticating only). I understand you just pass it to mongoose, in this case i will further investigate it. Maybe adding a test case:
```ts
it('should return the unselected field', async () => {
    const selecttest = new Select();
    await selecttest.save();

    const foundselect = (await Select.findById(selecttest.id).select('+test1').exec()).toObject();
    expect(foundselect).to.have.property('test1');
    expect(foundselect).to.have.property('test2', 'testing 2 should be included');
    expect(foundselect).to.not.have.property('test3');
  });
```
Would make sure the field is in the database but not returned?

**Comment by hasezoey** [comment]
@shilangyu i am adding / improving the select tests, and i notice, you are right, only the not default `{select: false}` are saved ... but i really dont know why

**Comment by hasezoey** [comment]
@shilangyu lets move the conversation / bug "report" to #326
