### ISSUE TITLE
Possible to use the same model in the front end?

### ISSUE THREAD

**Issue by dulichan** [szokodiakos/typegoose#2]
Hi guys,
Is it possible to use the same class on the front end of the app? (For example on an Angular app)?
Cheers~

**Comment by guenam** [comment]
In case this helps somewhat: I tried using mongoose models on the front end with Angular and found out it could not work. At least, so said one of the main maintainer on the project github. And he also said they didn't see the need: mongoose is for the back end, period.

**Comment by szokodiakos** [comment]
@dulichan I don't know if @guenam got your question right. If I am correct you want to reuse the defined class on the frontend side so you dont have to create a separate interface/class for the model.

I honestly haven't thought about it until now, but in my opinion you can use the class on the frontend side safely. However you will see the - user defined and non-existing on frontend - static and instance Mongoose methods which should be ignored, but for attribute properties it should be OK.

I will test it myself and if it's successful, I will add this "feature" to the documentation.

**Comment by vinczedani** [comment]
This issue seems to be dead. Closing it.
If there is some update on this, feel free to reopen.

**Comment by foolisheep** [comment]
Is there a conclusion that typegoose-inherited classes can or cannot be used in front end? @szokodiakos
