### ISSUE TITLE
Ref is saved as subdocument

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#204]
I'm referencing another typegoose object but for some reason it is saved as the full object as subdocument in the database.

The Invoice class has a reference to Organization: 
```js
export class Invoice extends Typegoose {
  @prop({
    required: true,
    ref: Organization
  })
  organization: Ref<Organization>
}
```

It is saved in this method from the Organization class:
```js
@instanceMethod
async getOrCreateInvoice(this: InstanceType<Organization>) {
     const invoice = new InvoiceModel()
     invoice.organization = this
    await invoice.save()
    // etc
}
```

With arrays and `itemRef` it works as expected, ie it only saves ObjectId's.

Any ideas?

**Comment by Christilut** [comment]
This is my workaround:
```js
  invoice.organization = mongoose.Types.ObjectId(this.id)
```

But I'd rather not have to use this

**Comment by JakeAi** [comment]
@Christilut I have the same issue. It just started randomly happening and breaking everything.

**Comment by JakeAi** [comment]
@Christilut The only thing i can think of is i added (below) instead of just using one connection.

```TS
export module mongodb {
    export let site: Connection = null;
    export let app: Connection = null;

    mongoose.Promise = require( 'bluebird' );
    app = mongoose.createConnection( MONGODB_APP_URI_LOCAL, {} );
    site = mongoose.createConnection( MONGODB_URI, {} );
}
```

**Comment by Christilut** [comment]
I'm not sure how this relates to my issue actually

**Comment by JakeAi** [comment]
Those are my models, and my code being used.

```
let user = await UserModel.findOne( { _id: '5bae832f5ab07f0e68e89451' } );
let cart1 = await CartModel.findOne( { _id: '5bae832f5ab07f0e68e89470' } );
let cart2 = await CartModel.findOne( { _id: '5bae832f5ab07f0e68e89475' } );
let log1 = await LogModel.findOne( { _id: '5bbe1f6cc855056010a0e760' } );

cart1.user = user;
cart2.user = user;
log1.user = user;

await cart1.save();
await cart2.save();
await log1.save();

```
cart 1 and 2 both save user as a subdocument. log saves user correctly as a ref

**Comment by Christilut** [comment]
Ah okay. I got confused by the 2 mongoose connections which I didn't think relate.

What you can do is check the `LogModel.schema` and `CartModel.schema` after it is constructed, it contains schema definitions and might show some difference between the two.

**Comment by JakeAi** [comment]
Looks like CartModel.schema User turns into a mixed 
```
[Node]     user:
[Node]       Mixed {
[Node]         path: 'user',
[Node]         instance: 'Mixed',
[Node]         validators: [],
[Node]         setters: [],
[Node]         getters: [],
[Node]         options: [Object],
[Node]         _index: null,
[Node]         defaultValue: null,
[Node]         '$parentSchema': [Circular],
[Node]         [Symbol(mongoose:schema_mixed)]: true },
```

Where as LogModel ends up being correct as ObjectID
```
[Node]      user:
[Node]       ObjectId {
[Node]         path: 'user',
[Node]         instance: 'ObjectID',
[Node]         validators: [],
[Node]         setters: [],
[Node]         getters: [],
[Node]         options: [Object],
[Node]         _index: null,
[Node]         '$parentSchema': [Circular] },
```

**Comment by Christilut** [comment]
I'm seeing the same thing here.

**Comment by JakeAi** [comment]
@Christilut My hacky fix for now is to implement this on my models.
```TS
@pre<Cart>( 'save', function ( next ) {
    fixRef( this, 'user' );
    // fixRef( this, 'anotherRefProp );
    next();
} )
```
```TS
import mongoose from 'mongoose';

export function fixRef( scope, ref: string ): void {
    if ( scope[ ref ] && scope[ ref ]._id ) { scope[ ref ] = mongoose.Types.ObjectId( scope[ ref ]._id ); }
}
```

**Comment by Christilut** [comment]
Thanks for sharing. Maybe someone with Typegoose knowledge can find the problem. I'm not an expert enough in TS for this

**Comment by JakeAi** [comment]
One thing I did notice about this issue in particular on my end, was not every Cart has a `user` at the moment in my MongoDB. So TECHNICALLY it could be a `User` ref or `undefined`. Does your DB `invoice.organization` all have values? Maybe Mongoose scans the DB to validate the models that are created by us?

**Comment by Christilut** [comment]
Yeah with my test setup there is only 1 invoice in the database. So I don't think that's it. It seems the schema generation is going wrong somewhere. Typegoose is kind of black magic to me since I don't have that much Typescript knowledge.

**Comment by gentleShark** [comment]
@Christilut  @JakeAi @szokodiakos I'm trying to store a simple two-field Typegoose object (which has to be a Typegoose objject because one of the two fields is a Ref and the other field just defines an enum scope) as a subdocument but I'm running across what seems to be the default behavior of a new collection being created instead of a subdocument. did you figure out the key to switching between the creation of subdocuments and collections? I see in the example @JakeAi  provided that his log model defined a collection name in the schemaOptions. In my case, I'm not passing collection as an option in schemaOptions in any of my model classes and the default behavior is that mongo collections are created.

**Comment by hasezoey** [comment]
@Christilut @JakeAi @gentleShark is this still a problem with typegoose 5.8.1+?
when yes, could someone provide an reproduce-able code, that is not so long, thanks?

**Comment by gentleShark** [comment]
not sure if it's still a problem. I refactored my typegoose models to work around the problem. here's a simple setup to test to see if sub-documents with refs are possible now:
```
export class Car extends Typegoose {
	@Field()
	readonly _id: ObjectId;

	@prop()
	make: string;

	@prop()
	model: string;
}

export class User extends Typegoose {
	@Field()
	readonly _id: ObjectId;

	@prop()
	name: string;
}

export class CarPurchase extends Typegoose {
	@Field()
	readonly _id: ObjectId;

	@prop()
	buyer: Ref<User>;

       @prop()
	referral: Referral;
}

export class Referral {
    @prop()
    referrer: Ref<User>;
    
    @prop()
    referralDiscount: number;
}
```

**Comment by hasezoey** [comment]
@gentleShark was the problem only with type-graphql or without too? (not tested yet, just noticed `@Field()`

**Comment by gentleShark** [comment]
the @Field() just snuck in there because I was copying from a model that
was also using type-graphql but the problem I encountered when trying to
store refs in sub-documents was strictly a typegoose issue.

**Comment by hasezoey** [comment]
@gentleShark just wanted to confirm that it is with only typegoose, thanks, will test later.

**Comment by hasezoey** [comment]
@gentleShark i "improved" your example with:
- removing type-graphql things
- adding { ref: } to the prop options (where they should be)

and got no error, just works fine:
```ts
import * as mongoose from "mongoose";
import { prop, Ref, Typegoose } from "./typegoose/src/typegoose";

class Car extends Typegoose {
    @prop()
    public make: string;

    @prop()
    public model: string;
}

class User extends Typegoose {
    @prop()
    public name: string;
}

class Referral extends Typegoose {
    @prop({ ref: User })
    public referrer: Ref<User>;

    @prop()
    public referralDiscount: number;
}

class CarPurchase extends Typegoose {
    @prop({ ref: User })
    public buyer: Ref<User>;

    @prop({ _id: false })
    public referral: Referral;

    @prop({ ref: Car })
    public car: Ref<Car>;
}

const CarModel = new Car().getModelForClass(Car);
const UserModel = new User().getModelForClass(User);
const CPModel = new CarPurchase().getModelForClass(CarPurchase);
const ReferralModel = new Referral().getModelForClass(Referral);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify204",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const car = await CarModel.create({ make: "something", model: "TeslaS" } as Partial<Car>);
    const user = await UserModel.create({ name: "someone" } as User);
    const rfl = await ReferralModel.create({ referralDiscount: 1, referrer: user } as Partial<Referral>);
    const cp = await CPModel.create({ buyer: user, car, referral: rfl } as Partial<CarPurchase>);

    const found = await CPModel.findById(cp.id).populate("car").populate("buyer").exec();
    console.log(found);

    await mongoose.disconnect();
})();
```

so i consider this as solved?
@Ben305 @Christilut

**Comment by Christilut** [comment]
I'll have to refactor my code with the new typegoose version and run my tests. I'll try to do this in the next few days or so

**Comment by hasezoey** [comment]
as a note for anyone coming by, [in this comment](https://github.com/szokodiakos/typegoose/pull/348#discussion_r307779538) is an example extension for typeguards

**Comment by tmarhem** [comment]
Thanks for the help on this topic here.
I upgraded my typegoose to the lastest 5.9.0 version and I still have this issue.
In my case, I am trying to update a reference in a subObject of my model, and in that case it updates it as an object instead of only the object id.
@hasezoey The only difference I see with your example is 'as Partial<T>', could this have any impact on the expected result?

**Comment by hasezoey** [comment]
> @hasezoey The only difference I see with your example is 'as Partial', could this have any impact on the expected result?

you can just use `as ClassName`, but at somepoint (i dont know when) it will get wrong, and wants the functions form the Typegoose class, thats why i make it as `as Partial<ClassName>` because so it dosnt get this error, but makes *every* property "optional", and thats a problem, that i will try to fix in #365, you could use `Exclude<ClassName, something>`, but currently i dont know how to use this and has potential issues with virtual functions & instancemethods...
(and the `as something`  is just to get at least *some* infomation of what properties can get set with type infomation, even if it is just set as optional by `as Partital<ClassName>`)

PS: sorry for this long text

**Comment by hasezoey** [comment]
@tmarhem could you give me an reproduceable example of how you use it that results in the object getting stored?

**Comment by tmarhem** [comment]
`import { User } from './userModel';
import { pre, prop, arrayProp, Ref, Typegoose } from 'typegoose';
import { Skill } from './skillModel';
import { Client } from './clientModel';
import { Shared } from '../shared';

enum State {
    IN_DEVELOPMENT = 'IN_DEVELOPMENT',
    IN_PRODUCTION = 'IN_PRODUCTION',
    STAND_BY = 'STAND-BY',
    NEGOCIATING = 'NEGOCIATING',
    STOPPED = 'STOPPED',
    CANCELED = 'CANCELED',
}

enum Type {
    ER = 'ER',
    IR = 'IR',
    CIR = 'CIR',
}

enum Job {
    UXDESIGNER = 'UXDESIGNER',
    DEVELOPER = 'DEVELOPER',
    LEADTECH = 'LEADTECH',
    SCRUMMASTER = 'SCRUMMASTER',
    MANAGER = 'PRODUCTOWNER',
    PROJECTLEADER = 'PROJECTLEADER',
}

class ProjectSettings extends Typegoose {
    @prop({
        default: 'NA',
    })
    gitlabId!: string;

    @prop({
        default: 'NA',
    })
    openprojectName!: string;

    @prop({
        default: 'NA',
    })
    jenkinsName!: string;

    @prop({
        default: 'NA',
    })
    gkeName!: string;
}

class UserOfProject extends Typegoose {
    @prop({
        ref: User,
    })
    user!: Ref<User>;

    @prop({
        enum: Job,
        required: true,
        default: Job.DEVELOPER,
        uppercase: true,
    })
    projectJob?: Job;

    @prop() tjm?: Number;
}

class Project extends Typegoose {
    @prop({
        required: true,
    })
    name?: string;

    @prop()
    description!: string;

    @prop({
        default: Date.now(),
    })
    dateCreated?: Date;

    @prop({
        default: 0,
    })
    progress?: number;

    @arrayProp({
        items: UserOfProject,
    })
    users?: UserOfProject[];

    @arrayProp({
        items: UserOfProject,
    })
    positions?: UserOfProject[];

    @prop() entity?: string;

    @prop({
        ref: Client,
    })
    client?: Ref<Client>;

    @prop({})
    projectSettings?: ProjectSettings;

    @arrayProp({ itemsRef: Skill })
    skills?: Ref<Skill>[];

    @prop({
        enum: State,
        required: true,
        default: State.STAND_BY,
        uppercase: true,
    })
    state?: State;

    @prop({
        enum: Type,
        default: Type.CIR,
        uppercase: true,
    })
    type?: Type;

    @arrayProp({ items: String })
    otpCodes?: string[];

    @arrayProp({ itemsRef: { name: 'UserModel' } })
    admins?: Ref<User>[];
}

const UserOfProjectModel = new UserOfProject().getModelForClass(UserOfProject);
const ProjectModel = new Project().getModelForClass(Project);
export { Project, UserOfProject, ProjectModel, UserOfProjectModel, State, Type };
`

That is what my model looks like, reproduceable example is complicated with all the classes interactions though. The thing is when I try to update the "skills" property, everything goes well and the populated skill "casts" as its object id upon saving.
Although, when I do the same with the "positions" property, which is a 'UserOfProject' subobject, it does not work and saves the whole object in positions[x].user

**Comment by hasezoey** [comment]
@tmarhem, because it is so long, could you setup an reproduce-repo? (that includes everything needed and how its called?)

**Comment by tmarhem** [comment]
@hasezoey as the project in our private company repository and this is a specific part of it I don't think I will be able/authorized to make a fucntionning repo out of it.
Concerning the Ref<T> subject at positions, the thing is my UserOfProject is a subobject but not a reference. I did this to better separate the different parts of my main class Project. 
In the database, UserOfProject is a plain object, not a reference,but it does contain a reference to a user. That is why it has no Ref<T> in my model. I actually tried to use it as a ref just in case, but it broke the thing completely.
Could it be the fact of including SubClasses as plain objects and not references that goes bad ?

**Comment by hasezoey** [comment]
> as plain objects

typegoose dosnt support plain objects
only nested schemas are supported (like you have done in the (long) example above)

---

> I don't think I will be able/authorized to make a functioning and open repo out of it.

i would just need to know the models that are used (stripped down to only the necessary parts) and how it is called to investigate this (i dont need the whole project...)

---

PS: sorry if some assumptions in this comment are wrong, because my last response is older then 6 days now, in the mean time i had other issues and working on release 6

**Comment by tmarhem** [comment]
Here's an extract from Typegoose README:
```
class Job {
  @prop()
  title?: string;

  @prop()
  position?: string;
}

class Car extends Typegoose {
  @prop()
  model?: string;
}

class User extends Typegoose {
  @prop()
  name?: string;

  @prop({ required: true })
  age!: number;

  @prop()
  job?: Job;

  @prop({ ref: Car })
  car?: Ref<Car>;
}
```

If I translate it to my Issue it would be

```
class Job {
  @prop(
ref: Car,
)
  jobCar?: Ref<Car>;
}

class Car extends Typegoose {
  @prop()
  model?: string;
}

class User extends Typegoose {
  @arrayProp(
items: Jobs,
)
  jobs?: Job[];

@arrayProp(
itemsRef:Car,
)
cars?:Ref<Car>[],

}
```

Here, when I get the document and later save it, "cars" objects would be casted into their IDs but "jobCar" would not and saves as plain object. 
So I guess I cannot use 'Job' as a Subclass containing a Ref if it is not going to be referenced as a Ref itself in the parent Object(here User)?
I'll try to book time to make a repo out of this example next week.

**Comment by hasezoey** [comment]
will investiage this, after i finished the next feature for r6

**Comment by hasezoey** [comment]
@tmarhem @Christilut @JakeAi is this issue still a problem with 5.9.x / v6.0.0?
when yes, please open a new issue at the new repo, thanks

@Ben305 this can be closed as "stale" / "fixed?"
