### ISSUE TITLE
timestamps option no longer working

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#206]
I use the timestamps option from mongoose to automatically add created and updated timestamps but they don't seem to work anymore. 
I tested this with typegoose 5.4.0 and mongoose 5.3.1.

Minimal reproduction:
```js
var mongoose = require('mongoose');
import { prop, Typegoose, InstanceType, staticMethod, instanceMethod, pre, Ref } from 'typegoose'

mongoose.connect('mongodb://localhost/bug');

class Kitten extends Typegoose {
  @prop()
  name: String
}

const KittenModel = new Kitten().getModelForClass(Kitten)

KittenModel.schema.set('timestamps', true);

(async () => {
  var fluffy = new KittenModel()

  await fluffy.save()

  console.log('saved')

  process.exit(0)
})()
```

Notice in the database that `createdAt` and `updatedAt` are not added to the record.

**Comment by strathausen** [comment]
Have you tried passing the options to `getModelForClass`?

```
const KittenModel = new Kitten().getModelForClass(Kitten, { schemaOptions: { timestamps: true }})
```

**Comment by Christilut** [comment]
Thanks that does work.

**Comment by seyaobey** [comment]
I would like to add that in my case the `updatedAt` is not updating when I call `updateOne`. The value remains the original value when this record was created although I set `schemaOptions: { timestamps: true }` when I create model with `getModelForClass`.

Any help would be greatly appreciated
