### ISSUE TITLE
In pre save hook `this` does not refer to document

### ISSUE THREAD

**Issue by dkimot** [szokodiakos/typegoose#212]
I'm using Typegoose version 5.2.1 which uses Mongoose version 5.0.16.

In my pre-save hook I cannot get this to refer to the document. Instead, I get an object that contains the constructor function for the model, the default model, information on the database connection, info on the model collection, and info on the schema.

I initially used an async/await function but upon investigating the Mongoose model's Kareem object, where all the hooks are stored, found that Kareem or Mongoose expect an identifier if the hook is async/await and Typegoose does not appear to provide that. So I switched over to the callback model with no results.

I also tried using the `(this: ModelType, ...)` notation instead of the `<T>` notation.

I suspect there is some kind of context error but I don't know where to look. I also don't know for sure that this is a Typegoose, and not a Mongoose error.

Any help would be appreciated, thanks.

**Comment by JakeAi** [comment]
can you provide code?

**Comment by Christilut** [comment]
I have the same problem.

In my pre hook `this` is of type `TypegooseDoc<MyClass>` but in my post hook `this` is of type `any`.

Neither seems to be working correctly.

```js
@pre<MyClass>('validate', async function () {
 })
```

and
```js
@post<MyClass>('save', async function () {
})
```

**Comment by AramZS** [comment]
@Christilut You must pass the `next` function to your callback and call it for it to work.
```
@pre<MyClass>('validate', function (next) { 
	if (this.startDate >= this.endDate) {
		const errorMsg = new Error('Start date before end date.');
		next(errorMsg);
	} else {
		next();
	}
})
export class MyClass extends Typegoose {
```

**Comment by Christilut** [comment]
It was my understanding that I don't need to do that because I'm using the `async` version of the hook.

**Comment by vsternbach** [comment]
probably also worth mentioning that it's not working with arrow function in pre hook

**Comment by hasezoey** [comment]
this can be closed, because it is not an typegoose issue
-> in v6.0.0 the types for `@pre` & `@post` are updated, but still not an issue with typegoose

@Ben305
