### ISSUE TITLE
What about GridFS ?

### ISSUE THREAD

**Issue by nesteban-aldera** [szokodiakos/typegoose#216]
HI,

A question, not an issue. Is there a way to use buckets with grid-fs with Typegoose ? There is an additionnal lib called `mongoose-gridfs`, is it compliant with Typegoose ?

Thanks in advance

**Comment by hasezoey** [comment]
in theory, gridfs works, but you need to define an own model/schema for it, but currently its not officially supported

@Ben305 could you label "enhancement"?

**Comment by hasezoey** [comment]
i investigated it and tried my best for this, here is the current state on it https://github.com/hasezoey/typegoose/pull/10

-> if anyone can/wants to continue it, please be free todo so

**Comment by hasezoey** [comment]
@Ben305 this can be close in favor of https://github.com/typegoose/typegoose/pull/10 for full migration
