### ISSUE TITLE
How to validate on update

### ISSUE THREAD

**Issue by alex-deas** [szokodiakos/typegoose#221]
I'd like to reuse validation functions which are run on document creation to also be used for updates but can't seem to find anything which will do this.

What I currently have is:
```js
Model.updateOne(
  { _id: Types.ObjectId(id) },
  {
    name
  }
).then(data => {
   ...
}).catch(err => {
  // handle validation error
})
```

Is there a way to run an object through validation before updating? I can't seem to find a method using `@pre("update")`

**Comment by hasezoey** [comment]
since #353 you can use `@pre(/^update.*/, () => {})` (RegExp)

so this could be closed
@Ben305
