### ISSUE TITLE
delay schema create 

### ISSUE THREAD

**Issue by chianquan** [szokodiakos/typegoose#222]
I love the `  @prop({ref: User})` mode to define the field type . In my project there are many table schema dependence each other,that cause cyclic dependencies problem when use `  @prop({ref: User})` . 
Maybe it can support `  @prop({ref: ()=>User})` mode and delay the schema create to the model create.
If not ,I can only use `  @prop({ref: "User"})`  mode (use string ref).

**Comment by hasezoey** [comment]
sorry, but i know no way to fix this, because `ref` is just passed through to mongoose, and would have to implement schema handling in typegoose itself

-> is this still a problem?

**Comment by hasezoey** [comment]
this could be considered as a duplicate of #211
