### ISSUE TITLE
schema defined extend from parent class.

### ISSUE THREAD

**Issue by chianquan** [szokodiakos/typegoose#223]
```
class Base{
@prop()
field1:string;
}
class Child extend Base{
@prop()
field2:string;
}

export class DataSet extends Typegoose {
   @prop()
   obj:Child;
}
```

Request to support the Child schema extend the Base's `field1` field.

**Comment by aoi-umi** [comment]
> 
> 
> ```
> class Base{
> @prop()
> field1:string;
> }
> class Child extend Base{
> @prop()
> field2:string;
> }
> 
> export class DataSet extends Typegoose {
>    @prop()
>    obj:Child;
> }
> ```
> 
> Request to support the Child schema extend the Base's `field1` field.


you can try to use [this package](https://www.npmjs.com/package/mongoose-ts-ua)

**Comment by hasezoey** [comment]
@chianquan your question is a bit unclear to me, could you write a bit more what you request?

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" & "unclear"

inheritance is supported in 5.7+ (this is the first version i know has stable inheritance)
