### ISSUE TITLE
Accessing document's _id from virtual property

### ISSUE THREAD

**Issue by rosscoombes** [szokodiakos/typegoose#224]
Apologies if this is elsewhere but I've failed to find the answer.

I have created a Model and I wanted to define a virtual property, I can access all the other model properties except _id., at least not in a proper Typescript manner.

@prop()
    get tags() : Promise<Tag[]> {
        console.log(this._id);  //not valid, doesn't compile in TS
        console.log(this['_id']);  //does actually work
        ....
    }

Just wondered whether there was a better approach for this?

**Comment by JakeAi** [comment]
```TS
@prop()
get tags( this: InstanceType<ModelType<Tag>> & typeof TagModel ): Promise<Tag[]> {
	console.log( this._id ); //does work and compiles
	console.log( this[ '_id' ] ); //does work
}

```

**Comment by rosscoombes** [comment]
It works beautifully, thank you!

**Comment by nick4fake** [comment]
@JakeAi it doesn't work anymore https://github.com/microsoft/TypeScript/issues/39254
