### ISSUE TITLE
Typegoose binding reference to polymorphic model

### ISSUE THREAD

**Issue by Dr-klo** [szokodiakos/typegoose#226]
I have a situation with polymorphic models

```
interface IEvent {
    title: string;
}
class SubscribeEvent implements IEvent {
    @prop()
    title: string;
    @prop({ref: User})
    user: IUser;
}
class NewsEvent implements IEvent {
    @prop()
    title: string;
    @prop({ref: Post})
    post: IPost;
    @prop({ref: User})
    user: IUser;
}
class OrderEvent implements IEvent {
    @prop()
    title: string;
    @prop({ref: Order})
    order: IOrder;
}
```

Now I created a typegoose model: 
```
class Card extends Typegoose {
    @prop()
    name: string;
    @prop()
    events: IEvent[];
}
```
How do I correctly map and extract the Card instance with populated references?

Need a 2 solution, when events is list of embedded documents, and when events stored in another collection.
Thanks.
[StackOverflow Question](https://stackoverflow.com/questions/53520436/typegoose-binding-referernce-to-polymorphic-model)

**Comment by hasezoey** [comment]
> ```ts
>@prop()
>events: IEvent[];
>```

you should change it to
```ts
@prop({ ref: Event }) // cant use interfaces for this
events: Ref<Event>[] // you could use interfaces for this, but shouldnt
```
Note: you cant use interface for this

---

> Need a 2 solution, when events is list of embedded documents, and when events stored in another collection.

Not possible with reasonable type completion. (by design)

**Comment by hasezoey** [comment]
with v6, you can use mongoose's discriminators

@Ben305 this can be closed as "stale" and "solved?"
