### ISSUE TITLE
Any way to make @prop decorator default?

### ISSUE THREAD

**Issue by cktang88** [szokodiakos/typegoose#229]
I find that I would often like nearly all of my fields in my classes, and it's inconvenient to add a `@prop()` to each field. Instead, is there a way to make it default, or have a `@noprop()` to add to fields we _don't_ want in the Mongoose model instead?

**Comment by hasezoey** [comment]
sorry, this is not possible in TS & JS, as far as i know

**Comment by hasezoey** [comment]
as an addition: it *would* be possible, but only when no options were given, but mostly they do, and #48 to be the coding style
