### ISSUE TITLE
Limited Hooks methods

### ISSUE THREAD

**Issue by ikuriel** [szokodiakos/typegoose#23]
type Method = 'init' | 'validate' | 'save' | 'remove';

please add all methods, like 'findOne', 'find' ... etc.

i can't create a class with @pre findOne

**Comment by ikuriel** [comment]
or just allow any string:

type Method = string;

**Comment by danigomez** [comment]
One work around is to assert to `any `type when using pre, i.e :
`@pre<Type>("find" as any, function(next){...})`

**Comment by ikuriel** [comment]
i'll try this way later, i had to rollback to the old model :(

but i still think this should be handled/added by typegoose.

regards.

**Comment by ikuriel** [comment]
with a recursive search of methods that returns Query from Mongoose.

**Comment by szokodiakos** [comment]
Hello, there is a PR for this and I will add it to the project ASAP
