### ISSUE TITLE
Document the use of ! for required props

### ISSUE THREAD

**Issue by ctrlplusb** [szokodiakos/typegoose#232]
It appears that when `strictPropertyInitialization` is enabled you need to add a ! to the definitions of any of your props that are "required" otherwise you will see a TS error similar to "Property 'foo' has no initialiser and is not definitely assigned in the constructor".

e.g.

```typescript
export class User extends Typegoose {
  @prop({ required: true })
  name!: string;

  @prop({ required: false })
  name?: age;
}
```

Related:
 - https://github.com/Microsoft/TypeScript-Vue-Starter#using-decorators-to-define-a-component
 - https://github.com/kaorun343/vue-property-decorator/issues/81

**Comment by WangLarry** [comment]
Try adding "strictPropertyInitialization": false to your compiler options.

**Comment by dgreene1** [comment]
@WangLarry I would not recommend turning off "strictPropertyInitialization". It's there to prevent a class from having a constructor that forgets to set each of the properties. 

@ctrlplusb I think the correct way to write that is:

```
export class User extends Typegoose {
  @prop({ required: true })
  name: string;

  @prop({ required: false })
  name?: age;

  constructor(name:string){
    this.name = name;
  }
}
```

After you do that, then your class will always have a way of ensuring that name is set. As for the use of `!`, that's just a way of telling TypeScript that "no it really is a truthy string." But in practice, you have no way of preventing someone from doing the following:
```
const aNamelessUser = new User();
// But if you add non-default constructor as I showed above, then TypeScript will require you to pass in a name
const aNamedUser = new User("George Smith");
```

**Comment by mamoru-kun** [comment]
I faced the same problem. I downgraded to  Typescript 2.9.2 and the error is gone. But, I think, this is not how you want to solve this.

**Comment by Drageaux** [comment]
@dgreene1 Wouldn't having a `constructor` require you to pass in the args in the exact same order when creating a new object? That would generate redundant code (setting arg to prop) and would disable passing in object literal params `new User({age: 33', gender: 'Male', name))`.

Imagine if `name` was your last argument while the rest were nullable, you would have to do this `new User(null, null, null, name);`
