### ISSUE TITLE
@prop({required: true, ref: "Prova"}) problem

### ISSUE THREAD

**Issue by pome90** [szokodiakos/typegoose#235]
It seems @prop decorator with ref and required=true in the same time doesn't work as expected.
When I try to save to Mongo without the required field no exceptions occur.

```
export class Test extends Typegoose{

  @prop({ required: true})
  name: string
}

@pre<MyClass>('save', async function(next) {
  this.secret = await crypto.randomBytes(32).toString('hex');
  next();
})
export class MyClass extends Typegoose {
  @prop({ required: true, default: mongoose.Types.ObjectId()})
  _id?: mongoose.Types.ObjectId;

  @prop()
  secret: string;

  @prop({required: true, ref: "Test"})
  test: Ref<Test>;
```

**Comment by ZVER3D** [comment]
You dont need quotation marks around your ref class.
Try this:
```typescript
@prop({required: true, ref: Test})
test: Ref<Test>;
```

**Comment by Noja13it** [comment]
@ZVER3D This issue still occurs without quotes

This doesn't result in exceptions when the user field is omitted.
`@prop({ required: true, ref:User })
  user: Ref<User>;`

**Comment by djgorilla** [comment]
@Noja13it 

Currently im doing:

`
@prop({ required: true })
@prop({ ref:User })
user: Ref<User>;
`

**Comment by techaks** [comment]
when it will work dude

**Comment by hasezoey** [comment]
@Ben305 this can be closed because of no further infomation / no reproduce snippets

-> if someone still has this issue, please open a new issue with the infomations given

**Comment by cesar3030** [comment]
Hi there!

I'm still having the issue. I need `require: true` and `ref: user` to be in two different `@prop({...})` decorators if I want the require feature to work.

Does not work:
```typescript
@prop({ required: true,  ref: User})
user: Ref<User>;
```

Does work:
```typescript
@prop({ ref: User })
@prop({ required: true })
user: Ref<User>;
```

I'm using Typegoose: ^5.7.2

**Comment by hasezoey** [comment]
@cesar3030 we only support the latest version (currently 5.9.0), so please try to use this, if it still happens, please try to use 6.0.0 [#365]

**Comment by cesar3030** [comment]
I'll upgrade and keep you posted 👍

**Comment by cesar3030** [comment]
I upgraded Typegoose to 5.9.0, Mongoose and reflect-metadata to their latest version as well but it still does not work.

I couldn't install Typegoose 6.0.0 because this version does not appear in the list of versions.
Am I using the right command? `yarn add @hasezoey/typegoose@next`

**Comment by hasezoey** [comment]
@cesar3030 i dont use yarn, but `npm i -s @hasezoey/typegoose@next`
[look here for the versions](https://www.npmjs.com/package/@hasezoey/typegoose)

**Comment by cesar3030** [comment]
OK I see the `6.0.0-21` tag. Thanks! 
I'll give it a shot in the next days when I will have some time since there is some breaking changes and I need to migrate my codebase.

**Comment by hasezoey** [comment]
In 6.0.0 there are many changes including incompatibilitys, here is the change log https://github.com/szokodiakos/typegoose/issues/365#issuecomment-520108444
