### ISSUE TITLE
Pre after OrderedBulkOp not getting called

### ISSUE THREAD

**Issue by antivist** [szokodiakos/typegoose#236]
Hi,

given the following operation that basically creates a document if the submitted id does not exist or updates it respectively as a bulk operation, I'm struggling to find the correct `@pre<>` hook in my model. 

```typescript 
async updateOrCreateMany(items: InstanceType<T>[]): Promise<InstanceType<T>[]> {
        const bulk = this._model.collection.initializeOrderedBulkOp();
        for (const item of items) {
            bulk.find({ _id: this.toObjectId(item.id) }).upsert().updateOne(item);
        }
        await bulk.execute();
        return items;
    }
```

So far I've tried `updateMany` and `update` but both are not being called.
Any ideas what hook is being called when you do a bulkoperation?

Thanks in advance.

**Comment by hasezoey** [comment]
> `this._model.collection.initializeOrderedBulkOp();`

with this it seems like you are using mongodb native functions, so mongoose hooks, or even models dont hook to there, you must use mongoose models to use hooks

---

this can be closed as not an issue with typegoose

@Ben305

**Comment by hasezoey** [comment]
@Ben305 Bump to close
