### ISSUE TITLE
@prop syntax for custom SchemaType

### ISSUE THREAD

**Issue by gae123** [szokodiakos/typegoose#237]
Is there any way to specify that a property has type that comes from a [mongoose custom SchemaType](https://mongoosejs.com/docs/customschematypes.html)?

**Comment by hasezoey** [comment]
currently, there are no tests for it, so i assume it dosnt work, at least its not officially supported

**Comment by hasezoey** [comment]
@Ben305 this can be closed in favor of https://github.com/hasezoey/typegoose/issues/36
