### ISSUE TITLE
(5.5.0) Stalled queries

### ISSUE THREAD

**Issue by PiotrMitkowski** [szokodiakos/typegoose#241]
After updating to new version my app hangs on every possible query without any errors. For example, when running below code:

```
...
const userModel = new User().getModelForClass(User);
const users = await userModel.find({});
console.log('users', users);
...
```
the console.log with users never gets invoked. Also there is no errors in console. Testing analogical code using pure Mongoose passes successfully.

**Comment by marcomag89** [comment]
i had the same problem.
solved setting `existingConnection` and/or `existingMongoose` parameter in `getModelForClass` passing your mongoose connection https://github.com/szokodiakos/typegoose#methods

**Comment by hasezoey** [comment]
is this still a problem?

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "not an issue with typegoose" & "stale"
