### ISSUE TITLE
Define property as a DocumentArray

### ISSUE THREAD

**Issue by rosscoombes** [szokodiakos/typegoose#243]
I've been trying to get Embedded discriminators to work with Typegoose and Typescript but having trouble.

Ultimately it comes down to the following line in the documentation
(https://mongoosejs.com/docs/discriminators.html)

// `batchSchema.path('events')` gets the mongoose `DocumentArray`
var docArray = batchSchema.path('events');

In order for the rest of the example to work properly, the line above needs to return a mongoose DocumentArray which when done outside of Typegoose, it does.

My equivalent line with my Typegoose objects is
const docArray = BatchModel.schema.path('events');

However, depending on how 'events' is declared
@prop()
public events: Event[]; 

--> returns Mixed

@arrayProp({ itemsRef: Event})
public events: Event[];

--> returns SchemaArray

Most other combinations I can think of result in Type is not a constructor from prop.js.

Any ideas?  Please!

**Comment by hasezoey** [comment]
this can be closed in favor of https://github.com/hasezoey/typegoose/issues/25

@Ben305
