### ISSUE TITLE
Add bson to depencies

### ISSUE THREAD

**Issue by orblazer** [szokodiakos/typegoose#244]
Hello,

I whant know if you can add bson to depencies fork work with PNPM ?

Thanks.

**Comment by shilangyu** [comment]
Im a pnpm user and typescript fails to compile because of `cant find module 'bson'`. How is this related to pnpm and is there a workaround?

**Comment by shilangyu** [comment]
Installing `@types/bson` seemed to fix it, cant see how it is related to pnpm tho

**Comment by hasezoey** [comment]
first: i dont know what pnpm is or how it is diffrent from npm

in my latest pr #318 i removed all dependencies for bson, because it is nowhere used in the project, so i would ask: is this still a problem?

**Comment by shilangyu** [comment]
Pnpm is just an alternative to npm that speeds things up

However I don't believe the error is related to pnpm. Will try to reproduce this error tomorrow (about 10h). 

On a unrelated note: Thank you for all your work @hasezoey on this project

**Comment by shilangyu** [comment]
## To reproduce:

```sh
> mkdir test && cd test
> npm init -y
> npm i @types/node @types/mongoose mongoose typegoose typscript
> npx tsc --init
```
Enable experimental decorators in tsconfig.
Create `index.ts`, populate with:

```ts
import { prop, Typegoose } from 'typegoose'

class Nest {
	@prop({ required: true })
	prop1!: string

	@prop({ required: true })
	prop2!: string
}

class User extends Typegoose {
	@prop()
	name?: string

	@prop()
	nested?: Nest
}
```

## Errors:

When running `npx tsc` the error is thrown: 

```
node_modules/.registry.npmjs.org/typegoose/5.7.2_mongoose@5.6.4/node_modules/typegoose/lib/prop.d.ts:2:26 - error TS2307: Cannot find module 'bson'.

import { ObjectID } from 'bson';
```

So looks lime the generated prop.d.ts imports `bson`? I couldnt find any source for the error, `bson` isnt imported in typegoose

**Comment by hasezoey** [comment]
@shilangyu sorry, but i asked if it still happenes with the latest master, not the latest npm (because npm package is a bit behind)

and because this module dosnt have an autobuild (install script to compile when installed over git), could you try it so:

```sh
mkdir test && cd test
npm init -y
npm i @types/node @types/mongoose mongoose typscript reflect-metadata
mkdir src && cd src
git clone https://github.com/szokodiakos/typegoose.git typegoose
cd ..
npx tsc --init
```
and call it as a as a normal code module with relative paths? (now it is a git-submodule) thanks

**Comment by shilangyu** [comment]
Tsc now compiles correctly however i had to remove `test/src/typegoose/test`, copy over typegoose's `tsconfig`. Running `node index.js`:
![image](https://user-images.githubusercontent.com/29288116/61117708-67ccc200-a497-11e9-8940-d60cb3b856ea.png)

**Comment by hasezoey** [comment]
why did you have to remove typegoose/test?
could you give the nodejs version (& TS version) and your model? thanks

**Comment by shilangyu** [comment]
Because ts was trying to compile it (yes, i could achieve the same by just adding an exclude in `tsconfig`). I am running the latest version of ts and node (v3.5.3 and v12.6.0 respectively). My model is the example i showed [here](https://github.com/szokodiakos/typegoose/issues/244#issuecomment-510792180)

**Comment by hasezoey** [comment]
@shilangyu could you add to that model, where you make the class to the Model (even if its just standart)?

**Comment by shilangyu** [comment]
I am incredibly sorry, i was running the wrong file with node, everything works fine now 🤦‍♀️

**Comment by hasezoey** [comment]
i think this can be closed now, because typegoose dosnt use bson anymore, only mongoose.types.objectid

@Ben305
