### ISSUE TITLE
loadash vulnerability in 4.17.10

### ISSUE THREAD

**Issue by antivist** [szokodiakos/typegoose#245]
Please upgrade to lodash 4.7.11 or later due to prototype pollution.

[npm advisory](https://www.npmjs.com/advisories/782)

Thank you in advance.

**Comment by gottsohn** [comment]
This is pretty urgent, critical build are failing because of this audit issue.
Thanks.

**Comment by luxcium** [comment]
I sent a new pull to fix this issue : #250
