### ISSUE TITLE
typegoose@5.6.0 requires a peer of mongoose@5.4.15  and I have mongoose@5.4.17

### ISSUE THREAD

**Issue by Luxcium** [szokodiakos/typegoose#256]
npm WARN typegoose@5.6.0 requires a peer of mongoose@5.4.15 but none is installed. You must install peer dependen
cies yourself.

+ mongoose@5.4.17
updated 1 package and audited 27987 packages in 15.862s
found 0 vulnerabilities

**Comment by pointtoken** [comment]
Also seeing this...

**Comment by duro** [comment]
Yep, I think there might have been a packaging error with the last release. I see that the tagged release in GitHub shows the proper `^5.4.15`, but what get's pulled from NPM in version `5.6.0` or typegoose reads a fixed version of `5.4.16`

**Comment by HansITChange** [comment]
Warning is still there: mongoose package is now at 5.5.9

**Comment by Ben305** [comment]
Fixed in 5.7.1
