### ISSUE TITLE
how to use mongoose auto-populate

### ISSUE THREAD

**Issue by techaks** [szokodiakos/typegoose#257]
https://www.npmjs.com/package/mongoose-autopopulate

**Comment by techaks** [comment]
@rjmunro @hpoul @bitjson @richarddd  help me

**Comment by hpoul** [comment]
are you kidding me? 1. why are you posting here? 2. why me? 3. either make at least *some effort* to have *any* grasp of what you are doing.. like.. you know.. read documentation, search the internet, try to find the right project, formulate a sensible question, or at least hire a tutor. and if you still feel like you need help from random people on the internet, try https://stackoverflow.com/help/how-to-ask

**Comment by techaks** [comment]
How to plugin schema

**Comment by techaks** [comment]
I need to know how to plugin

**Comment by Ben305** [comment]
This is not a support forum, closing.
