### ISSUE TITLE
tslint warnings

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#259]
I'm getting these TSLint warnings everywhere I await a model:
```
Invalid 'await' of a non-Promise value. (await-promise)tslint(1)
```

In places like this:
```ts
const org = await OrganizationModel.findById(this.organization)
```

And then another TSLint error after that:
```
This type is not allowed in the operand for the '!' operator because it is always truthy. It may be null/undefined, but neither 'allow-null-union' nor 'allow-undefined-union' is set. Only booleans are allowed. (strict-boolean-expressions)tslint(1)
```

On this line:
```ts
if (!org.name) { ... }
```

tslint.json:
```json
{
  "extends": "tslint-config-standard",
  "rules": {
    "space-before-function-paren": false,
    "interface-name": [
      true,
      "always-prefix"
    ],
    "array-type": [
      true,
      "array"
    ],
    "no-angle-bracket-type-assertion": true,
    "no-floating-promises": true,
    "promise-function-async": true,
    "no-unused-variable": false,
    "await-promise": [
      true
    ],
    "strict-boolean-expressions": true
  }
}
```

Does anyone know how to properly setup TSLint for Typegoose? It did actually used to work a month ago but something changed and I'm not sure what.

```
    "tslint": "^5.11.0",
    "tslint-config-standard": "^8.0.1",
    "typegoose": "^5.4.1",
    "typescript": "^3.0.3",
```

**Comment by hasezoey** [comment]
is this still a problem with typegoose@5.8.0?

**Comment by Christilut** [comment]
Yes this still happens.

Just upgraded all relevant dependencies to this:
```
    "tslint": "5.18.0",
    "tslint-config-standard": "^8.0.1",
    "typegoose": "5.8.1",
    "typescript": "3.5.3",
```

**Comment by hasezoey** [comment]
can it be that you have some tslint rule preventing `await` in non-promise returning functions?
because when you use something like `OrganizationModel.findById(this.organization)` returns a query, wich wouldnt be a problem normally, but you should (at least when using typescript & for completeness) execute it so: `await OrganizationModel.findById(this.organization).exec()` important: the `.exec()` executes the query and returns 100% a promise
-> does this solve it?

**Comment by hasezoey** [comment]
and
> This type is not allowed in the operand for the '!' operator because it is always truthy. It may be null/undefined, but neither 'allow-null-union' nor 'allow-undefined-union' is set. Only booleans are allowed. (strict-boolean-expressions)tslint(1)

is not a typegoose issue, but i will answer it anyway:
`!org.name` isnt valid with this strict tslint, because `name` is probably a string, and the `!` in this strict tslint is only allowed if it is an boolean ("true" or "false")

**Comment by Christilut** [comment]
Using `.exec()` does solve it and the linting behaves as it should now.

If I'm understanding it correctly, using `findById()` also executes immediately but returns a Query which is a Thenable, which is similar to a Promise but not really a Promise... And this is a mongoose thing, not a Typegoose thing. I do find it kind of strange that `findById()` returns a Query and immediately executes, because it seems that's what it should only after adding the `exec()`.

Anyway thanks for the help!

**Comment by hasezoey** [comment]
> If I'm understanding it correctly, using findById() also executes immediately but returns a Query which is a Thenable, which is similar to a Promise but not really a Promise... And this is a mongoose thing, not a Typegoose thing.

yes you are right

> I do find it kind of strange that findById() returns a Query and immediately executes, because it seems that's what it should only after adding the exec().

because mongoose just uses the the `.find()` with the only options being `_id`, so you can still add something like "where" or "select"(to exclude the output)

**Comment by Christilut** [comment]
Ah I see, good to know, thanks :)
