### ISSUE TITLE
Possible to use references in instance methods

### ISSUE THREAD

**Issue by aequasi** [szokodiakos/typegoose#26]
Something like:

```javascript
class GuildMember extends Typegoose {
    @prop({ref: User})
    public user: Ref<User>;

    public get id() {
        return this.user.identifier; // <------ identifier doesn't exist on `Ref`
    }
}

**Comment by szokodiakos** [comment]
Hello! `Ref<T>` is basically `T | string`. There are two issues with this code:
- In this situation `User` is just a reference in `GuildMember` schema, so it must be populated before we can access the properties of a referred schema.
- If you populate the `User` you have to tell TypeScript explicitly that `Ref<T>` now is `T` by 
```
public get id() {
    return (this.user as User).identifier;
}
```

Hope it helps!

**Comment by aequasi** [comment]
Thanks!
