### ISSUE TITLE
Linter issues with Ref<T> and .populate()

### ISSUE THREAD

**Issue by jrejaud** [szokodiakos/typegoose#261]
When I run the following code:

```
const foundPayer = await PayerModel.findOne({_id: payerID}).populate("sponsor")
console.log(foundPayer.sponsor.name)
```

My linter provides me the following message:
```
`TS2339: Property 'name' does not exist on type 'Ref<Sponsor>'.   Property 'name' does not exist on type 'ObjectId'.`
```

Is there a way I can have the linter perceive the type as T (from Ref<T>) rather than ObjectId?

Classes:
```
 class Payer extends Typegoose {
  @prop({ref: Sponsor, required: true})
  sponsor: Ref<Sponsor>
}

class Sponsor extends Typegoose {
  @prop()
  name: string;
}
```

**Comment by elincognito** [comment]
Same here

**Comment by SpencerKaiser** [comment]
I have the same problem as well... have y'all found a workaround??

**Comment by AlecDusheck** [comment]
In my situtation, using a type guard fixed this. For example:
`
const foundPayer = await PayerModel.findOne({_id: payerID}).populate("sponsor")
console.log(foundPayer.sponsor.name)
`
would turn into:
`
const foundPayer = await PayerModel.findOne({_id: payerID}).populate("sponsor")
if(foundPlayer.sponsor instanceof Sponsor){
    console.log(foundPayer.sponsor.name) // No errors!
}
`

**Comment by Goodluckhf** [comment]
I have the same problem, but according to the docs of mongoose
![image](https://user-images.githubusercontent.com/9287861/58015860-f7439d80-7b04-11e9-9f57-eae87e1c109c.png)

_ref_ field also can be null.

**Comment by PabloSzx** [comment]
> In my situtation, using a type guard fixed this. For example:
> 
> ```
> const foundPayer = await PayerModel.findOne({_id: payerID}).populate("sponsor")
> console.log(foundPayer.sponsor.name)
> ```
> 
> would turn into:
> 
> ```
> const foundPayer = await PayerModel.findOne({_id: payerID}).populate("sponsor")
> if(foundPlayer.sponsor instanceof Sponsor){
>     console.log(foundPayer.sponsor.name) // No errors!
> }
> ```

turns out that in runtime this doesn't work properly,

i was testing this type guard on runtime and it doesn't work, it seems to not be a real instance of the the Typegoose class, but instead an instance of `Model` from `mongoose`, but you can't just do 
```typescript
instanceof Model
``` 
because it really is the Typegoose extended class, so in order to work in Typescript compilation time AND runtime, you have to make a [custom type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) like so

```typescript
import { Model } from "mongoose";
import { Ref } from "typegoose";

export function isModel<T>(arg: Ref<T>): arg is T {
  return arg instanceof Model;
}
```

this could be really useful if it were available on this library itself

**Comment by PabloSzx** [comment]
> I have the same problem, but according to the docs of mongoose
> ![image](https://user-images.githubusercontent.com/9287861/58015860-f7439d80-7b04-11e9-9f57-eae87e1c109c.png)
> 
> _ref_ field also can be null. So there is one more issue in types

is not that easy to fix this, because (*correct me if i'm wrong*) if we change this
```typescript
export type Ref<T> = T | mongoose.Schema.Types.ObjectId;
```
to
```typescript
export type Ref<T> = (T | null) | mongoose.Schema.Types.ObjectId;
```

we would have to do unnecessary validations for the array of refs , since for arrays if it's not found, it's not null
