### ISSUE TITLE
The @index decorator is producing a deprecation warning

### ISSUE THREAD

**Issue by justinmchase** [szokodiakos/typegoose#265]
* Mongo v3.4.19 (or later)
* typegoose@5.6.0
* mongoose@5.4.15

```
(node:189) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
```

**Comment by kettuvitonen** [comment]
Setting `useCreateIndex` in mongoose connection options should remove the warning.

`mongoose.connect(Config.MONGODB_URI, { useNewUrlParser: true, useCreateIndex: true })`

**Comment by hasezoey** [comment]
this can be closed, because its not an typegoose issue (its an mongoose `.connect` issue, where `useCreateIndex` option is not set to true, like stated above)

@Ben305

**Comment by justinmchase** [comment]
But shouldn't you just call the right method instead? The warning is there to tell you to call a different method and setting that flag is to just ignore the warning, no?

**Comment by justinmchase** [comment]
Ok I see, I didn't get that mongoose was abstracting over the two and the flag tells mongoose which api to use in the driver. I thought it was telling us to update the calling code but I see that typegoose is just calling `schema.index` which then calls into one or the other apis based on the flags.

Sorry for the noise, I get it now.
