### ISSUE TITLE
Outputting a read-only schema?

### ISSUE THREAD

**Issue by RyannGalea** [szokodiakos/typegoose#266]
Existing feature?

I noticed type-graphql has a nice feature 'emitSchemaFile' which outputs the Graphql schema that is being generated.

Does Typegoose have a similar feature for outputting the Mongoose schema? Would be a nice feature to see what exactly is being generated whilst developing.

Thanks Ryann,

**Comment by hasezoey** [comment]
when you want to get the schema from a model:
`Model.schema` (mongoose native)

when you want to get the schema from a document:
`doc.schema` (mongoose native)

when you want it before the model is build
`new Class().buildSchema()` since #341

this can be considered solved
@Ben305

**Comment by hasezoey** [comment]
@Ben305 Bump to close
