### ISSUE TITLE
Unpack InstanceType<T> for testing

### ISSUE THREAD

**Issue by MikeShiner** [szokodiakos/typegoose#268]
Does anyone have good testing strategy for InstanceType<T> ?
I need to remove all the properties from the logic &  with Document - so I'm left with my original interface properties to test with.

Currently doing something like..
`expect(environmentArr[0]).to.be.eql(Eviron1);`
is comparing all the mongo properties like:
`      -          "$init": true`
              `   "_doc": {`
`      +            "__v": 0`

I basically need to unpack the original class (I'm okay with keeping the Typegoose extention methods) without the InstanceType properties. Mongoose's .toJson & .toString doesn't remove these.

I'm currently having to write instance methods which return an object of all the properties of the original class:
```
@instanceMethod
	reduceToInterface() {
		return {
			project: this.project,
			module: this.module,
			operator: this.operator,
			browser: this.browser
		};
	}
```

But this is laborious and tricky to manage with subdocuments.
Thanks, Mike

**Comment by MikeShiner** [comment]
I've changed my InstanceMethod to be easier to work with..

`@instanceMethod
	reduceToInterface() {
		return JSON.parse(JSON.stringify(this));
	}`

**Comment by hasezoey** [comment]
@Ben305 this could be closed as "stale" / "fixed"

if you still have this problem, and v5.9.x / v6.0.0's typeguards dont fix this, please feel free to open a new issue on the new repo
