### ISSUE TITLE
Save does not exist on type

### ISSUE THREAD

**Issue by AshotN** [szokodiakos/typegoose#269]
```
UserModel.findOne({apiKey: data.APIKey}, (err, user: UserType) => {
	user.save((err, doc) => {
         ...
	});
});
```

Gives me the TypeScript error
```Property 'save' does not exist on type 'UserModel'.```

What am I doing wrong...

**Comment by ealtuna** [comment]
There is no enough information to say for sure. Can you provide your UserModel definition?

**Comment by kettuvitonen** [comment]
User should be of type `InstanceType<UserType>` then it should work.

```
import { InstanceType } from "typegoose";

UserModel.findOne({apiKey: data.APIKey}, (err, user: InstanceType<UserType>) => {
	user.save((err, doc) => {
         ...
	});
});
```

**Comment by hasezoey** [comment]
https://github.com/szokodiakos/typegoose/issues/269#issuecomment-485248496 should have fixed this, this can be considered solved

@Ben305
