### ISSUE TITLE
Add support for bson/Long

### ISSUE THREAD

**Issue by aequasi** [szokodiakos/typegoose#27]
https://mongodb.github.io/node-mongodb-native/api-bson-generated/long.html

**Comment by szokodiakos** [comment]
Hello, is this supported in Mongoose? Typegoose builds on Mongoose not on Mongo directly. If yes can you link some documentation about this feature in Mongoose?

**Comment by aequasi** [comment]
Yeah, theres another package for it: https://www.npmjs.com/package/mongoose-long

**Comment by hasezoey** [comment]
@Ben305 this can be closed in favor of https://github.com/hasezoey/typegoose/issues/36

**Comment by hasezoey** [comment]
@Ben305 Bump to close
