### ISSUE TITLE
How to use Map

### ISSUE THREAD

**Issue by patchimou** [szokodiakos/typegoose#274]
Is it possible to use the ES6 type Map ?

**Comment by krnik** [comment]
You want to use Map inside the Mongo? Check out this list of [BSON Types](https://docs.mongodb.com/manual/reference/bson-types/).

If you want to represent document property using a Map you can use instance methods.
There is `init` [middleware](https://mongoosejs.com/docs/middleware.html) which probably could be used during mapping the data from the DB to the model instance (It's just a guess, haven't really used that).

**Comment by fiws** [comment]
mongoose supports the `Map` type: https://mongoosejs.com/docs/schematypes.html#maps

But it does not work out of the box with typegoose, does it?

**Comment by hasezoey** [comment]
@fiws no it dosnt work out-of-the-box because: typegoose dosnt supply the `of` property options
-> and it cannot fully implement Map's outputs from given inputs, only an indexer
but you could try it with `// @ts-ignore`, but i dont know if it will work

**Comment by fiws** [comment]
I'm wondering what my code actually does. I have a schema with a field like this:

```
  @prop()
  data: Map<string, string>
```

And it's not actually a JS map, but an object. Is this to be expected?

**Comment by hasezoey** [comment]
@fiws, yes it is expected, to be "unexpected" because the `Map` Property isnt supported, and by the way, you didnt add the `of:` parameter options, what mongoose would need

**Comment by hasezoey** [comment]
with #284 (old) and #342 (new) Map is added as `@mapProp`, when merged, available to everyone

**Comment by hasezoey** [comment]
@fiws, when you still work with typegoose, could you try #342, and report if it works how it should?
