### ISSUE TITLE
Force collection name

### ISSUE THREAD

**Issue by ShabanGomaa** [szokodiakos/typegoose#275]
When I try to force collection name using it doesn't work, here is my sample code:

async create(item: BuyModel) {
    const Model: ModelType<BuyModel> = new BuyModel().getModelForClass(
      BuyModel,
      {
        **schemaOptions: { collection: "buy" }**
      }
    );
    const modelItem = new Model(item);
    await modelItem.save();
  }

I set collection name to "buy" but it ignores this name and saves in collection name 'buymodels'

**Comment by hasezoey** [comment]
Cannot Reproduce, i changed collection to "test", "buy", "helloworld" and all worked (all collections got created and saved)

Full sample Code used:
```ts
import * as mongoose from "mongoose";
import { index, prop, Typegoose } from "typegoose";

class Test extends Typegoose {
    public _id!: mongoose.Schema.Types.ObjectId;

    @prop({ required: true })
    public test!: number;
}

const TestModel = new Test().getModelForClass(Test, {
    schemaOptions: {collection: "buy"}
});

(async () => {
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify275",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const _test = new TestModel({
        test: 100
    });

    console.log("test 1 saved!", await _test.save());
})();
```

PS: you can set the collection after you made an instance of the model with
`_test.collection.collectionName = "helloCollection"`

**Comment by hasezoey** [comment]
i would consider this closed | solved, because of inactivity 

@Ben305
