### ISSUE TITLE
Support inheritance from abstractModel (old: staticMethod not giving model as this)

### ISSUE THREAD

**Issue by aequasi** [szokodiakos/typegoose#28]
Using the following code:

```typescript
export default abstract class AbstractModel extends Typegoose {
    @staticMethod
    public static findByIdentifier(this: ModelType<AbstractModel>, identifier: Long) {
        return new Promise((resolve, reject) => {
            console.log(this);
            this.findOne({identifier}).then(resolve).catch(reject);
        });
    }

    @prop({required: true, index: true, unique: true})
    public identifier: string;
}
```

`this` is always an instance of the model, instead of the model type, so i can't call `findOne`.

Feel like im missing something...

**Comment by szokodiakos** [comment]
Hello I think you haven't included some other Models' code. Can you please extend your example? Right now its hard to tell what is wrong.

**Comment by aequasi** [comment]
```
import AbstractModel from "./AbstractModel"

export default class User extends AbstractModel {
}

let user: User = await UserModel.findOneByIdentifier('some identifier here');
```

**Comment by aequasi** [comment]
I might be missing something, but it actually seems like inheritance is not supported

**Comment by vinczedani** [comment]
Hi @aequasi 
Sorry for the late response. The current version of typegoose is not written with inheritance support in mind. I mark this issue with enhancement instead of question.
Thanks, Daniel

**Comment by buzzyboy** [comment]
Has there been any update to creating this enhancement?

**Comment by hasezoey** [comment]
this should work in v6.0.0

@Ben305 this can be closed
