### ISSUE TITLE
Create a model with ref is not storing the ref documents

### ISSUE THREAD

**Issue by felipebelluco** [szokodiakos/typegoose#280]
Calling `model.create` on a model with refs creates the array of ObjectID corresponding to the refs but does't store any document in the ref collection. Here's my code:
```
export class ProcessStep extends Typegoose {

    @prop({ required: true, trim: true })
    name: string;

    @arrayProp({ required: true, itemsRef: Action})
    actions: Ref<Action>[];

    static get model(): ModelType<ProcessStep> {
        return new FluxoProcesso().getModelForClass(ProcessStep , { schemaOptions: schemaOptions });
    }

    static get modelName(): string {
        return this.model.modelName;
    }
}
```

```
export class Action extends Typegoose {

    @prop({ required: true, trim: true })
    name: string;

    @prop({ ref: { name: 'ProcessStep' } })
    ProcessStep: Ref<ProcessStep>;

    static get model(): ModelType<Action> {
        return new Action().getModelForClass(Action, { schemaOptions });
    }

    static get modelName(): string {
        return this.model.modelName;
    }
}
```

When I call model.create method on the following object:

```
{
  "name": "Process Step 1",
  "actions": [
    {
      "name": "Action 1"
    }
  ]
}
```

It stores the Process Step document as following:

```
{
  "_id": "5cd30986563e0d981c53c355",
  "actions": [
    "5cd30986563e0d981c53c356"
  ],
  "name": "Process Step 1",
  "__v": 0
}
```

But it doesn't store any document in the Action collection. If I'm misunderstanding the ref concept, is there any way to accomplish cascade insertion?

**Comment by hasezoey** [comment]
https://github.com/Automattic/mongoose/issues/8115 ?

PS: there is not actually an example of how you call `.create`

**Comment by hasezoey** [comment]
its a bit old now, but does it still happen with `6.0.x` (/ `6.1.0-6`)?

-> when possible please text it with `6.1.0-6` (or higher), because in that version it is reworked how array options are mapped

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed as "stale"

-> if someone ever comes across this again, please open a new issue at the new repo
