### ISSUE TITLE
@index index not created for read-only collection

### ISSUE THREAD

**Issue by gentleShark** [szokodiakos/typegoose#287]
I created a Typegoose model for an existing collection that I only intend to use for read purposes. I applied some @index decorators hoping these would be applied to the collection but they were not so I just added the indexes manually via the mongo CLI. At what point are mongo indexes created?  On the first write? I successfully used the @index decorator in other parts of the my project so I have had some success with the decorator.

**Comment by hasezoey** [comment]
is #277 related?

just to be right:
>  I successfully used the @index decorator in other parts of the my project so I have had some success with the decorator.
does this mean that the indexes are created in the collection you are trying to read/write?
& do you have the mongoose option `autoIndex: true` set?

**Comment by gentleShark** [comment]
I set those options but it didn't result in an index being created. 
However, the index was created on the collection after I used the Typegoose model to do a find() query. 
It's not necessarily a bad thing for Typegoose to ignore models before they are called in the code though I supposed I had grown accustomed to other ORMs such as Typeorm and Prisma where the model changes modify the underlying DB structure prior to the model being called in the code. Anyway, thanks for the quick reply!

**Comment by hasezoey** [comment]
As far as i know, mongoose only adds a collection +/& indexes when an read/write operation is called, this would mean, it is not necessarily Typegoose's fault

**Comment by gentleShark** [comment]
on second glance, it looks like Typegoose is creating the indexes on the fly as I make changes to the model prior to any read/write. For example, I put an index on a field "type" and then changed that to "properties.zip" and an index ended up getting created called "properties.ziptype" along with "properties.zip" because the index was generated while I was typing/modifying the "type" index. That seems to be an issue.
`> db.zips.getIndexes();
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "type-graphql.zips"
	},
	{
		"v" : 2,
		"key" : {
			"type" : 1
		},
		"name" : "type_1",
		"ns" : "type-graphql.zips",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"properties.ziptype" : 1
		},
		"name" : "properties.ziptype_1",
		"ns" : "type-graphql.zips",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"properties.zip" : 1
		},
		"name" : "properties.zip_1",
		"ns" : "type-graphql.zips",
		"background" : true
	}
`

 Also, it would be great to be able to (optionally) reconcile Typegoose model indexes with the underlying collection so that indexes generated while typing for example, get removed if not defined on the Typegoose model (perhaps with exception to _id ?).

**Comment by gentleShark** [comment]
I tested to see if a subsequent read of the model might remove the index "properties.ziptype_1" that was generated while typing, changing the "type" index to "properties.zip," but it didn't

**Comment by hasezoey** [comment]
sorry, without seeing your model definition, i cant say from where the "type" comes, could you please provide it?

**Comment by gentleShark** [comment]
it's the type field on the Zip class:

`class Geometry {
	@Property({ default: 'Point' })
	type: string;

	@ArrayProperty({ items: Array })
	coordinates: [number];
}

class Properties {
	@Property()
    city: string;
    
    @Property()
    zip: string;
    
	state: string;
}

@index({"properties.zip": 1})
export class Zip extends Typegoose {
	@Property({ default: 'Feature'})
	type: string;

    @Property({_id: false})
    geometry: Geometry;

    @Property({_id: false})
    properties: Properties;
}

export const ZipModel = new Zip().getModelForClass(Zip);
`

**Comment by hasezoey** [comment]
you know only `@prop` & `@arrayProp` are valid? -> at least i dont see anything in the documentation to state otherwise

PS: use tripple \` with the language behind

**Comment by gentleShark** [comment]
Thanks for the tips. My imports are just renaming the decorators:
```import { prop as Property, arrayProp as ArrayProperty, Typegoose, index} from 'typegoose';

**Comment by hasezoey** [comment]
for me, typegoose did only create index "_id"("_id_") and "properties.zip"("properties.zip_1")

Code i used:
```ts
import * as mongoose from "mongoose";
import "source-map-support/register";
import { index, prop, Typegoose } from "typegoose";

class Properties {
    @prop()
    public city?: string;

    @prop()
    public zip?: string;

    @prop()
    public state?: string;
}

@index({ "properties.zip": 1 })
export class Zip extends Typegoose {
    @prop({ default: "Feature" })
    public type?: string;

    @prop()
    public properties?: Properties;
}

const ZipModel = new Zip().getModelForClass(Zip);

(async () => {
    await mongoose.connect(`mongodb://sylvi:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verifyTest",
        user: "hasezoey",
        pass: "FhU2MdPxWzWvESHN",
        authSource: "admin",
        autoIndex: true
    });

    const instance = await new ZipModel({} as Zip);
    await instance.save();
})();
```

**Comment by gentleShark** [comment]
thanks for testing. however, there definitely seems to be a bug related to modifying an @index on a model. Originally, I had @index({ "type": 1 }) on the Zip class and while I was modifying @index({ "type": 1 }) to instead be @index({ "properties.zip": 1 }), there was a split second while I was typing where the text was @index({ "properties.ziptype": 1 }) before I deleted type. An index named "properties.ziptype_1" was created during that split second while I typing. No reads or writes using the model occurred while I was making the edits. 

The feature request would be a way to (optionally) reconcile indexes defined on a model with the underlying collection and delete indexes not explicitly defined on the model (except for perhaps _id). Should I create a separate feature request for that?

**Comment by hasezoey** [comment]
can it be that you have somekind of auto run on save & had saved at this moment? otherwise i dont know how this happened -> so i think this is not an bug/error with typegoose

**Comment by hasezoey** [comment]
and isnt the original Question already answered?
anyway i do it again:

> I created a Typegoose model for an existing collection that I only intend to use for read purposes. I applied some @index decorators hoping these would be applied to the collection but they were not so I just added the indexes manually via the mongo CLI. 

now we know that the indexes got created & modified
*Note for anyone just coming by*: try adding mongoose connection option `useCreateIndex: true` & `autoIndex: true` if not already done

> At what point are mongo indexes created? On the first write?

on the first read/write from mongoose on the collection

**Comment by hasezoey** [comment]
BTW i just read about it, this is probably what you search for:
[`model.syncIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.syncIndexes)

**Comment by gentleShark** [comment]
model.syncIndexes() looks like it should do the trick for syncing and syncing would also fix the bug that I noticed where an index was generated while I was typing. I'll add the feature request. thanks for the help!!!
