### ISSUE TITLE
[enhancement] decorator to auto execute "model.syncIndexes" on model/class

### ISSUE THREAD

**Issue by gentleShark** [szokodiakos/typegoose#290]
model.syncIndexes() looks like it should do the trick for syncing models with underlying collections and syncing would also fix the bug of indexes getting created while a user is typing the name of an index (see issue https://github.com/szokodiakos/typegoose/issues/287).

**Comment by hasezoey** [comment]
@Ben305  thanks to [e87bb9d79a9382c13f3cef9f6749c953207ccd55](https://github.com/typegoose/typegoose/commit/e87bb9d79a9382c13f3cef9f6749c953207ccd55) this can be closed

**Comment by akash-rajput** [comment]
There's missing documentation on this even in the new docs. Please consider adding. @hasezoey

**Comment by hasezoey** [comment]
@akash-rajput i dont know what you mean https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#runsyncindexes
-> if the issue persist, please open a new issue at the new repository

**Comment by akash-rajput** [comment]
Ohh my bad. Came across this from a issue. Couldn't locate model options.
Thanks for the link :)
