### ISSUE TITLE
[Dependencie Bug] typegoose@5.6.0 requires a peer of mongoose@5.4.15 & travis uses 5.0.0

### ISSUE THREAD

**Issue by hasezoey** [szokodiakos/typegoose#291]
Related are #256 #285 
- typegoose wants a peer dependency of `mongoose@5.4.15`
- in travis tests `mongoose@5.0.0` (in use oldest) is installed

<br/>
<br/>

Fixes that could be applied:
> - in travis tests `mongoose@5.0.0` (in use oldest) is installed

- [ ] change peer dependency to `5.0.0` or in travis change it to `5.4.15`

<br/>
<br/>

> - typegoose wants a peer dependency of `mongoose@5.4.15`

- [ ] republish the package with the package.json that is in this repo (in the repo it is `^5.4.15`, in the npm package it is `5.4.15` (the `^` is missing))

**Comment by Ben305** [comment]
Fixed in 5.7.1
