### ISSUE TITLE
Error using `default` for `@arrayProp` - figured it out but questionable method

### ISSUE THREAD

**Issue by Drageaux** [szokodiakos/typegoose#296]
I'm working on a chess game and I wanted the `default` array of Squares to have a preset structure. However, I kept getting this when using @arrayProp({default: DEFAULT_LIST })

```
Invalid schema configuration: `exampleVal` is not a valid type at path `exampleProp`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
```

❌my initial code:
```js
export class Board extends Typegoose {
  @arrayProp({ items: Square, default: DEFAULT_LIST }) // does not work right
  squares: Square[];
}

const DEFAULT_LIST = [*a specific array*]
```

What this did was adding a `default` property to the list of `Square` class properties (I checked using the VSCode debugger). The README, instead, misled me to believe that the behavior would be setting squares = DEFAULT_BOARD upon creation.
___
![image](https://user-images.githubusercontent.com/8085776/58738224-bd528100-83b9-11e9-9c7e-336ae30925cb.png)
___

✅So I thought of chaining the @prop decocator after @arrayProp and it worked
```js
export class Board extends Typegoose {
  @arrayProp({ items: Square }) // this describes the items within the array and their props
  @prop({ default: DEFAULT_BOARD }) // this describes the array itself
  squares: Square[];
}
```

Does this still align with the expected design? I mean it works but nowhere in the README mentioned that you could/should do this.

**Comment by hasezoey** [comment]
> ```ts
> export class Board extends Typegoose {
>  @arrayProp({ items: Square, default: DEFAULT_LIST }) // does not work right
>  squares: Square[];
>}
>
>const DEFAULT_LIST = [*a specific array*]
>```

i would say this would error in something like "'DEFAULT_LIST' cant be used before initialization"

otherwise it *should* work

PS: using `@arrayProp` and `@prop` is a bad practice 


When you want to use it, without the error "True is not valid at path required", you must use the #194 fix currently
```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "./typegoose/src/typegoose";

// tslint:disable:variable-name typedef

class Dummys extends Typegoose {
    @prop({ required: true, default: "dummys name" })
    public name!: string;
}

const def = [new Dummys()];

class Dummy extends Typegoose {
    @prop({ required: true, default: "hello someprop" })
    public someprop!: string;

    @arrayProp({ required: true, items: Dummys, default: def })
    public dummys!: Dummys[];
}

const dummyModel = new Dummy().getModelForClass(Dummy);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://sylvi:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify131",
        user: "hasezoey",
        pass: "FhU2MdPxWzWvESHN",
        authSource: "admin",
        autoIndex: true
    });

    const d1 = await new dummyModel().save(); // all default
    const d2 = await new dummyModel({ someprop: "someprop 2", dummys: [new Dummys(), new Dummys()] } as Dummy).save();

    const newfound = await dummyModel.find().exec();
    console.log(newfound);

    await mongoose.disconnect();
})();
```

**Comment by hasezoey** [comment]
>```ts 
>export class Board extends Typegoose {
>  @arrayProp({ items: Square, default: DEFAULT_LIST }) // does not work right
>  squares: Square[];
>}
>
>const DEFAULT_LIST = [*a specific array*]
>```

here i would expect an error like "cannot use DEFAULT_LIST before initialization

otherwise, when you want to use something like below, you would need fix #194 (to not get "True is not valid type for required" error)
```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "./typegoose/src/typegoose";

class Dummys extends Typegoose {
    @prop({ required: true, default: "dummys name" })
    public name!: string;
}

const def = [new Dummys()];

class Dummy extends Typegoose {
    @prop({ required: true, default: "hello someprop" })
    public someprop!: string;

    @arrayProp({ required: true, items: Dummys, default: def })
    public dummys!: Dummys[];
}

const dummyModel = new Dummy().getModelForClass(Dummy);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify296",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const d1 = await new dummyModel().save(); // all default
    const d2 = await new dummyModel({ someprop: "someprop 2", dummys: [new Dummys(), new Dummys()] } as Dummy).save();

    const newfound = await dummyModel.find().exec();
    console.log(newfound);

    await mongoose.disconnect();
})();
```

**Comment by Drageaux** [comment]
@hasezoey My bad in my example code. `const` should come before to avoid using 'before initialization'. Maybe my JS is rusty but it's not const is not hoisted up top?

I already solved the problem by chaining with a `@prop()` right after 
>```js
>@arrayProp({ items: Square })
>@prop({ default: DEFAULT_BOARD })
>```

Still, your example would cause something similar to the `"True is not valid type for required"` error, if I did  

>```js 
>@arrayProp({ required: true, items: Squares, default: DEFAULT_LIST })
>```
it would give me "`A` is not a valid type at path `file`", `file` being property name and 'a' is supposed to be an enum value assigned to `file`


I have a good guess as to why: **I'm passing in raw JSON object (not model type)** for the items in the DEFAULT_LIST, like this
```js
class Piece extends Typegoose {
  @prop({ required: true, enum: Color })
  color: Color;

  @prop({ required: true, enum: PieceType })
  type: PieceType;

  @prop({ default: false })
  captured?: boolean;

  @prop()
  get name(): string {
    return `${this.color} ${this.type}`;
  }
}

enum File {
  'a' = 1,
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h'
}
class Square extends Typegoose {
  // (file and rank are just x and y in chess terms)
  @prop({ lowercase: true, enum: File, required: true })
  file: string;

  @prop({ required: true })
  rank: number;

  @prop()
  piece?: Piece;
}

export class Board extends Typegoose {
  @arrayProp({ items: Square, default: DEFAULT_BOARD })
  @prop({ default: DEFAULT_BOARD })
  squares: Square[];
}

const DEFAULT_LIST = initBoard();
// THIS is probably why it refuses to work
function initBoard(): Square[] {
{ return 
  [ 
    { file: 'a', rank: 1, piece: { color: 'white', type: 'rook' } },
    { file: 'a', rank: 2, piece: { color: 'white', type: 'pawn' } },
    ...
  ]
}
```
I'm not entirely sure if this is hacky and bad practice, but I'm trying to generate the single raw JSON list for the chess board by doing `initBoard()` once. Every time a new BoardModel is created, it just instantiates based on an already made structure called `DEFAULT_LIST`.

It's a shortcut. And the reason I'm not creating a model for each PieceModel and SquareModel is because 1) it would repeat the process and slow down and 2) it might reference to the same collection of models. 


What I'm asking is can you point out potential Typegoose problems from my code? I already solved it in an unconventional way, but I thought it should be important to note in the README that `@arrayProp()` has its quirks and requires some massaging to work.

**Comment by Drageaux** [comment]
I also tried making a default list with instantiated models eg
`const newSquare: InstanceType<Square> = new SquareModel({
        file: File[1],
        rank: 1
      });
`
However, if you look at my Square class there is a virtual prop called `name`. When I created this model and `return [newSquare]`. The BoardModel yells `a1` is not a valid type within the array `default`. So far, only chaining decorators work completely for me

**Comment by Drageaux** [comment]
I removed the virtual name for the sake of testing, and got this error still

Tracing this problem as far as I can with VSCode debugger. 
![image](https://user-images.githubusercontent.com/8085776/58827879-f62c6900-85f8-11e9-8bc8-65e875cc725e.png)
![image](https://user-images.githubusercontent.com/8085776/58827441-e2ccce00-85f7-11e9-98e7-8eb389dfb33a.png)
![image](https://user-images.githubusercontent.com/8085776/58827739-96ce5900-85f8-11e9-9e4c-d2e2bd1a4d66.png)

- file, rank, and piece are the Square class's properties
- passing `default` into @arrayProp() makes it think that default is another path with schemaType 'undefined'

I realized this could be a duplicate of https://github.com/szokodiakos/typegoose/issues/238. When I used `required: true` it did give me that `True` is not a valid type at path `required`. I don't think it's totally solved.

**Comment by hasezoey** [comment]
> ```ts
> const DEFAULT_LIST = initBoard();
> export class Board extends Typegoose {
>   @arrayProp({ items: Square, default: DEFAULT_BOARD })
>   squares: Square[];
> }
> 
> // THIS is probably why it refuses to work
> function initBoard(): Square[] {
> { return 
>   [ 
>     { file: 'a', rank: 1, piece: { color: 'white', type: 'rook' } },
>     { file: 'a', rank: 2, piece: { color: 'white', type: 'pawn' } },
>     ...
>   ]
> }
> ```

@Drageaux for using something like above, it would be good using hooks[validate/save] (like setting `.squares` if undefined / null / empty if you wish)  
<br/>
<br/>

> Still, your example would cause something similar to the "True is not valid type for required" error, if I did

and like i said, had you tried to use #194 ?

PS: more info / comment coming soon after some testing

**Comment by hasezoey** [comment]
heres the test result:
all is working fine ... after 2 ts-ignores
now i wonder is this the result you wanted?

here the result:
```json
[
  {
    "_id": "5cf5eed6915ecb237344cb49",
    "squares": [
      {
        "_id": "5cf5eed6915ecb237344cb4a",
        "file": "a",
        "rank": 1,
        "piece": {
          "captured": false,
          "_id": "5cf5eed6915ecb237344cb4b",
          "color": "white",
          "type": "idk"
        }
      },
      {
        "_id": "5cf5eed6915ecb237344cb4c",
        "file": "a",
        "rank": 2,
        "piece": {
          "captured": false,
          "_id": "5cf5eed6915ecb237344cb4d",
          "color": "white",
          "type": "idk"
        }
      }
    ],
    "__v": 0
  },
  {
    "_id": "5cf5efc9d4962f2453b744f4",
    "squares": [
      {
        "_id": "5cf5efc9d4962f2453b744f5",
        "file": "a",
        "rank": 1,
        "piece": {
          "captured": false,
          "_id": "5cf5efc9d4962f2453b744f6",
          "color": "white",
          "type": "idk"
        }
      },
      {
        "_id": "5cf5efc9d4962f2453b744f7",
        "file": "a",
        "rank": 2,
        "piece": {
          "captured": false,
          "_id": "5cf5efc9d4962f2453b744f8",
          "color": "white",
          "type": "idk"
        }
      }
    ],
    "__v": 0
  }
]
```

here is the code ( [using this repo, with some fixes, including #194](https://gitlab.com/hasezoey/typegoose) )
```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "./typegoose/src/typegoose";

enum Color {
    red = "red",
    blue = "blue",
    white = "white"
}
enum PieceType {
    idk = "idk"
}
class Piece extends Typegoose {
    @prop({ required: true, enum: Color })
    public color: Color;

    @prop({ required: true, enum: PieceType })
    public type: PieceType;

    @prop({ default: false })
    public captured?: boolean;

    @prop()
    public get name(): string {
        return `${this.color} ${this.type}`;
    }
}

enum File {
    "a" = 1,
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h"
}
class Square extends Typegoose {
    // (file and rank are just x and y in chess terms)
    @prop({ lowercase: true, enum: File, required: true })
    public file: string;

    @prop({ required: true })
    public rank: number;

    @prop()
    public piece?: Piece;
}

const DEFAULT_LIST = initBoard();
export class Board extends Typegoose {
    @arrayProp({ items: Square, default: DEFAULT_LIST })
    public squares: Square[];
}

function initBoard(): Square[] {
    {
        return [
            // @ts-ignore  just a quick fix
            { file: "a", rank: 1, piece: { color: Color.white, type: PieceType.idk } },
            // @ts-ignore  just a quick fix
            { file: "a", rank: 2, piece: { color: Color.white, type: PieceType.idk } },
        ];
    }
}

const BoardModel = new Board().getModelForClass(Board);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify296",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const d1 = await new BoardModel().save(); // all default

    const newfound = await BoardModel.find().exec();
    console.log(JSON.stringify(newfound, null, 2));

    await mongoose.disconnect();
})();
```

**Comment by Drageaux** [comment]
Sorry I guess I didn't understand it when you said to use #194 
> and like i said, had you tried to use #194 ?

Since I'm not an active contributor and just using this for my external project, should I be tinkering with the code as a node_module? 

EDIT: IT WORKS!

First thing I did was using enum the same way you did `piece: { color: Color.white, type: PieceType.idk }`. 

Second I just added `// @ts-ignore` to 
```js 
const newSquare: Square = {
        file: (x + 1) as File,
        rank: y + 1
      };
```
and it solved 
> `Type '{ file: File; rank: number; }' is missing the following properties from type 'Square': name, getModelForClass, setModelForClass, buildSchema.ts(2739)`

as well as 

> have you tried Exclude<Value, toexclude> / Partitial<Value>, its an easy way around, Partitial make all optional, but exclude only excludes the value given

**Comment by Drageaux** [comment]
So `// @ts-ignore` was all I needed for most of the problems I had. Maybe using enum consistently helped too. I was just doing raw JSON without type check and it probably didn't like that during `@arrayProp` check

**Comment by Drageaux** [comment]
I spoke too soon. When I ran the build script for TS it gives me the same error that you said #194  would fix. Still, I don't get what you mean by "using" #194 so I'd like you to clarify that first.

**Comment by hasezoey** [comment]
>  I don't get what you mean by "using" #194 so I'd like you to clarify that first.

i do it it (in the examples) clone the repo from #194 to the src folder (structure would be `exampleroot/src/typegoose/src/typegoose.ts`
and so i import it with (in src) `import {...} from "./typegoose/src/typegoose;`
(it means it will compile the typegoose with your source code, so it could be made to an git submodule)

otherwise try [my provided (gitlab) code](https://gitlab.com/hasezoey/typegoose), like, install it with `npm install git+https://gitlab.com/hasezoey/typegoose.git` or like said above with a git submodule (the npm install would make it an npm module)

PS: using `// @ts-ignore` is "bad" practice, only use it in "dummy" examples, or when there is no other way to fix it.
