### ISSUE TITLE
Is there a way to mock or stub typegoose models for unit tests?

### ISSUE THREAD

**Issue by seyaobey** [szokodiakos/typegoose#297]
Apologies if this is not the right place for this type of question. I have been looking for days across the internet to find a way to mock of stub my models for unit tests and avoid setting up an in-memory database. The closest solution I have found is this library `sinon-mongoose`.
But there is presently a bug preventing it to work correctly with the latest version of `sinon`.

So I would like to know if there is a way to mock my models (they are used as dependencies of my domain repository classes), setup expectations and/or stubbing methods.

What is the strategy I may use to approach this problem?

Thank you for your suggestion. And again, apologies for reporting this problem here.

**Comment by hasezoey** [comment]
typegoose currently uses `mongodb-memory-server-global` for the tests (it is an in-memory version)
- to inspect the schema you can use `buildSchema` or `model.schema` to get the schema
- to inspect a model, just make a model
- to inspect a document, create one
all these above can be done without a mongoose connection, all other like `save`, `find` need a mongoose connection

does this solve your question?

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" & "solved?"
