### ISSUE TITLE
Pre and Pos methods

### ISSUE THREAD

**Issue by leodsgn** [szokodiakos/typegoose#3]
First of all, The idea is awesome!

I just wanted to know about how to implement 'pre' and 'pos' save methods in typegoose way.

Thanks!

**Comment by szokodiakos** [comment]
Thank you for your interest in Typegoose! This is currently not available however this would be a great addition to the library.

If you have a working solution feel free to open a pull request, otherwise it may be implemented in the future.

**Comment by leodsgn** [comment]
Awesome! Thanks!
