### ISSUE TITLE
Clarification on casting string to ObjectId

### ISSUE THREAD

**Issue by RyannGalea** [szokodiakos/typegoose#308]
Hey Everyone,

Confused if this is the proper implementation...

I created a field called 'createdBusiness' which has a default value of ObjectId (imported from 'mongod') and it is stored in the DB as an ObjectId

When I try and do:

    const { business } = ctx.req.session.state;
    return ContactModel.find({createdBusiness: business})
 

It returns no values, but if I create an ObjectId and pass it in it works fine as below

    import { ObjectId } from 'mongodb';

    const { business } = ctx.req.session.state
    const createdBusiness = new ObjectId(business.toString())
    return ContactModel.find({createdBusiness})

Now from my previous experience I always found that mongoose would cast the string value into an ObjectId but it doesn't happen here. I just want to clarify this is expected behavior.

Thanks for looking.

**Comment by hasezoey** [comment]
could you provide your model?

**Comment by RyannGalea** [comment]
@ObjectType()
          export class Contact extends CreatedTypegoose {
            
            @Field()
            readonly _id: ObjectId

            @Field(type => ContactType)
            @Property({required: true, enum: Object.values(ContactType), index: true})
            contactType: ContactType

            @Field()
            @Property({lowercase: true}) 
            name: string 

            @Field()
            @Property({lowercase: true})
            surname: string

            @Field()
            @Property({lowercase: true})
            email: string

            @Field()
            @Property({default: false, index: true})
            emailConfirmed: boolean

            @Field()
            @Property()
            mobile: string 

            @Field()
            @Property()
            phone: string

            @Field()
            @Property({default: false, index: true})
            mobileConfirmed: boolean

            @Field(type => Address)
            @Property({ _id: false })
            postalAddress: Address

            @Field(type => Address)
            @Property({ _id: false })
            billingAddress: Address

            @Field()
            fullName(@Root() parent: Contact): string { 
              const fullName = `${parent.name} ${parent.surname || ''}` 
              return fullName.trim();
            }

            @Field(type => [Note])
            allNotes(@Root() parent: Contact) {
              return NoteModel.find({ contactRef: parent._id }).select('body')
            }


          }


Which extends a shared class:

          @ObjectType()
          export class CreatedTypegoose extends Typegoose {
            
            @Field()
            @Property({ default: () => unixTimestampSeconds() })
            createdDate: number

            @Field(type => User)
            @Property({ index: true })
            createdUser: Ref<User>

            @Field(type => Business)
            @Property({ index: true })
            createdBusiness: Ref<Business>

          }

**Comment by hasezoey** [comment]
> @Property({ index: true })
        createdBusiness: Ref<Business>

basic mistake, fix it with this below:
```ts
@Property({ index: true, ref: "Business" }) 
createdBusiness: Ref<Business>
```
Note: use ref as a string do avoid Errors like "cant use 'Business' before creation"

---

PS: if this does not answer your question, please provide what `@Field`, `@ObjectType` & `@Property`(i assume its `prop as Property`) is, thanks

**Comment by RyannGalea** [comment]
Thanks @hasezoey, ill give this a try and report back. Knew it would likely be something simple.

**Comment by Laubeee** [comment]
I basically have the same question. How am I supposed to convert a string to a ref-object?

If I do something like this
`const x: Ref<User> = new ObjectId("myhexstring");`
I get an error that ObjectId cannot be assigned to Ref type.
Currently I am doing some workaround like this:
`const x: Ref<User> = (new Types.ObjectId("myhexstring") as unknown) as Schema.Types.ObjectId;`
which is VERY ugly. Is there a better way?

**Comment by hasezoey** [comment]
@Laubeee please use [the new repository](https://github.com/typegoose/typegoose) for questions, this repo is not maintained anymore

**Comment by Laubeee** [comment]
phew. It sure seems to be difficult to actually get an answer to questions in this repo. Nevertheless I am sure I won't be the last that's gonna be led here by google, so posting an answer here (if there is a simple one) would still be beneficial.
If there is none and this needs to be addressed as means of further development I will be happy to open a new issue in the new repo and link it here for those who end up at this place (or you could do so)

**Comment by hasezoey** [comment]
@Laubeee i would like this repo to be archived (like #398) but only the repository owner can do this

> It sure seems to be difficult to actually get an answer to questions in this repo

i know, but i say this because much changed since the move to the new repo, because this one couldnt be maintained (the original author abandoned this project, and the other 2 maintainers that i know of either left or didnt have much time to review pr's and maintain this project)

> (if there is a simple one) would still be beneficial.

the answer as low because this repo here is old, and if written here it is either not noticed, or targeted at 5.x or earlier which are versions that are not maintained by the newer project anymore (version 6 and 7 are already out on the new one)

PS: and this is because [and documentation website](https://typegoose.github.io/typegoose/) exists now for the project instead of an long readme (most of the new questions here are answered by this)
