### ISSUE TITLE
TypeScript questions

### ISSUE THREAD

**Issue by alizahid** [szokodiakos/typegoose#309]
Hey,

I've got a couple of questions.

---

### `id` is not defined

My understanding is that `id` is a virtual property on every Mongoose model. But this doesn't work.

```javascript
@prop()
get posts() {
  return Post.find({
    user: this.id
  })
}
```

**Error**

```
Property 'id' does not exist on type 'User'.ts(2339)
```

Neither does `_id`.

---

### `@arrayProp` defaults and properties

I have a `Rating` schema defined like this.

```javascript
class Rating extends Typegoose {
  @prop({ default: 1, max: 1, min: -1 })
  direction: number

  @prop({ default: new Date() })
  created: Date

  @prop({ default: new Date() })
  updated: Date

  @prop()
  user: ObjectId
}
```

And on my `Post` schema I have this.

```javascript
@arrayProp({
  default: [
    {
      user: this.user
    }
  ],
  items: Rating
})
ratings: Rating[]
```

Hope is that the default rating will be created when a `Post` is created.

1. Will this work?
2. Will the default values be automatically populated?
3. Will `this.user` be picked from the `Post`'s context?

Adding to this question, I can't seem to use `post.ratings.create` anymore because `ratings` is an array now.

Also, TypeScript has issues with this.

```javascript
post.ratings.push({
  direction,
  user
})
```

**Error**

```
Type '{ direction: number; user: ObjectId; }' is missing the following properties from type 'Rating': created, updated, getModelForClass, setModelForClass, buildSchemats(2345)
```

Also, `user` here is a string from input. How do I get it to typecast to `ObjectId`? Someone opened an issue yesterday about this #308.

---

Where do I define `toJSON` on the model? I want to override the `transform` method for some stuff.

**Comment by hasezoey** [comment]
> `id` is not defined

could you provide a model for both? (where the virtual is in & the Post model)

---

> Adding to this question, I can't seem to use `post.ratings.create` anymore because ratings is an array now.

where is this function "create" defined?

---

> Where do I define toJSON on the model? I want to override the transform method for some stuff.

as far as i know, you cant override toJSON on typegoose, you can only set if it should output virtuals, `_v`, `_id`

---

Note: more on other questions will follow

**Comment by hasezoey** [comment]
> `@arrayProp` defaults and properties

here is my dummy code, it fully works (look below the code for `default` advise)
Note: [I used this repo, because otherwise it would error out](https://gitlab.com/hasezoey/typegoose) (error that would come: #238)
```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Ref, Typegoose } from "./typegoose/src/typegoose";

class User extends Typegoose {
    @prop({ required: true })
    public name!: string;
}

class Rating extends Typegoose {
    @prop({ required: true, default: 1, max: 1, min: -1 })
    public direction: number;

    @prop({ required: true, default: new Date() })
    public created!: Date;

    @prop({ required: true, default: new Date() })
    public updated!: Date;

    @prop({ required: true, ref: "User" })
    public user: Ref<User>;
}

class Post extends Typegoose {
    @arrayProp({ required: true, items: Rating, _id: false })
    public ratings!: Rating[];
}

const UserModel = new User().getModelForClass(User);
const PostModel = new Post().getModelForClass(Post);
const RatingModel = new Rating().getModelForClass(Rating);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongod:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify309",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const dummyUser = new UserModel({ name: "dummyUser" } as User);
    await dummyUser.save();

    const dummyPost1 = new PostModel();
    await dummyPost1.save();

    dummyPost1.ratings.push(new RatingModel({ user: dummyUser } as Partial<Rating>));
    await dummyPost1.save();

    await mongoose.disconnect();
})();
```
---

> ```
>default: [
>    {
>      user: this.user
>    }
>  ],
> ```

if you want to use a default for an arrayProp, wich is not an primitive, i suggest you use a wrapper function like this below
Note: i dont know how you came to the user id in  the default, so i just imagine
```ts
function makePost(user: InstanceType<User>): InstanceType<Post> {
    const newPost = new PostModel();
    // tslint:disable-next-line:object-literal-shorthand
    const defaultRating1 = new RatingModel({ user: user } as Partial<Rating>);
    newPost.ratings.push(defaultRating1);

    return newPost;
}
```
Note for above: [see the Note for README#instancetype](https://github.com/szokodiakos/typegoose#instancetype)

---

PS: i hope this answers your `arrayProp` question(s)

**Comment by alizahid** [comment]
Thank you for the quick response!

This is my `User` model.

```typescript
import { Typegoose, prop } from 'typegoose'

import Post from './post'

class User extends Typegoose {
  @prop({ default: new Date() })
  created: Date

  @prop({ default: true })
  notifications: boolean

  @prop()
  platform: string

  @prop()
  pushToken: string

  @prop({ default: new Date() })
  updated: Date

  @prop()
  get posts() {
    return Post.find({
      user: this.id // this is where the error is: Property 'id' does not exist on type 'User'.ts(2339). same for `_id`
    })
  }
}

export default new User().getModelForClass(User)
```

And this is my `Post` model.

```typescript
import { ObjectId } from 'bson'
import { sumBy } from 'lodash'
import {
  Typegoose,
  InstanceType,
  ModelType,
  arrayProp,
  prop,
  instanceMethod,
  staticMethod
} from 'typegoose'

class Comment extends Typegoose {
  @prop()
  body: string

  @prop({ default: new Date() })
  created: Date

  @prop()
  user: ObjectId
}

class Rating extends Typegoose {
  @prop({ default: 1, max: 1, min: -1 })
  direction: number

  @prop({ default: new Date() })
  created: Date

  @prop({ default: new Date() })
  updated: Date

  @prop()
  user: ObjectId
}

class Post extends Typegoose {
  @prop()
  body: string

  @arrayProp({ items: Comment })
  comments: Comment[]

  @prop({ default: new Date() })
  created: Date

  @arrayProp({ items: Number })
  location: number[]

  @arrayProp({
    default: [ // will replace this with a wrapper method as you suggested. or maybe on a `pre-save` or `init` hook? how do I do those with Typegoose?
      {
        user: this.user
      }
    ],
    items: Rating
  })
  ratings: Rating[]

  @prop()
  user: ObjectId // I only want to save the user `_id` and nothing else. should I use `Ref` or does this work?

  @prop()
  get meta() {
    return {
      comments: this.comments.length,
      rating: sumBy(this.ratings, 'direction')
    }
  }

  @instanceMethod
  rated(this: InstanceType<Post>, id: string) {
    return Boolean(this.ratings.find(({ user }) => user.equals(id)))
  }

  @staticMethod
  async rate(
    this: ModelType<Post>,
    id: string,
    user: string,
    direction: number
  ) {
    const post = await this.findById(id)

    const rating = post.ratings.find(rating => rating.user.equals(user))

    if (rating && rating.direction === direction) {
      return rating
    }

    if (rating && rating.direction !== direction) {
      rating.direction = direction

      await post.save()

      return rating
    }

    if (!rating) {
      const index = post.ratings.push({ // can't use `create` here, which is a support Mongoose method for sub-document arrays. `create` would allow me to return the `Rating` sub-document separately instead of doing `post.ratings[index]`
        direction,
        user // error: Type 'string' is not assignable to type 'ObjectId'.ts(2322). once I fix this by new Object(user), I get this error:   Type '{ direction: number; user: ObjectId; }' is missing the following properties from type 'Rating': created, updated, getModelForClass, setModelForClass, buildSchemats(2345)
      })

      console.log(post.ratings[index])

      await post.save()

      return post.ratings[index]
    }
  }
}

export default new Post().getModelForClass(Post)
```

I've inlined all my comments and questions.

**Comment by hasezoey** [comment]
first, you should always export the class too (to use it as a reference or so)

like:
> public user: ObjectId; // I only want to save the user `_id` and nothing else. should I use `Ref` or does this work?

use `user: Ref<User>` (note: User is the class)

---

> default: [ // will replace this with a wrapper method as you suggested. or maybe on a `pre-save` or `init` hook? how do I do those with Typegoose?

you can use a wrapper or these hooks, but you should remove the default property from the options

---

> user: this._id // this is where the error is: Property 'id' does not exist on type 'User'.ts(2339). same for `_id`

you must for that define this like so:
```ts
public get posts(this: InstanceType<User>) {
```
BIG Note: there are 2 versions of "InstanceType", you must import it from Typegoose!

---

> // can't use `create` here, which is a support Mongoose method for sub-document arrays. `create` would allow me to return the `Rating` sub-document separately instead of doing `post.ratings[index]`

yes, currently not implemented

---

> user // error: Type 'string' is not assignable to type 'ObjectId'.ts(2322). once I fix this by new Object(user), I get this error:   Type '{ direction: number; user: ObjectId; }' is missing the following properties from type 'Rating': created, updated, getModelForClass, setModelForClass, buildSchemats(2345)

use this currently:
```ts
...

const RatingModel = new Rating().getModelForClass(Rating);

...

@staticMethod
    public async rate(
        id: string,
        user: InstanceType<User>,
        direction: number
    ) {
        const post = await PostModel.findById(id)

        ...

        if (!rating) {
            const newrating = new RatingModel({ user } as Partial<Rating>);
            const index = post.ratings.push(newrating);

            await post.save();

            return post.ratings[index];
        }

```
Note: `...` means there is other code between

---

is something unclear or not answered?

**Comment by alizahid** [comment]
Thank you, that clears up everything.

However, I'm now running into a new issue.

In VS Code, `Post.rate` works just fine. Intellisense, etc.

But when I run the code, `Post.rate` is undefined. Any ideas why?

**Comment by alizahid** [comment]
Also, looks like `Ref<User>` does not have an `equals` method on it. I'm doing `user === id` right now.

**Comment by alizahid** [comment]
Also, how do I run `toJSON` on sub docs?

For example.

```
const post = await Post.findById(id)

return {
  ratings: post.ratings.map(rating => rating.toJSON({
    virtuals: true
  })
}
```

**Comment by hasezoey** [comment]
> Also, looks like Ref<User> does not have an equals method on it. I'm doing user === id right now.

i never knew that it had an equals method before

---

> Update: toJSON actually works. But Typescript shows this error.

you should not define a toJSON on a model/schema, because of mongoose's toJSON, when you want subdocuments you should use mongoose's toJSON, and modify the json from there on

---

> But when I run the code, Post.rate is undefined. Any ideas why?

do you mean `PostModel.rate` is undefined? because the `Post` otherwise is just the schema, on there the functions will not work

**Comment by alizahid** [comment]
>i never knew that it had an equals method before

You need that to compare ObjectIds with strings. It would be nice to have that added to the types.

>you should not define a toJSON on a model/schema, because of mongoose's toJSON, when you want subdocuments you should use mongoose's toJSON, and modify the json from there on

I'm overriding Mongoose's `toJSON` in the schema to fit my needs. It makes it easier to define it there than to mutate my response object in every controller.

>do you mean PostModel.rate is undefined? because the Post otherwise is just the schema, on there the functions will not work

Yes, I mean `PostModel`. I just named it `Post` for readability, I guess.

**Comment by alizahid** [comment]
@hasezoey This seems like a bug. Did you get a chance to look at it?

**Comment by hasezoey** [comment]
@alizahid, sorry for this late response, but could you clarify what the issue/bug currently is?
is it that  your "ObjectIDs" dont have a `.equals` function or that the `PostModel` dosnt have an `.rate` function?

**Comment by hasezoey** [comment]
when it is the `.rate` problem, did you already try to set `static` before the `async` statement?
like so: `static async rate(`?

**Comment by alizahid** [comment]
Both, but I can just `@ts-ignore` the `equals` problem for now. It's not a huge deal.

For the `.rate` is.

---

`PostModel.rate` not existing is a big one, though.

I just tried adding static. I get this error now;

```
post_1.default.rate is not a function
```

Without static, I get;

```
models_1.Post.rate
```

I will create a small project from scratch and follow the docs to see if I can reproduce it. I'm assuming you're not able to?

**Comment by alizahid** [comment]
So, this is the code;

```typescript
import { connect } from 'mongoose'
import { ModelType, Typegoose, prop, staticMethod } from 'typegoose'

connect(
  'mongodb://localhost:27017/test',
  {
    useNewUrlParser: true
  }
)

class User extends Typegoose {
  @prop()
  name?: string

  @staticMethod
  hello(this: ModelType<User>, name: string) {
    return `Hello, ${name}`
  }
}

const UserModel = new User().getModelForClass(User)

UserModel.hello('Ali')
```

And it throws this error;

```
UserModel.hello('Ali')
          ^
TypeError: UserModel.hello is not a function
```

**Comment by hasezoey** [comment]
so, as a conclusion:
- all Questions are solved, right?
- one thing that came up is that `ObjectId`'s dont have an `.equals` method?
-> when you use the `mongoose.Types.ObjectId`, then typegoose can do nothing about it, because its and `@types/mongoose` problem
-> when you use bson's `ObjectId`, typegoose can do nothing too ...

i would consider it closed now, except when the `ObjectId` thing is actually a typegoose problem.

**Comment by hasezoey** [comment]
@Ben305 this can be considered solved & closed

**Comment by alizahid** [comment]
Yes, thank you. All questions are resolved.
