### ISSUE TITLE
Enhanced enum support

### ISSUE THREAD

**Issue by 19majkel94** [szokodiakos/typegoose#31]
Right now, you support string array as an enum:
```ts
// Enum-like type and definition example.
type Gender = 'male' | 'female';
const Genders = {
  MALE: 'male' as Gender,
  FEMALE: 'female' as Gender,
};

@prop({ enum: Object.values(Genders) })
gender?: Gender;
```
However we have string enum support in TS now. It would be nice if the decorator function accept also the `object` type as the `enum` value and get the string values using `Object.values(object)` inside:
```ts
// true enum type
enum Gender {
  MALE = 'male',
  FEMALE = 'female',
};

@prop({ enum: Gender })
gender?: Gender;
```
So the signature of the `BasePropOptions` would be `enum?: string[]|object;` and you can in runtime check if `Array.isArray(enum)` to behave like now or convert enum object to values.

**Comment by 19majkel94** [comment]
I can make a PR if you want 😉

**Comment by szokodiakos** [comment]
Hello! Yes, when I saw the new string enums I wanted to make this but currently don't have enough time for it. A PR would be awesome indeed!
