### ISSUE TITLE
Support mongoose `refPath`

### ISSUE THREAD

**Issue by mschnee** [szokodiakos/typegoose#310]
For feature parity, add support for [Mongoose Dynamic References](https://mongoosejs.com/docs/populate.html#dynamic-ref)

```js
const commentSchema = new Schema({
  body: { type: String, required: true },
  on: {
    type: Schema.Types.ObjectId,
    required: true,
    // Instead of a hardcoded model name in `ref`, `refPath` means Mongoose
    // will look at the `onModel` property to find the right model.
    refPath: 'onModel'
  },
  onModel: {
    type: String,
    required: true,
    enum: ['BlogPost', 'Product']
  }
});

const Product = mongoose.model('Product', new Schema({ name: String }));
const BlogPost = mongoose.model('BlogPost', new Schema({ title: String }));
const Comment = mongoose.model('Comment', commentSchema);
```

```ts
class Schema extends Typegoose {
    @prop()
    body: string

    @prop({ required: true, refPath: 'onModel' })
    on: Ref<BlogPost | Product>

    @prop()
    onModel: string
}
```

**Comment by RyannGalea** [comment]
I want to try and implement this into my notes Schema, but I'm confused on how I would type it to 'Type-Graphql', Any ideas?

          @ObjectType()
          export class Note extends CreatedTypegoose {

            @Field() 
            @prop()
            body: string

            @Field(type => ) ???
            @prop({ required: true, refPath: 'modelRef' })
            model: Ref<Contact | Property>

            @Field(type => ModelRef)
            @prop({required: true, enum: Object.values(ModelRef), index: true})
            modelRef: ModelRef
            
          }

**Comment by hasezoey** [comment]
@RyannGalea this is not really a questions for here, try to make a question in https://github.com/19majkel94/type-graphql/issues , i tried and searched, but didnt found anything related to refPath or multiple types

Note: i dont know anything about graphql

**Comment by mschnee** [comment]
Hey y'all- given that the relevant PR has been merged (thanks for the quick response), I'm going to close the issue.
