### ISSUE TITLE
@pre Hooks  on updateOne

### ISSUE THREAD

**Issue by thurft** [szokodiakos/typegoose#315]
I can create an execute 
```ts
@pre<Offer>("updateOne", (next: HookNextFunction, offer: any) => {
  console.log("[**** updateOne *****]");
  console.log(offer.toString());
  next();
})
```

and I can see something like this from the console log

``
function(error, result) {
 oldCb(error, result ? result.result : {ok: 0, n: 0, nModified: 0});
      }
```

i was wondering if i can do anything from the  `offer` function to edit data before its updated? because the `@pre<Offer>("save"` never get executed...

Whats the work around to play with the data pre being updated by the `updateOne`

**Comment by hasezoey** [comment]
i think you have a small formatting issue

btw after \`\`\` you can do the language like "ts"

-> when fixed, i will remove this comment

**Comment by hasezoey** [comment]
> `@pre<Offer>("updateOne", (next: HookNextFunction, offer: any) => {`

i dont know how you try, but what i can see, is that the "next" function is always at the end
-> so you are essentially doing `next.toString()`

**Comment by thurft** [comment]
@hasezoey  since I can't access `save` on the operation `updateOne`.  I would inside the `@pre<Offer>("updateOne"`  to access the object `Offer` and a public property before its saved, just like you would do on `@pre<Offer>("save"` if that makes sense 

```ts
@pre<Offer>("save", (next: HookNextFunction) => {
 this.isOfferLive = false;
  next();
})
@pre<Offer>("updateOne", (next: HookNextFunction, offer: any) => {
  console.log("[**** updateOne *****]");
  console.log(offer.toString());
  next();
})
export class Offer extends Typegoose {
  @prop({ required: true, default: false })
  public isOfferLive: boolean;
}
export const Model = new Offer().getModelForClass(Offer);
```

**Comment by hasezoey** [comment]
ok, i take my last comment back, i thought "next" and "result" would be switched, like in the "@post" methods,

---

and normally this *should* work what you are trying todo

... and from what the types say "offer"(/in types it is "docs") is defined as an array ...

---

-> i will write back when i tested your code

**Comment by hasezoey** [comment]
so after my testing i got the following:
- `@pre<Offer>("updateOne", (next: HookNextFunction, offer: any) => {` must be a normal function, and not an arrow function
- had to replace "offer" with "this"
- "this" is a "mongoose.Query"
- i didnt find anything to add something like a "$set" or modify the value in any way
- that typegoose hooks types are broken

PS: why do you want to update on updateOne and not save? (could i see how you call .updateOne?)

**Comment by thurft** [comment]
@hasezoey 

Thank you so much for the effort on checking this undocumented thing. Yes. it seems a hack rather than a proper implementation 


as per `PS: why do you want to update on updateOne and not save? (could i see how you call .updateOne?)`

This was the original `updateOne` but i dont know how performance would be to use the `mongosee.Query`
```ts
Model.updateOne({ offerNumber: id }, req.body, {
    new: true,
  })
    .then(data => {
      if (data.n === 0) {
        return next(new AppError(1100, "Offer Not Found"));
      }

      res.json({ data: req.body });
    
    .catch(error => {
      return next(AppError.fromError(error));
    });
```

I instead choose to change the query for something different that uses the `@pre<T>("save"`
Not elegant i know and requires more work but does the trick for now.

```ts
Model.findOne({ offerNumber: id })
    .then(data => {
      // if (data.n === 0) {
      //   return next(new AppError(1100, "Offer Not Found"));
      // }
      if (data === null) {
        return next(new AppError(1100, "Offer Not Found"));
      }
      const entries = Object.entries(req.body);

      entries.forEach((element: any) => {
        const name: any = element[0];
        const value: any = element[1];
        // @ts-ignore
        data[name] = value;
      });
      data.save();

      res.json({ data });
   
    })
    .catch(error => {
      return next(AppError.fromError(error));
    });
```

**Comment by hasezoey** [comment]
should this be considered "closed"/"solved" now?

PS: you still have some small formatting wrong in the original question

**Comment by thurft** [comment]
Thank you!
