### ISSUE TITLE
[Bug] {select} not working properly

### ISSUE THREAD

**Issue by hasezoey** [szokodiakos/typegoose#326]
## Versions

- NodeJS: 12.6.0
- Typegoose(GIT): 943c5890e5434f0c793d4dcff47a9fc9a4591794
- mongodb: 4.1-bionic (docker)

---

It is probably not a typegoose problem, but @shilangyu in #197 (& i after testing) have found that `@prop({ select })` is not working properly example in #327

**Comment by shilangyu** [comment]
@Ben305 any chance the merge can be released as a minor release? The npm version has the bugged `select`. Thanks!

**Comment by Ben305** [comment]
Done
