### ISSUE TITLE
Removing 'id' field from Typegoose

### ISSUE THREAD

**Issue by Pikachews** [szokodiakos/typegoose#33]
Would it be possible to remove the `id` field from the Typegoose class?

My documents have their own `id` field which are numbers instead of strings, so TypeScript gives me an error telling me that I haven't extended the Typegoose class properly. However, removing the `id` field from the Typegoose typings allows it to compile and work just fine.

If having the `id` field is necessary in some way, maybe consider renaming it to `_id` since `id` does not necessarily seem to be reserved in MongoDB.

**Comment by szokodiakos** [comment]
Hello, yes currently `id` is forced into the model with ObjectID. I'm planning to extend this with customization.
