### ISSUE TITLE
[FP] Add Mongoose discriminators

### ISSUE THREAD

**Issue by gotenxds** [szokodiakos/typegoose#332]
## Which feature
Discriminators
https://mongoosejs.com/docs/discriminators.html

## Why do you want it
Currently the best we can do when it come to inheritance is extending the class.
Discriminators adds a layer to that so when we fetch data we get only the type we want
So if we have 
class Item of collection items
class weapon extends item of collection items

currently if we do 
```
Item.find() //we get all items
Weapon.find() //we get all items
```

discriminators will allow us to 
```
Item.find() //we get all items
Weapon.find() //we get all weapons

```

**Comment by hasezoey** [comment]
Note: i dont fully understand discriminator currently, but i have some questions

1. would it work with #331? (also the `const DiscriminatedModel = SomeModel.discriminator("name", SomeSchema)`?) [i will test it, but like i said in my note, i dont know if it would be what is wanted]
2. would someone otherwise have some implementation proposal?

**Comment by hasezoey** [comment]
as my Test result, yes it fully works with #331, but some makeup should be done, here the code i used
```ts
import * as mongoose from "mongoose";
import { InstanceType, prop, Typegoose } from "./typegoose/src/typegoose"; // Note: using PR#331

class Main extends Typegoose {
    @prop({ required: true })
    public main1?: string;
}

class Dis extends Main { // extends, because property "main1" will still be needed for mongoose
    @prop({ required: true })
    public dis1: string;
}

const MainModel = new Main().getModelForClass(Main);
const DisModel = MainModel.discriminator("hello", new Dis().buildSchema(Dis));

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify332",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    await (new MainModel({ main1: "main1" })).save();
    await (new DisModel({ dis1: "dis1", main1: "main1?" } as Partial<InstanceType<Dis>>)).save();

    await mongoose.disconnect();
})();
```

-> i propose a new function, something like `Typegoose.buildDiscriminator`
(but i will wait until #331 is merged OR is squashed)

**Comment by hasezoey** [comment]
@gotenxds, i made a Draft at #333 for Discriminators, but not everything is working correctly...

**Comment by naorzr** [comment]
@hasezoey I think that ```Typegoose.buildDiscriminator``` would be taking this library out of it's original scope.
It should better focus on providing a broader way to infer mongoose schema from typescript class.

**Comment by hasezoey** [comment]
uhm it does everything the mongoose style, the function is just there to feed the created model to the typegoose storage & to output the right types

**Comment by hasezoey** [comment]
discriminator support is added in 6.0.0-16, which can be tested at `@hasezoey/typegoose@next`

-> this can be closed
@Ben305
