### ISSUE TITLE
[Question] Extending existing Typegoose Class within same collection

### ISSUE THREAD

**Issue by HendrikRoth** [szokodiakos/typegoose#337]
Hello everyone,
is it possible to extend a created typegoose class (entity) but using the same collection as the parent class?

example:

```ts
class Base extends Typegoose {
  @prop()
  name: string;
}

class Extended extends Base {
  @prop()
  age: number;
}
```

instead of creating a new collection for extended i would like to use the same base collection. Is this possible and how? I tried to use mongoose SchemaOptions, but seams not to work for this variant?

```ts
const ExtendedModel = new Extended().getModelForClass(Extended, { schemaOptions: { collection: "base" } });
```

The goal is to be able to query the mongo database with the BaseModel helper.

```ts
const BaseModel = new Base().getModelForClass(Base);
await BaseModel.findById(...);

// should deliver also the extended entries.
```

**Comment by hasezoey** [comment]
so when i understand this correctly:
- you want to have a parent model
- you want to have a child model, extending the parent model
- you want the parent & child to use the same collection
- and you want to still query the child model, but only with the values from the parent model

right?

---

yes, it is half possible:
you can have a child & parent in the same collection with [Discriminators](https://mongoosejs.com/docs/discriminators.html), BUT they are currently not supported with typegoose, #333 adds it, but also breaks some things
and no, to my knowledge it is not possible, at least not with typegoose and the correct types ...

**Comment by HendrikRoth** [comment]
Yes you did understand me right.
Ok, than i have to figure out how to change my structure, thank you

**Comment by hasezoey** [comment]
i consider it solved | closed now, thanks that i could help
