### ISSUE TITLE
No isModified function or isNew property inside hooks

### ISSUE THREAD

**Issue by nullpixel** [szokodiakos/typegoose#34]
This makes hashing passwords almost impossible for me.

code to reproduce: 

```ts
@pre<User>('save', function(next) {
    if (this.isModified("password") || this.isNew) {
        // errors
    }
})
```

**Comment by szokodiakos** [comment]
Hey thanks, an additional interface is required to make in Typegoose and one should alter the type of `this` on the callback function. When I will have time I will create the proper interface.

**Comment by nullpixel** [comment]
Thanks! I love typegoose, by the way!

**Comment by nullpixel** [comment]
Awesome! Thanks
