### ISSUE TITLE
[FP] subDocument @props are missing schema options, hooks, middleware, plugins, virtuals, everything, because buildSchema() is not run on them

### ISSUE THREAD

**Issue by mschnee** [szokodiakos/typegoose#340]
## Which feature
- [Subdocuments](https://mongoosejs.com/docs/subdocs.html)

## Why do you want it

To quote from the mongoose documentation (emphasis added)

> Subdocuments are similar to normal documents. Nested schemas can have middleware, custom validation logic, virtuals, and any other feature top-level schemas can use. **The major difference is that subdocuments are not saved individually, they are saved whenever their top-level parent document is saved.**

This is a core feature of mongoose: nested documents or subdocuments are fully featured mongoose documents, with hooks, virtuals, and their own schema options.  These documents are **not compiled into models** and **do not cause the creation of mongodb collections**.

### This means that there are two necessary action items:
- We need to be able to define schema options for Typegoose classes that will **not** have `getModelForClass` invoked.  This is trivial, and should be implemented using a class-level decorator such as `@options(opts: mongoose.SchemaOptions)` or `@schemaOptions(opts: mongoose.SchemaOptions)`
- `baseProp()` needs to be updated to invoke `buildSchema` on a property that derives from `Typegoose` and that has not already had its schema compiled.  
  - To do this, `baseProp` can/should be refactored into a standalone function instead of a private method.

## Additional Notes
It is a core concept of mongoose to describe nested documents that have full feature configuration, hooks, plugins, and virtuals, but that do not become models or mongodb collections.  This is the single major missing feature preventing me from migrating existing mongoose projects to using Typegoose.

**Comment by hasezoey** [comment]
i must say, i never used | needed to use a validator on a subdocument, but i am surprised that there isnt a test for it, i will think about adding one & verifying the feature/core concept

**Comment by aoi-umi** [comment]
you can try this 
[mongoose-ts-ua](https://www.npmjs.com/package/mongoose-ts-ua)

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed

subdocuments (at least as Objects) are supported in 6.0.0 and subdocuments (without a schema) arnt supported by typegoose (by design), but there is a `buildSchema` function in v6.0.0 if needed

**Comment by hasezoey** [comment]
@Ben305 Bump to close

**Comment by mschnee** [comment]
Agreed, it's an acceptable solution :)
