### ISSUE TITLE
[Question] Is it possible to map fieldName to field_name?

### ISSUE THREAD

**Issue by DawTaylor** [szokodiakos/typegoose#344]
We're migrating a project from JS to TS and we decided to go with Typegoose.

Our models use `snake_case` convention for field names, however it seems that Typegoose does not support it out of the box, at least I couldn't figure out how. Is that possible?

I thought of something like this class;
```ts
class UserAddress extends Typegoose {
  @prop({ fieldName: 'zip_code' })
  zipCode: string
}
```

That would have the following Schema output;
```js
new Schema({
  zip_code: String,
})
```

**Comment by hasezoey** [comment]
i dont know what you are trying to archive, but when you just mean simple usage, `@prop()` is enough for a string, when you try to reference another model from a different collection, use `Ref<T>`, if you try to use [something like this](https://mongoosejs.com/docs/populate.html#populate-virtuals), translate this to typegoose, documentation is missing for this (i added this, but cant fully understand this)

if these above are not what you want, please clarify your question and yes, typegoose uses `PascalCase`

**Comment by DawTaylor** [comment]
I'm not trying to reference another model, and I'm not sure how would virtuals or alias help us. We don't actually need a `field_name` alias, we need to persist the document with `field_name` while using `fieldName` on the application.

For instance, a document for the `user` collection would look like;
```
{
  avatar_url: 'https://...',
}
```

**Comment by hasezoey** [comment]
> We don't actually need a `field_name` alias, we need to persist the document with `field_name` while using `fieldName` on the application.

thats what i meant, when you use some different "alias" in the application / DB, you should define what is saved on your DB and make an alias (virtual) for your application

like:
```ts
class Dummy extends Typegoose {
    @prop()
    public save_as_this?: string; // what is saved to the DB

    @prop()
    public get saveAsThis() { // an virtual "alias"
        return this.save_as_this;
    }
    public set saveAsThis(to: string) {
        this.save_as_this = to;
    }
}
```

**Comment by DawTaylor** [comment]
Thanks for the example @hasezoey.
