### ISSUE TITLE
[Poll] Continuation of feature/4?

### ISSUE THREAD

**Issue by hasezoey** [szokodiakos/typegoose#356]
*mainly targeting @Ben305 @vinczedani @szokodiakos, but feedback from anyone is appreciated*

I would ask if the continuation of the branch(/ something like that) would be appreciated?

Advantages would be:
- when using some thing like `await new DummyModel({prop: 'hi'} as DummyType).save();` would not in any case require the typegoose(current) function to build a model, but still require the virtual properties ....
- would not add overhead with each class created

Disadvantages would be:
- i dont know any currently

would target something like `Typegoose@6.0.0` for this kind of feature

**Comment by Ben305** [comment]
@hasezoey I haven't looked into the feature/4 branch but when there are some useful features inside, I would love to see these changes in master.

Unfortunately, my time is very limited at the moment...

**Comment by hasezoey** [comment]
> I haven't looked into the feature/4 branch but when there are some useful features inside, I would love to see these changes in master.

currently `feature/4` removes the Typegoose class, and makes all functions inside not needing a class, so this would resolve these `setModelForClass` etc `is missing from T`

**Comment by Ben305** [comment]
I think it's worth it, even it's a breaking change.

**Comment by hasezoey** [comment]
Closed - It will be integrated in 6.0.0, but a poll about how in #373
