### ISSUE TITLE
Is pre validate hook available

### ISSUE THREAD

**Issue by dragouf** [szokodiakos/typegoose#357]
I'm trying to use @pre 'validate' hook but it's seems not to be triggered. Is it available in typegoose ?

**Comment by hasezoey** [comment]
all these hooks are supported with types in typegoose
https://github.com/szokodiakos/typegoose/blob/ea1c0ec6bbebdd6b27ba4580ec39c1d3535b2084/src/hooks.ts#L7-L17

[how to use them](https://github.com/szokodiakos/typegoose#pre)

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale"
