### ISSUE TITLE
[Poll] add plugin mongoose-autopopulate as "native-typegoose"?

### ISSUE THREAD

**Issue by hasezoey** [szokodiakos/typegoose#371]
*Title says all, respond with comments or reactions to this*

example:
```ts
@prop({ auto: true, ref: 'someClass' })
public something: Ref<someClass>;
```

**Comment by nartc** [comment]
+1 this.

I've been trying to get autopopulate to work with Typegoose but I can't seem to get it to work. Here's what I've tried so far:

```ts
@plugin(require('mongoose-autopopulate'))
class User ... {
     @ExposedProp({ refPath: 'FileReference', autopopulate: true })
     @Type(() => FileReference)
     avatar?: Ref<FileReference>;

     @ExposedProp({ ref: FileReference, autopopulate: true })
     @Type(() => FileReference)
     avatar?: Ref<FileReference>;
}
```

`@ExposedProp` is a custom decorator that combine `Expose` (from ClassTransformer) and `prop` so it's not a big deal. `Type` is also from ClassTransformer. Side note: I'm using ClassTransformer to play with some reflection.

Both `ref` and `refPath` doesn't work. I always get `avatar: ObjectId(...)` in my query response. 

If you/anyone has had autopopulate working with typegoose, I'd be appreciate to listen to some guides. Thanks

**Comment by hasezoey** [comment]
> Both ref and refPath doesn't work. I always get avatar: ObjectId(...) in my query response.

isnt this how it should work? ref is a reference to a doc in another collection (/ database), when you have such a problem, please open an issue for this

**Comment by hasezoey** [comment]
i will close this here, because the "design goal" hasnt changed in typegoose to implement such thing, but since version 6.0.3, default class for `mongoose-findorcreate` got added, and the `autopopulate` PropOption for `mongoose-autopopulate`
