### ISSUE TITLE
Validation is being ran on unset fields

### ISSUE THREAD

**Issue by shilangyu** [szokodiakos/typegoose#372]
## Versions

- NodeJS: 12.7.0
- Typegoose(NPM): 5.8.1
- mongoose: 5.6.2
- mongodb: newest? (its ran on Mongo Atlas)

## Code Example

I have an optional field that lets say holds a middle name of a person. It is validated with a regex.
```ts
class PersonModel {
	@prop({ validate: /^[A-Z][a-z]+$/ })
	middleName?: string
}
```

Mongoose allows unsetting fields by assigning `undefined` to it. Like so:
```ts
const person = await PersonModel.findById(userId)

if (!person) throw new Error('error')
person.middleName = undefined
await person.save()
```

However this fails because: `Error [ValidationError]: Person validation failed: Validator failed for path 'middleName' with value 'undefined'`

## Do you know *why* it happens?

My guess would be the validation is still being run even tho the field is being unset.

**Comment by shilangyu** [comment]
To clarify, setting `undefined` did unset the field before I added a validation regex to it

**Comment by hasezoey** [comment]
validation is not an issue with typegoose, the regexp in this case is passed to mongoose and mongoose runs the validation, sorry

**Comment by shilangyu** [comment]
To fix it I added `{ validateBeforeSave: false }` to the `.save()` call.

@hasezoey if i find time i will check if this happens in mongoose too.

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "not an issue with typegoose"

**Comment by hasezoey** [comment]
@Ben305 Bump to close
