### ISSUE TITLE
[Question] Can I add a label or comment to one property?

### ISSUE THREAD

**Issue by MaxGeorgeBlack** [szokodiakos/typegoose#374]
In mongoose, I write one property with a label
`  name: {
    type: String,
    label: 'Customer name',
    max: 50,
    optional: true,
  },`

But it seems that "label" is not supported in typegoose. Any solutions or ideas?

**Comment by hasezoey** [comment]
could you provide a link where mongoose documents this?

**Comment by mfulop** [comment]
Some plugins like mongoose-json-schema are using this technique, and it makes sense to me as well. I simply extended the PropOptions declaration to allow this (I am on the phone but tomorrow I can show you how)

**Comment by mfulop** [comment]
@hasezoey for this reason I recommend keeping the current way of forwarding the whole provided PropOptions object to mongoose and I would also either document how to extend the declaration or add [k:string]: any to the PropOptions declaration

**Comment by hasezoey** [comment]
> add [k:string]: any to the PropOptions declaration

will be added into 6.0.0 :)
