### ISSUE TITLE
Optional object fields always created

### ISSUE THREAD

**Issue by Pikachews** [szokodiakos/typegoose#38]
Models containing fields of a custom class type seem to always be created when retrieving a document from the collection, even if said field is optional.

For example, the model:
```
class Thing extends Typegoose {
    @prop() text: string;
}

class Container extends Typegoose {
    @prop() numeric: number;
    @prop() custom?: Thing;
}
```
----
The collection:
```
[ { numeric: 1 } ] // _id omitted for brevity
```
----

If you query and log the result to the console, it logs the expected value
```
Collection.findOne({ numeric: 1 }).then(r => console.log(r));
```
logs
```
{ numeric: 1 } // _id omitted for brevity
```

But you can somehow still access the non-existent 'custom' field and it will return an empty object
```
Collection.findOne({ numeric: 1 }).then(r => console.log(r['bonus']));
```
logs
```
{ }
```
whereas it *should* be `undefined` since it isn't defined in the document.

I'm not exactly sure that this is Typegoose's fault, but I don't think this should happen using just Mongoose, but I haven't tried. 😕

**Comment by vinczedani** [comment]
Hi @Pikachews 
I tested your issue and it is true that it prints an empty Object, so I created a native mongoose test to see how it works there.

my mongoose schema:
```const testSchema = new mongoose.Schema({
  nested: {
    value: String,
  },
  numeric: Number,
});

export const mongooseModel = mongoose.model('Test', testSchema);
```

my test code:
```const nativeMongoose = await Test.create({
      numeric: 1,
    });

    console.log(JSON.stringify(nativeMongoose, null, 2));
    console.log(nativeMongoose['nested']);

    const foundNative = await Test.findOne({
      numeric: 1,
    });

    console.log(JSON.stringify(foundNative, null, 2));
    console.log(foundNative['nested']);
```

That printed out the following:
```
{
  "__v": 0,
  "numeric": 1,
  "_id": "59c2287fe89e526d3f9ccb07"
}
{}
{
  "_id": "59c2287fe89e526d3f9ccb07",
  "numeric": 1,
  "__v": 0
}
{}
```
So the native mongoose implementation prints nested objects too. We don't want to differ from their functionality, even if it is not completely logical so I am closing this issue.
Thanks for using Typegoose and reporting your issues.
Cheers,
Daniel
