### ISSUE TITLE
[ts-jest only] `enum` can only be set on an array of strings, not undefined

### ISSUE THREAD

**Issue by duro** [szokodiakos/typegoose#380]
## Versions

- NodeJS: 10.15.2
- Typegoose(NPM): 5.8.1
- mongoose: 5.6.9
- mongodb: 3.2.7

## Code Example

The below example is a sub-document of a parent Typegoose model

```ts
import { arrayProp as ArrayProperty } from 'typegoose'

export enum UpdateOptions {
  EMAIL = 'email',
  PUSH = 'push',
}

export class UserUpdatesPreferences {
  @ArrayProperty({
    items: String,
    enum: UpdateOptions,
    default: [UpdateOptions.EMAIL, UpdateOptions.PUSH],
  })
  public promotions: UpdateOptions[]

  @ArrayProperty({
    items: String,
    enum: UpdateOptions,
    default: [UpdateOptions.EMAIL, UpdateOptions.PUSH],
  })
  public mobile: UpdateOptions[]

  @ArrayProperty({
    items: String,
    enum: UpdateOptions,
    default: [UpdateOptions.EMAIL, UpdateOptions.PUSH],
  })
  public recommendations: UpdateOptions[]
}
```

## Do you know *why* it happenes?

*no*

## Additional Notes

This only started appearing when we tried to upgrade from mongoose 5.6.5 -> 5.6.9.

Here is the full stack trace that throws in our tests:

```
    `enum` can only be set on an array of strings, not undefined

      2 |   Typegoose,
      3 |   prop as Property,
    > 4 |   index as Index,
        |                                      ^
      5 |   arrayProp as ArrayProperty,
      6 |   pre as PreHook,
      7 |   // InstanceType,

      at SchemaArray.Object.<anonymous>.SchemaArray.enum (../../node_modules/mongoose/lib/schema/array.js:205:13)
      at SchemaArray.SchemaType (../../node_modules/mongoose/lib/schematype.js:85:18)
      at new SchemaArray (../../node_modules/mongoose/lib/schema/array.js:87:14)
      at Schema.Object.<anonymous>.Schema.interpretAsType (../../node_modules/mongoose/lib/schema.js:865:12)
      at Schema.Object.<anonymous>.Schema.path (../../node_modules/mongoose/lib/schema.js:606:27)
      at Schema.add (../../node_modules/mongoose/lib/schema.js:444:12)
      at new Schema (../../node_modules/mongoose/lib/schema.js:121:10)
      at baseProp (../../node_modules/typegoose/src/prop.ts:265:25)
      at ../../node_modules/typegoose/src/prop.ts:287:3
      at DecorateProperty (../../node_modules/reflect-metadata/Reflect.js:553:33)
      at Object.decorate (../../node_modules/reflect-metadata/Reflect.js:123:24)
      at Object.<anonymous>.__decorate (src/models/User/User.ts:4:92)
      at Object.<anonymous> (src/models/User/User.ts:80:3)
```

**Comment by hasezoey** [comment]
which typescript version?
and did you try typegoose 5.9.0 (or even 6.0.0)?

**Comment by hasezoey** [comment]
Tested it, cant replicate it in 5.9.0 & 6.0.0-19

used code (syntax of 6.0.0): 
```ts
enum TestEnum {
  HELLO1 = 'Hello 1',
  HELLO2 = 'Hello 2'
}
class TestEnumArray {
  @arrayProp({ items: String, enum: TestEnum })
  public somevalue: TestEnum[];
}

const model = getModelForClass(TestEnumArray);
const { _id: id } = await model.create({ somevalue: [TestEnum.HELLO1, TestEnum.HELLO2] } as TestEnumArray);
const found = await model.findById(id).exec();

expect(found).to.not.be.an('undefined');
expect(found.somevalue).to.deep.equal(['Hello 1', 'Hello 2']);
```

**Comment by duro** [comment]
@hasezoey upgrading to 5.9.0 did not seem to help. The only way I have been able to get tests to pass is by removing all Array Props from my model.

**Comment by duro** [comment]
@hasezoey The odd thing as well is that this only appears to happen when running inside tests. If I manually test the service locally, I get no errors.

**Comment by duro** [comment]
@hasezoey I was actually able to reproduce with a super minimal repo here:

https://github.com/duro/typegoose-repro

**Comment by hasezoey** [comment]
@duro yes i can see the error, but i dont understand why it happenes, because it works in non-jest environments, like mocha, ts(compiled)...

**Comment by hasezoey** [comment]
it seems like this is an issue with ts-jest, i dont know what causes it, and i will not be investigating further because i dont know & use jest (sorry), for now the only workaround is to compile the tests first and then run them OR dont use (ts-)jest

@duro could you add "[ts-jest only]" to your title?

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "not an issue with typegoose" / cant be fixed

**Comment by hasezoey** [comment]
I ran your repo again, with latest `@typegoose/typegoose` (6.0.4), and upgraded:
- jest to 24.9.0
- ts-jest to 24.1.0
- typescript to 3.6.4
- mongoose to 5.7.7

and the test runs fine - i guess it got fixed now
