### ISSUE TITLE
[Question] How to use `Int32` schema type?

### ISSUE THREAD

**Issue by wxs77577** [szokodiakos/typegoose#381]
https://www.npmjs.com/package/mongoose-int32

**Comment by hasezoey** [comment]
there was *somewhere* an documentation for "custom" types, but i cant find it, will probably add an test & documentation in 6.0.0

**Comment by hasezoey** [comment]
@Ben305 this can be closed in favor of https://github.com/hasezoey/typegoose/issues/36
