### ISSUE TITLE
NPM install broken

### ISSUE THREAD

**Issue by lForain** [szokodiakos/typegoose#383]
## Versions

- NodeJS: 0.0.0
- Typegoose(NPM): 0.0.0
- Typegoose(GIT): commithash
- mongoose: 0.0.0
- mongodb: 0.0.0

## Code Example
```
getModelForClass<T>(t: T, { existingMongoose, schemaOptions, existingConnection }?: GetModelForClassOptions): mongoose.Model<InstanceType<this>, {}> & this & T;
    setModelForClass<T>(t: T, { existingMongoose, schemaOptions, existingConnection }?: GetModelForClassOptions): mongoose.Model<InstanceType<this>, {}> & this & T;
    buildSchema<T>(t: T, { schemaOptions }?: GetModelForClassOptions): mongoose.Schema<any>;
```

## Do you know *why* it happenes?

The last version published its broken in this part of the code, when i clone the lib from the latest commit and use it, it works fine. I was trying to fix it by every way thinking my code was wrong, but the version 5.9.0 its not working( the one i got using npm install typegoose ). Please can you publish the latest commit as npm module at npm registry? so i can use it reliably into my project, not by cloning the lib from your repositorie and pasting into my `./src`.

**Comment by hasezoey** [comment]
i dont understand what should be wrong with the currently published version of it (no one other seems to have this issue), could you try `@hasezoey/typegoose@latest`, and if this dosnt work `@hasezoey/typegoose@next`? (note: latest is 5.9.0 and next is 6.0.0)

**Comment by hasezoey** [comment]
btw you can install it as a git package `git+https://github.com/szokodiakos/typegoose.git#5.9.0`(or let everything behind `#` empty to get the **always latest** version

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed
