### ISSUE TITLE
[Question] Populate Virtuals

### ISSUE THREAD

**Issue by AyumiKai** [szokodiakos/typegoose#386]
hey guys, how to define populate virtuals？

**Comment by hasezoey** [comment]
*<sub>[Soon<sub>TM<sub/>](https://hasezoey.github.io/typegoose/docs/decorators/prop/#virtuals)*

[Currently in here](https://github.com/hasezoey/typegoose/tree/r6/master#virtuals) (For V6.0.0)

**Comment by AyumiKai** [comment]
> _[Soon™](https://hasezoey.github.io/typegoose/docs/decorators/prop/#virtuals)_
> 
> [Currently in here](https://github.com/hasezoey/typegoose/tree/r6/master#virtuals) (For V6.0.0)

thank you
