### ISSUE TITLE
[Question] Additional properties in typegoose?

### ISSUE THREAD

**Issue by taimooralam** [szokodiakos/typegoose#390]
Mongoose can enable [adding of additional properties](https://mongoosejs.com/docs/guide.html) on objects by setting the `strict` flag to `false`.

`var thingSchema = new Schema({..}, { strict: false });`

I am looking to add custom properties to typegoose objects. Is this possible to do in typegoose?

**Comment by hasezoey** [comment]
when you use version 6.x.x:
```ts
@modelOptions({ schemaOptions: { strict:false } })
```

in v ~5.5+
```ts
.getModelForClass(class, { schemaOptions: { strict:false } })
```

does this solve your issue?

PS: please dont open new issues here, use the new repo

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" & "solved?"

**Comment by hasezoey** [comment]
@Ben305 Bump to close
