### ISSUE TITLE
[Question] Import ObjectId from Typegoose?

### ISSUE THREAD

**Issue by lcswillems** [szokodiakos/typegoose#396]
Is it possible to import ObjectId type from Typegoose? If not, it would be convenient to be able to import it.

**Comment by hasezoey** [comment]
typegoose dosnt use anything different than the mongoose `ObjectId`

PS: this repo / package is not supported anymore, please use the new https://github.com/typegoose/typegoose

**Comment by lcswillems** [comment]
Sorry, I wanted to publish it in the other repo. I think you should archive this repository. Without this, it is very hard to see that this one is not the good one because this repo appears first in Google search results and there is no clear distinction.

I will open it in the other repo.

**Comment by lcswillems** [comment]
You can also transfer issues from this repo to the good one.

**Comment by hasezoey** [comment]
>  I think you should archive this repository

> You can also transfer issues from this repo to the good one.

that is the reason a new repo was made in the first place, because i dont (and still dont) have any write permissions on this repo, that is why hasezoey/typegoose (and later typegoose/typegoose) was made
