### ISSUE TITLE
[Question] Type of User.x property is not a y

### ISSUE THREAD

**Issue by Tobjoern** [szokodiakos/typegoose#401]
I have the following code in Typegoose:

```
    @prop({ required: false  })
    x!: string | null;
```
The compiler throws the following error: Type of User.x property is not a string.
I just found the solution by trial and error, but I will still post this issue anyway, because I wasn't able to find the solution by googling, so maybe this will help someone else.
The solution to this is definitely defining the type like so:

```
    @prop({ required: false, type: String  })
    x!: string | null;
```

**Comment by hasezoey** [comment]
this repository is not maintained anymore, please use https://github.com/typegoose/typegoose

PS: you issue was using `!` and `| null` instead of an `?` (`required` is `false`)
