### ISSUE TITLE
my populate field cant be queried out

### ISSUE THREAD

**Issue by yKanon** [szokodiakos/typegoose#405]
I need a virtual field so that it can be populated into response.

I do these in Course model.
![image](https://user-images.githubusercontent.com/19491751/83708147-206e9780-a64e-11ea-85c9-dd2e075ab935.png)
![image](https://user-images.githubusercontent.com/19491751/83707838-8eff2580-a64d-11ea-9500-17a1ac001802.png)
then. set prop course in Episode model
![image](https://user-images.githubusercontent.com/19491751/83708225-5c096180-a64e-11ea-93a2-4f70e434732a.png)

on front end.I need to get the detail message  of  one course, with episodes. so

**Comment by yKanon** [comment]
![image](https://user-images.githubusercontent.com/19491751/83708658-5c562c80-a64f-11ea-85a3-3844e73e03fa.png)
but the result is disapointed~:
![image](https://user-images.githubusercontent.com/19491751/83708714-80b20900-a64f-11ea-94fa-c3fa782cc0ff.png)
I think I have a right relationship between Episode and Course~
![image](https://user-images.githubusercontent.com/19491751/83708879-e69e9080-a64f-11ea-904f-883208cc5835.png)
![image](https://user-images.githubusercontent.com/19491751/83708909-f74f0680-a64f-11ea-8c93-fb9a5a005ac9.png)

**Comment by hasezoey** [comment]
@EX-EA this repository is not maintained anymore, please look at the [new repository](https://github.com/typegoose/typegoose)

**Comment by yKanon** [comment]
> @EX-EA this repository is not maintained anymore, please look at the [new repository](https://github.com/typegoose/typegoose)

ok, sorry~~
