### ISSUE TITLE
[Question] Can we add custom error messages when @prop options fail?

### ISSUE THREAD

**Issue by LikhithKolayari** [szokodiakos/typegoose#408]
In Mongoose we can add custom error messages to override the default message that is thrown when inserting/updating data violates the Schema.
Eg:
```
var breakfastSchema = new Schema({
  eggs: {
    type: Number,
    min: [6, 'Too few eggs'], //Custom error message
    max: 12
  },
  bacon: {
    type: Number,
    required: [true, 'Why no bacon?'] //Custom error message
  }
})
```

**Comment by hasezoey** [comment]
this repository is not maintained anymore, [look at the new repository instead](https://github.com/typegoose/typegoose)

**Comment by LikhithKolayari** [comment]
Closing this thread as it is irrelevant
