### ISSUE TITLE
[Question] Are transactions supported for deleteMany?

### ISSUE THREAD

**Issue by Tobjoern** [szokodiakos/typegoose#409]
Hey, I noticed that the 'session' option (used for transactions) is not supported in the types (at least).
Now I'm wondering if it is at all supported for deleteMany?
Reading up online I noticed that deleteMany [wasn't supported](https://github.com/Automattic/mongoose/issues/6805) for quite a while, but now transactions are [supported](https://mongoosejs.com/docs/api.html#query_Query-setOptions) on all operations.

Is this a mistake, or are transactions not supported?

**Comment by hasezoey** [comment]
this repository is not maintained anymore, [look at the new repository instead](https://github.com/typegoose/typegoose)
