### ISSUE TITLE
Type return of getModelForClass

### ISSUE THREAD

**Issue by ElMatella** [szokodiakos/typegoose#41]
Hi, I'm trying typegoose since yesterday, and I have a question related to your implementation. (Thanks a lot for your work, this package rocks!):

Why can't we assign a model as a type? 

```
import { prop, Typegoose} from 'typegoose'

class User extends Typegoose {
    ...
    @prop({ required: true})
    public firstName: string;
    ...
}

export default new User().getModelForClass(User);
```

```
import User from './User'

let user:User = new User(); // -> Does not work because User is not a type 
```

**Comment by lwallent** [comment]
Hi @ElMatella,

You are trying to make an instance of the Model which may not be what you had in mind?

May I suggest keeping things separate - doing something like:

```
export class User extends Typegoose {
    ...
    @prop({ required: true})
    public firstName: string;
    ...
}

export const UserStore = new User().getModelForClass(User);
```
and then importing the User and/or Store?

```
import { User, UserStore } from './User';

let user:User = new User(); 

 const store = new UserStore(user); 
 await store.validate();
 user = await store.save();

```
But be aware, there is a snake in paradise ... 
I will create a question myself about properties not having the writable property set in a minute. 

Currently if you wish to work directly on the object properties you will have to make the properties writable in a hackish kind of way (not desirable):

```
export class User extends Typegoose {
    ...
   @prop(<any>{required:true, writable: true})
    public x: string;
    ...
}

export const UserStore = new User().getModelForClass(User);

let user:User = new User(); 
user.x = "test";
let store = new UserStore(user);
store.save();
```
Not making the property writable will produce a TypeError like:

`TypeError: Cannot assign to read only property 'x' of object '#<User>'`

Please note I am ***not*** part of the _typegoose_ team and the above approach is not recommended in the long run, but I hope to convince the creators of the library to add the writable flag within the _typegoose_ code :-) I have a local typegoose version where I have made this change. If you need it - then we are two :-) Good luck with your project!

Kind Regards
Lasse

**Comment by lwallent** [comment]
Hi @ElMatella,
I have created a PR on the writable issue described in my previous post.
KR
Lasse

**Comment by ElMatella** [comment]
Thanks a lot for your response, it totally makes sense that way. It feels more like a repository kind of thing implementation. It would be great to have that documented if your PR is being merged.

**Comment by szokodiakos** [comment]
Hi, I've reviewed the PR. There needs to be some adjustments to make it fully featured. I've described the details at the PR's page.

Akos

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed
