### ISSUE TITLE
Cannot use same model on two connections.

### ISSUE THREAD

**Issue by dcarniel** [szokodiakos/typegoose#416]
In order to split database I'm trying to use the same model on multiple databases depending on context.

Unfortunately, when invoking the "getModelForClass" the internal cache used to build model only once ignores the connection (cf: https://github.com/szokodiakos/typegoose/blob/99f6be02dfb53c42fd5dd9209d4d73e4e2bcc97f/src/typegoose.ts#L51 ).

It would be interesting that this cache take the existingConnection (or existingMongoose) in account to allow instantiating multiple times the same model with a different underlying connection.

**Comment by hasezoey** [comment]
this repository is not maintained anymore, look at the [new repository](https://github.com/typegoose/typegoose)

**Comment by dcarniel** [comment]
Sorry, I didn't check the actual repo. I copied my ticket there, thanks for your response.
