### ISSUE TITLE
[Question] Is there a `required if` feature on model classes?

### ISSUE THREAD

**Issue by adil-waqar** [szokodiakos/typegoose#417]
Hello all. I just wanted to know if we could do something like this in our model definition:
```ts
class MyModel {
  @prop({ required: true })
  public hasHost!: boolean;

  @prop({ required: this.hasHost })
  public myHost!: string;
}
```

**Comment by hasezoey** [comment]
wrong repo, https://github.com/szokodiakos/typegoose/issues/391

PS: as you can see [in the mongoose documentation](https://mongoosejs.com/docs/validation.html) you can make more or less all validators from mongoose an function

**Comment by adil-waqar** [comment]
Thank you!
