### ISSUE TITLE
Fields loaded are more than in the Model definition

### ISSUE THREAD

**Issue by pgsfredda** [szokodiakos/typegoose#46]
Hi.
Great job but I have encountered maybe a trouble:
If I use the 'find' method of my little example in that I defined only two fields (username and email), if there are more fields in the database (firstname, lastname, username, email, password, ...), Typegoose load all the field. If I use the mongoose schema, mongoose load only the two field. It seems like when you define an empty schema.
Can you explain me that?
Below I attached my source files: server, the model and a route page.

[user.model.ts](https://github.com/szokodiakos/typegoose/files/1359110/user.model.txt)
[IndexRoute.ts](https://github.com/szokodiakos/typegoose/files/1359113/IndexRoute.txt)
[server.ts](https://github.com/szokodiakos/typegoose/files/1361722/server.txt)

Thank you! Typegoose is really THE typescript solution for mongoose.

**EDIT (06/oct/2017):**
I found the solution using the '**projection**' parameter of the '_find_' method. 
I don't know if there is a typegoose method or a better idea to compose the projection string:

**let proj = Object.keys(UserModel.schema.obj).join(' ');**

```js
public index(req: Request, res: Response, next: NextFunction) {
       let proj = Object.keys(UserModel.schema.obj).join(' ');

        UserModel.find({}, proj, (err, data) => { 
            if(err) {
                res.status(200).json({msg: 'err', "err": err});
                return next(err);
            }
            res.status(200).json({msg: 'ok', "data": data});
           // prints:
           // {"msg":"ok","data": [{"_id":"57669d50a87cfa704393bf54","username":"myusername","email":"mail@domain.it"}]}
        });

    }

```

**Comment by szokodiakos** [comment]
Hello. That is an interesting finding. Actually Typegoose under the hood composes a Mongoose schema using the props defined by your class, no more. It wont scan the db for pre existing fields, so it is really interesting.

Anyway I will try to reproduce the problem when I will have the time and will get back to you with the results.

**Comment by vinczedani** [comment]
Hi @pgsfredda 
Based on your edit in your issue I close this issue.
I paste your solution so if someone from google ends up here, will find it faster.
Cheers,
Daniel

```
EDIT (06/oct/2017):
I found the solution using the 'projection' parameter of the 'find' method.
I don't know if there is a typegoose method or a better idea to compose the projection string:
```
