### ISSUE TITLE
Troubles with reciprocal reference fields in the models

### ISSUE THREAD

**Issue by pgsfredda** [szokodiakos/typegoose#50]
Hi.
Please, can you help me to solve a problem with reciprocal reference fields in the models?
Yes, it seems strange but usefull in something situations.

If you have two classes with reciprocal reference fields in the models, you can receive an Error (_In property user: Object is not a primitive type nor a Typegoose schema (Not extending it)._) during che compilation phase.
Maybe because one of the classes is not yet defined. This happens also if the two classes are in the same file.
I searched for a foreward instruction without success.

Below a short example:

```js
import { prop, staticMethod, instanceMethod, Typegoose, ModelType, InstanceType, Ref } from 'typegoose';

export class Admin extends Typegoose {
    @prop() firstName: string;
    @prop({ ref: User }) user?: Ref<User>;
}
export const AdminModel = new Admin().getModelForClass(Admin);

export class UserRole {
    @prop({ ref: Admin }) admin?: Ref<Admin>;
}

export class User extends Typegoose {
    @prop({ required: true }) email: string;
    @prop({ required: true }) username: string;
    @prop() roles?: UserRole;
}
export const UserModel = new User().getModelForClass(User);

```

Thank you in advance.

**Comment by szokodiakos** [comment]
Hello. Yes I believe at this time, circular schema definitions are not supported, haven't tested it myself though but judging by your example that is the case.

I will keep an eye on this when developing Typegoose (also all PRs are appreciated).

**Comment by pgsfredda** [comment]
**EDIT: 10/oct/2017:**
Maybe I found the solution but I'm still testing that.
I'm using [Angular forwardRef function](https://angular.io/api/core/forwardRef).
It seems it works.

```js

import { prop, staticMethod, instanceMethod, Typegoose, ModelType, InstanceType, Ref } from 'typegoose';

import { forwardRef } from 'forwardref'
import { User } from './user.model';

export class AdminName {
    @prop() first: string;
    @prop() last: string;
};

export class Admin extends Typegoose {
    @prop() name?: AdminName;
    @prop({ ref: forwardRef(() => User) }) user?: Ref<User>;
}

export const AdminModel = new Admin().getModelForClass(Admin);
```

**Comment by MrHayato** [comment]
The workaround I've been using is to use an object with a name property as the class name as the ref/itemsRef:

```
class Chapter extends Typegoose {
    @prop({ ref: { name: 'Series' } }) public series: Ref<Series>;
}

class Series extends Typegoose {
    @arrayProp({ itemsRef: { name: 'Chapter' } }) public chapters: Ref<Chapter[]>;
}
```

Seems to work so far for me, but probably not something that'll work long term.

**Comment by pgsfredda** [comment]
Great! Thank you.
It transpilles. ;-)

Why do you think this solution is not good in the long term?
The '**name**' property for the '_ref_' field works for the mongoose '_populate_' method?

**Comment by pgsfredda** [comment]
Hi @WillsonHaw ,

I tested your solution: it works perfectly with '**_populate_**' method. 
Thank you!

**Comment by WillsonHaw** [comment]
If that metadata changes, then it can be an issue. Not likely, but just keep that in mind. Glad it worked out for you though!

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "not an issue with typegoose" - limitation of javascript

if someone has this error, please look at https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/
