### ISSUE TITLE
Feature: Class Type reflection capabilities

### ISSUE THREAD

**Issue by 19majkel94** [szokodiakos/typegoose#51]
I would love to see the reflection capabilities with class instances, just like `obj.constructor` works like.

I use `class-transformer` for document serialization:
```ts
import { Typegoose, prop as Property } from "typegoose";
import { Exclude, Expose } from "class-transformer";

@Exclude()
export class User extends Typegoose {

    @Expose()
    id: string;

    @Expose()
    @Property({ unique: true })
    email: string;

    @Property()
    password: string;

}

export const UserModel = new User().getModelForClass(User);
```

It would be amazing to be able to write generic `serialize` method which could take the original `ClassType` from the mongoose document and invoke `plaintToClass(ClassType, object)` without explicit specifying the constructor class function.

Examples:
```ts
// instead writing in http framework controllers methods
const dbUser = await UserModel.findOne({ email: "test" });
const clsUser = plainToClass(User, dbUser!);
return classToPlain(clsUser);

// I would like to return plain document
return await UserModel.findOne({ email: "test" });

// and the `serialize` method would be invoked by http framework before sending response to client
function serialize(document) {
    const ClassType = getClassTypeForTypegooseDocument(document);
    return plainToClass(ClassType, document);
}
```
I know that your main goal is to define the schema by class but since you don't return the class itself as a document (like TypeORM does) it would be necessary to provide posibility to get the class of the document of schema created by the class 😉 

I think that the best way would be to store `this.constructor` function from `getModelForClass` inside typegoose's `constructors` dictionary and then get the constructor by model name with the model name from `docObj.constructor.modelName` 😃

**Comment by szokodiakos** [comment]
Thanks, I've added comments to the PR.
