### ISSUE TITLE
.save() never returns

### ISSUE THREAD

**Issue by roeibh** [szokodiakos/typegoose#53]
Hi. I'm trying to follow your example and having difficulties.
my project structure is:
app.ts
server.ts
models
 -->user.model.ts
routes
  -->users.ts

in app.ts I'm defining the connection to the database:
```
constructor() {
    this.mongoose = new mongoose.Mongoose();
    this.express = express();
    this.express.use("/users", usersRouter);
    this.mongoose.connect("mongodb:\/\/localhost:27017/example", (err) => {
        if (err) {
            console.log('[-] Error connecting  to database mongodb:\/\/localhost:27017/example" - ${err.message}');
            throw err;
        } else {
            console.log('[*] Connected to database mongodb:\/\/localhost:27017/example');
        }
    });
}
```
server.ts is only there to start the server itself:
```
let app = new App();
app.express.listen(3000, () => {
    console.log('[*] server started on port 3000');
});
```
I've created a user model with Typegoose and added an API call via express to add a user to the system:
routes/users.ts (where i call 'addUser' from the model):
```
private static readonly UserModel = new User().getModelForClass(User);
usersRouter.post("/register", (req, res, next) => {
    let newUser = new Models.UserModel({
        email: req.body.email,
        name: req.body.name,
        password: req.body.password,
        username: req.body.username,
    });
    UserModel.addUser(newUser, (err, user) => {
        if (err) {
            res.json({
                msg: "Failed regisgter user",
                success: false,
            });
        } else {
            res.json({
                msg: "registered user",
                success: true,
            });
        }
    });
}
```
models/user.model.ts
```
export class User extends Typegoose {
    @staticMethod
    public static async addUser(newUser: InstanceType<User>, callback: (err: any, product: InstanceType<User>) => void)) {
        await newUser.save(callback);
    }
    @prop({required: true})
    public email: string;
    @prop()
    public name?: string;
    @prop({required: true})
    public password: string;
    @prop({required: true})
    public username: string;
}
```
everything's going fine until the line `newUser.save();`
the callback never get called... I also don't see any traffic in mongo.

The project work on JavaScript, now I'm trying to move to TS. Is there something I missed during the transmission or is it an issue?

**Comment by szokodiakos** [comment]
Hello

This is actually a feature and this isn't about Typegoose but it's how Mongoose's API works.

Mongoose supports both callback and Promise interface. Since you are using `async/await` meaning you `.then` on the operation in the behind scenes the callback gets ignored.

If you want to use the callback style, remove the `async/await` keywords from the code and it should be fine.

**Comment by roeibh** [comment]
Thanks for the answer.
unfortunately, the same behavior happens when I use the following function:
```
@staticMethod
    public static addUser(newUser: InstanceType<User>, callback: (err: any, product: InstanceType<User>) => void) {
        newUser.save(callback);
    }
```
The request just wait forever until timeout.

**Comment by vinczedani** [comment]
Hi @roeibh 
Since you said that the above solution worked, I close the issue.
If you have any new question feel free to create a new issue.
Cheers,
Daniel
