### ISSUE TITLE
Unresolved functions in IDE

### ISSUE THREAD

**Issue by MickL** [szokodiakos/typegoose#55]
Seems like the IDE thinks alot of Mongoose functions are undefined, but the code works:

![bildschirmfoto 2017-10-10 um 13 00 13](https://user-images.githubusercontent.com/5103210/31383342-016682fa-adbb-11e7-8779-4088a8262a56.png)

**Comment by szokodiakos** [comment]
Hi! Can you please post your whole code so I can see what is exactly `Person`, etc.?

**Comment by Ben305** [comment]
Closed because of missing feedback.
