### ISSUE TITLE
'plugin' documentation in README.md file improving

### ISSUE THREAD

**Issue by pgsfredda** [szokodiakos/typegoose#56]
Hi.
I'm using typegoose increasingly in a production project; it works and keep clean the source code. Thank you!

Maybe, in the README.md file you can specify the following tips about '**_plugin_**':

#### 1- plugin source file written in typescript: check the export instructions
If the plugin is developed with Typescript language and it is not a 3rd part software, check the first line of the transpilled file. 
From Typescript 2.2 the first transpilled js line after the '_use strict_' line, is '**Object.defineProperty(exports, "__esModule", { value: true });**' and a mongoose error is generated because a function is needed at start of plugin.
To avoid this error you can start the plugin in the Typescript source file with the line:

```js
module.exports = exports = function findOrCreatePlugin (schema, options?) {
...
}
```

#### 2- plugin static methods in typegoose class
_staticMethod_ decorator and an empy body {} are mandatory for a correct and complete method signature also when you add manually the static methods for typing information about a _schema.statics_ function in a plugin. 

```js
@staticMethod public static findOrCreate(condition: InstanceType<User>): Promise<{ doc: InstanceType<User>, created: boolean }> {};
```

Whitout these two warnings in the README.md it's possible to lose a lot of work time.

**Comment by hasezoey** [comment]
> `@staticMethod`

got removed in 6.0.0

---

> plugin source file written in typescript: check the export instructions

the user must pass it in, typegoose does not handle it (in the meaning of "importing" the module and giving the function to typegoose)

**Comment by hasezoey** [comment]
@Ben305 i think with the [new documentation](https://typegoose.github.io/typegoose/docs/decorators/plugins/) this can be closed
