### ISSUE TITLE
'expires' option in @prop decorator missing

### ISSUE THREAD

**Issue by pgsfredda** [szokodiakos/typegoose#57]
Hi.
It's very usefull the '_**expires**_' option for the schema field definition when data type is _**Data**_.

Below a mongoose example:

```js
new Schema({ 
   createdAt: { type: Date, expires: 60*60*24 }
});
```

Please, can you consider to implement it?
Thank you!

**Comment by vinczedani** [comment]
Hi @pgsfredda 
It is a good idea to add this functionality to typegoose, We would appreciate it if you could create a pull request. If not, we will try to do it ourselves when we some free time for the project.
Cheers,
Daniel

**Comment by pgsfredda** [comment]
Of course but it would be the first time for me creating a pull request. 
I'll try the solution by me and when I'm ready I'll create the request.
Thank you!

**Comment by pgsfredda** [comment]
Hi.
I tried to add  _**expires**_ field in the interface **BasePropOptions** in the _ts_ and _d.ts_ of **prop** file as listed below.
It seems work correctly! The saved rows are deleted after the time indicated in the **_expires_** field (string for time notation and number for milliseconds as with mongoose).

```ts
export interface BasePropOptions {
  required?: RequiredType;
  enum?: string[] | object;
  default?: any;
  unique?: boolean;
  index?: boolean;
  expires?: string | number;
}
```

**Comment by vinczedani** [comment]
Hi @pgsfredda 

Can you please create a pull request about this, with a test covering the new feature.

Cheers,
Daniel

**Comment by hasezoey** [comment]
because of https://github.com/szokodiakos/typegoose/blob/ea1c0ec6bbebdd6b27ba4580ec39c1d3535b2084/src/prop.ts#L51

this can be closed

@Ben305
