### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by gkbps** [szokodiakos/typegoose#63]
Dear Szokodiakos

Thank you for Typegoose that helps a lot in simplifying code and improve maintainability. I have an issue and could not understand why and how it happens when using 'mongoose-paginate' as the Typegoose plugin, I have followed the guides for similar issue in this git but it still does not work, could you help look at and kindly advise why plugin does not return result? 
Extracted code is as below (which worked well if I use plugin with native mongoose but not via Typegoose)

import {
    prop,
    Typegoose,
    InstanceType,
    staticMethod,
    plugin,
  } from 'typegoose';

// tslint:disable-next-line:no-var-requires  
import * as paginate from "mongoose-paginate";

export interface PageinateResult<T> {
    docs: [InstanceType<T>];
    total?: number;
    limit?: number;
  }

@plugin(paginate)
export class ClientType extends Typegoose {
    @prop({ required: true, minlength: 5, index: true })
    name: string;

    @prop()
    status?: string;
    
    static paginate: (query, options) => Promise<PageinateResult<ClientType>>;    
    // I thought the issue happens here but try several scenarios still not work
}
export const model = new ClientType().getModelForClass(ClientType);

Then

// As I use multi DB thus below
var client = new ClientType().getModelForClass(ClientType, {schemaOptions: {collection: 'Client'}, existingConnection: mongooseConnection});        
 
Where I expect it returns the documents, it only return the unfulfilled Promise
client.paginate(query, options)
.then(result => {
console.log(result)
});        

Thank you for your advices.

**Comment by szokodiakos** [comment]
Hello @gkbps ! Thanks for using Typegoose. I've tried to reproduced the problem (with a slightly modified version of your code).

```typescript
import {
  prop,
  Typegoose,
  InstanceType,
  staticMethod,
  plugin,
  } from '../typegoose';

import * as paginate from 'mongoose-paginate';

export interface PageinateResult<T> {
  docs: [InstanceType<T>];
  total?: number;
  limit?: number;
}

@plugin(paginate)
export class ClientType extends Typegoose {
  @prop({ required: true, minlength: 5, index: true })
  name: string;

  @prop()
  status?: string;

  static paginate: (query) => Promise<PageinateResult<ClientType>>;
}
const model = new ClientType().getModelForClass(ClientType);

await model.create({ name: '12345', status: 'status' });
const p = await model.paginate({});
console.log(p);
/*
 { docs:
   [ { _id: 59f0e425863d3fbd2a08e376,
       name: '12345',
       status: 'status',
       __v: 0 } ],
  total: 1,
  limit: 10,
  offset: 0,
  page: 1,
  pages: 1 }
*/
```

For me this has no issues. Can you please test that this code works for you? If so, can you please debug at which step does the `paginate` call becomes bad for you?

Thanks in advance!

Akos

**Comment by hasezoey** [comment]
i think because of no response in a long time and no one other had issues like this, this can be closed...

@Ben305
