### ISSUE TITLE
Mongoose types conflict with typegoose during build

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#65]
When running `tsc`, there are tons of `duplicatie identifier` errors if you have both `typegoose` and `@types/mongoose` installed.

Removing the latter solves the issue.

**Comment by vinczedani** [comment]
Hi @Christilut 
We are aware of the issue that typegoose has dependencies that should be listed as peer dependency, however it is a braking change to remove such dependecies, so it requires some planning.
Cheers,
Daniel

**Comment by xnramx** [comment]
I've the same issue. How can we solve it?

**Comment by Bracique** [comment]
Hi there,
I had the same problem but this solved it for me: https://stackoverflow.com/a/40667268/9052919
Hope that works for you, too.
Best, Michael

**Comment by frederik-b** [comment]
It helped to explicitly install the exact same version of @types/mongoose for me ("@types/mongoose": "4.7.15")

**Comment by Ben305** [comment]
With the release of typegoose 5.0.0, _mongoose_ and _reflect-metadata_ are now peer dependencies.
