### ISSUE TITLE
How to use InstanceType?

### ISSUE THREAD

**Issue by Christilut** [szokodiakos/typegoose#66]
I have my class like this:
```ts
export class User extends Typegoose {
}
```

How can I add `mongoose.Document` or `InstanceType` to it? Because now I have to do this in all my functions:
```ts
export async function addUser(args: IAddUserArgs): Promise<User & mongoose.Document> {
}
```
Which is a bit annoying because I have to import mongoose in every file that imports User.

I'm not sure how to do this with my limited TS knowledge :)

**Comment by szokodiakos** [comment]
Hello! Basically you can substitute `Promise<User & mongoose.Document>` with `Promise<InstanceType<User>>`

`InstanceType` is nothing else but a shorthand for the logical and of your class and the `mongoose.Document` (https://github.com/szokodiakos/typegoose#instancetype).

**Comment by Christilut** [comment]
Thanks, it works :)

**Comment by drryanjames** [comment]
I ran into something like this but kept getting errors. It took me too long to realize there's another InstanceType defined in es6. If you can't get InstanceType working make sure you're using the typegoose InstanceType by writing the following at the top of your file:

```import { InstanceType } from 'typegoose'```

**Comment by SpencerKaiser** [comment]
@CodeRhymesLife thank you for your comment above... I've been struggling with this for a while now. I would love to see typegoose get updated with a different name for that type to avoid naming collisions...

**Comment by Drageaux** [comment]
@CodeRhymesLife Exactly the answer I need
@SpencerKaiser A warning in the README would also have saved some anguish
