### ISSUE TITLE
Automatic pluralizing collection names

### ISSUE THREAD

**Issue by DonKennethVitug** [szokodiakos/typegoose#67]
Typegoose automatically pluralizing my collection names. for example my collection is device_warehouse, on the db it became device_warehouses with "s". I hope I can get feedback soon.

**Comment by vinczedani** [comment]
Hi @DonKennethVitug 
This is the default mongoose behaviour, since Typegoose is built upon mongoose, it works the same.
Cheers,
Daniel

**Comment by vinczedani** [comment]
Hi @DonKennethVitug 
You can pass in the collection name into the schema options like this to enforce mongoose not to pluralise your collection names:

```

export const device_warehouseModel = new device_warehouse().getModelForClass(device_warehouse, { schemaOptions: { collection: 'device_warehouse'}});
```
