### ISSUE TITLE
Error with nested classes order

### ISSUE THREAD

**Issue by joseluisgarciaott** [szokodiakos/typegoose#7]
I got the following error when trying to nest models...:

_**Error: There is no metadata for the "job" property. Check if emitDecoratorMetadata is enable in tsconfig.json
at [...]/node_modules/typegoose/src/prop.ts:148:11**_

... if the nested model is defined after the parent one (this is the same example of your md file, without the Car ref):

```
import { prop, Typegoose } from 'typegoose';

class User extends Typegoose {
    @prop()
    name?: string;

    @prop({ required: true })
    age: number;

    @prop()
    job?: Job;


}

class Job extends Typegoose {
    @prop()
    title?: string;

    @prop()
    position?: string;
}


export const UserModel = new User().getModelForClass(User);
```

The work around is to define Job before User.

I'm using:
Hapi 16.4.3, 
typegoose 3.0.0, 
typescript 2.4.1,
ts-node 3.1.0,

And yes, I have "emitDecoratorMetadata": true in tsconfig :wink: 

Let me know if you can reproduce this!
Thanks!

**Comment by szokodiakos** [comment]
Thank you for your report @joseluisgarciaott. Yes currently Job must be defined before User. I will investigate this further and update you about this.

**Comment by szokodiakos** [comment]
@joseluisgarciaott I investigated the issue, and came up with a solution: you could pass the `Job` class explicitly to the `prop` decorator as a `subdoc` property for example. I've implemented the feature quickly, then the following TypeScript error rose:

![issue](http://i.imgur.com/DVxlHQ3.png)

So it means that TypeScript won't actually let me use the class before declaration. The example provided in the documentation is wrong, i will update it, however the "workaround" must be used.

Or if you put each class to a separate file, then the import order should not matter (take a look at the tests for an example structure).

And I will try to add a more clear error message to prevent this happening in the future.

**Comment by szokodiakos** [comment]
I've created #9 as an enhancement task in which I add documentation and error message to make it more clear.

**Comment by joseluisgarciaott** [comment]
You are right. I thought classes definitions were hoisted, but **only their bindings are**... just like in the case of **let** and **const**: they indeed exist, but aren't yet initialized.

So yes, just change the doc and we are done :)

**Comment by szokodiakos** [comment]
Right! :) Closing this one.
