### ISSUE TITLE
findById read empty arrays when the items are defined with a "_id" field

### ISSUE THREAD

**Issue by pgsfredda** [szokodiakos/typegoose#72]
Hi.
I'm using yet **typegoose 3.5.2** because 3.6.0 don't works for me (see #68).

I defined a model with the "_id" field to simplify the configuration of data on db. This is not frequently but it works and it is admitted with mongoose. 

When I load in memory a doc defined with an array of items wich are defined with an "**__id_**" field, the array is empty.

Below the source file.

```js
import * as tg from 'typegoose';

export class perm extends tg.Typegoose {
    @tg.prop() routerFunction : string;
    @tg.prop() permit: boolean;
}

export const permModel = new perm().getModelForClass(perm);


export class group extends tg.Typegoose {
    @tg.prop( { required: true, index: true, unique: true } ) _id: string;
    @tg.prop( { required: true, index: true, unique: true } ) name : string;
    @tg.arrayProp( { itemsRef: perm } ) perms ?: tg.Ref<perm>[];
}

export const groupModel = new group().getModelForClass(group);

export class admin extends tg.Typegoose {
    @tg.prop() name : string;
    @tg.arrayProp( { itemsRef: group } ) groups ?: tg.Ref<group>[];
    @tg.arrayProp( { itemsRef: perm } ) perms ?: tg.Ref<perm>[];
}

export const adminModel = new admin().getModelForClass(admin);

adminModel.findById('an id').exec((err, data) => {
   console.log(data); // prints correctly the perms array data but an empty groups array
}
```

**Comment by derchirurg** [comment]
I found out: do not define _id as prop. Just use it as property and it should work.

**Comment by pgsfredda** [comment]
Thank you @derchirurg but your answer is not complete.
I tried to remove the _id definition field but:
if I save an **_id** as **string** I can't use that to find the recors and I can't load that field with typegoose using find or findbyid.

With other mongo client I can use that _id also when ai save it as ObjectID or as string because mongoose convert it automatically. So, I think this is a **typegoose issue**.

This is a problem for that records that you have to save before run the app for configuring something on the db. In that case is usefull to use a known _id (as string). But after is usefull use the automatic ObjectID generation.

**Comment by lukechatton** [comment]
Having the same issue. I want to access `_id` but am missing not being able to use findById() like I can in raw mongoose.

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" & "fixed?" - no-one encountered this again since January 2018, and should be working with v6
