### ISSUE TITLE
feathers-mongoose

### ISSUE THREAD

**Issue by Alex27052007** [szokodiakos/typegoose#75]
Hi,

I am trying to use Typegoose with feathers-mongoose and I guess I am making some beginner´s mistake, because I can´t get it to work.

My model class looks like this:

```
export class PostalCode extends Typegoose{
    @prop({ required: true })
    code: String
    @prop({ required: true })
    city: String
}

```

I thought, I could simply replace the model creation (which is commented out and works fine) with the getModelForClass statement, but this doesn´t work:

```
const service = require('feathers-mongoose');

function services() {
    /* var postalCodeSchema = mongoose.Schema({
        code: String,
         city: String
     });

    var PostalCodeModel = mongoose.model('PostalCode', postalCodeSchema); */

    var PostalCodeModel = new PostalCode().getModelForClass(PostalCode);

    this.use('/postalcode', service({
           Model: PostalCodeModel,   
           paginate: {
            default: 2,
            max: 4
           }
      }));
} 
```

I would be great if you could give me a hint, what I did wrong.

Thanks Alex

**Comment by vinczedani** [comment]
Hi @Alex27052007 

Thanks for sending us this issue. Is there any error log in your console? The code seems fine at first look. What versions of typegoose and mongoose do you use?

Cheers,
Daniel

**Comment by Alex27052007** [comment]
Hi Daniel,
unfortunately there is no error, I don´t get any response for the get request. 
I am using: 
feathers-mongoose 5.1.2
typegoose 3.7.0
mongoose 4.13.5

With the mongoose - schema version, I get the following response as expected:

```
{
    "total": 1,
    "limit": 2,
    "skip": 0,
    "data": [
        {
            "_id": "5a1e8c8a81397b0cc0b980dc",
            "code": "90478",
            "city": "Nürnberg",
            "__v": 0
        }
    ]
}
```

**Comment by PowerMogli** [comment]
I have the same problem please help us out. My environment looks almost the same like the one from Alex.

**Comment by hasezoey** [comment]
@Alex27052007 when you still use typegoose / feathers-mongoose, could you please say if this is still an issue? 
-> and when no-one has these issues anymore, please close it, thanks

**Comment by hasezoey** [comment]
@Ben305 i think this can be closed as "stale" - because of no further infomation of @Alex27052007

**Comment by hasezoey** [comment]
@Ben305 Bump to close
