### ISSUE TITLE
Data not saving correctly

### ISSUE THREAD

**Issue by dekaha1** [szokodiakos/typegoose#76]
I want to save a mongoose document with a typegoose sub-document but data isn't saving correctly.

**Car Model does not extend Typegoose**
`import * as mongoose from 'mongoose'
const Model = mongoose.Schema
const CarModel = new Model ({
  color: String,
  driver: { type: Schema.Types.ObjectId, ref: 'UserModel' },
})`

**UserModel extends Typegoose**
`export class User extends Typegoose {
  @prop()
  public name: string;
}

export const UserModel = new User().getModelForClass(User)`

**Different file to create Data to save**
const autoMobile = {};
autoMobile.color = 'black';
autoMobile.driver = new UserModel({name: 'Bob'});
`Car.create(autoMobile, (createdCar: any) => {
  return createdCar;
})`

Everything is saved correctly except the name attribute on the userModel. Mogoose even creates the ID correctly.  Any help is much appreciated

**Comment by dekaha1** [comment]
Sorry for the bad styling 

**Car Model does not extend Typegoose**
```
import * as mongoose from 'mongoose'
const Model = mongoose.Schema
const CarModel = new Model (
  { color: String,
  driver: { type: Schema.Types.ObjectId, ref: 'UserModel' }, 
  })
```

**UserModel extends Typegoose**
```
export class User extends Typegoose {
@prop()
public name: string;
}

export const UserModel = new User().getModelForClass(User)
```

**Different file to create Data to save**
```
const autoMobile = {};
autoMobile.color = 'black';
autoMobile.driver = new UserModel({name: 'Bob'});
Car.create(autoMobile, (createdCar: any) => { return createdCar; })
```
Everything is saved correctly except the name attribute on the userModel. Mogoose even creates the ID correctly. Any help is much appreciated

**Comment by vinczedani** [comment]
Hi @dekaha1 

Thanks for using typegoose and reporting your issue. I currently have no time to reproduce your issue. But I think I might know what is going wrong.

First You don't pass down your existing mongoose to Typegoose. You should do it like the following: ```
getModelForClass(User, { existingMongoose: mongoose })
```
The other thing is, that you use the ref as 'UserModel'. I think it wont work this way. typegoose creates models based on the constructor name (in this case 'User'). So you should try the following inside your bus Model description:
```
driver: { type: Schema.Types.ObjectId, ref: 'User' }, 
```

I hope you will be able to resolve your issues based on these comments.
May I ask, why are you using booth classic mongoose and typegoose at the same time?

Cheers,
Daniel

**Comment by bitjson** [comment]
@dekaha1 thanks, `{ existingMongoose: mongoose }` is what I needed too.
> May I ask, why are you using booth classic mongoose and typegoose at the same time?

I'd love to see an example of how to avoid installing `mongoose` in my project completely – is that possible? I'm currently having trouble getting the example in `readme.md` working without the `existingMongoose` setting.

**Comment by hershal** [comment]
Hey @vinczedani, your suggestion to add `{ existingMongoose: mongoose }` fixed it for me too, just wanted to add my $0.02. Cheers!

**Comment by hasezoey** [comment]
@bitjson 
> I'd love to see an example of how to avoid installing mongoose in my project completely – is that possible? I'm currently having trouble getting the example in readme.md working without the existingMongoose setting.

not possible, because as the name says its "typescript" + "mongoose" = "typegoose" so by design, it will not be supported without mongoose, typegoose is just a "wrapper" for schemas & models, not for the functions

Update:
in v6.0.0, `mongoose` is still a peer-dependencie, but could be get as `import { mongoose } from "@hasezoey/typegoose"`

@Ben305  this can be closed

**Comment by hasezoey** [comment]
@Ben305 Bump to close
