### ISSUE TITLE
Trouble connecting to Mongo, performing some operations when Typegoose is a dependency

### ISSUE THREAD

**Issue by bitjson** [szokodiakos/typegoose#82]
Thanks for the fantastic library! I've already appreciated using it in a small project.

I'm having trouble with a few use cases, and I'm unsure if these are bugs or if I'm misunderstanding the usage. I've tried to get usage examples from Typegoose's tests, but several features don't seem to work outside of the Typegoose module (i.e. when importing Typegoose to use in a different project).

Could I get some feedback on the issues with [these examples](https://github.com/bitjson/typegoose-objects-array)?

You can test quickly by:
```bash
git clone https://github.com/bitjson/typegoose-objects-array.git && cd typegoose-objects-array
npm install
```
```bash
npm run start1
# (review output)

npm run start2
# (review output)

npm run start3
# (review output)
```

[**Test 1**: Trying to save a User without using the existingMongoose option.](https://github.com/bitjson/typegoose-objects-array/blob/master/test1.ts)
[**Test 2**: Saving a User using the existingMongoose option. (Works)](https://github.com/bitjson/typegoose-objects-array/blob/master/test2.ts)
[**Test 3**: Trying to save a User with a property containing an array of objects.](https://github.com/bitjson/typegoose-objects-array/blob/master/test3.ts)

Only `Test 2` works for me (npm@5.6.0, node@8.9.3, mongo@3.4.10)

I'm most interested in what I'm doing wrong with `Test 3` – the same functionality, creating and using a model which includes an array of instances of another class (e.g. `previousJobs?: Job[]`), [works as expected in the tests](https://github.com/szokodiakos/typegoose/blob/v3.7.0/src/test/index.test.ts#L41). Am I missing something, or are these bugs?

**Comment by kyle-mccarthy** [comment]
I was looking at your repo and could reproduce your problems.  If you look in your node_modules folder do you have the reflect-metadata package?  If not, when you install that does it resolve your problems?  I explicitly added it as a dev-dependency in your repo and was able to get it working for me.

```
Setup complete.
Trying to save a User without using the existingMongoose option.
{ _id: 5ac408b3e56cf862503c5b71, name: 'Gimli', __v: 0 }
```

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "invalid" / "stale"
