### ISSUE TITLE
arrayProp with existingMongoose option - Cannot read property '$globalPluginsApplied' of undefined

### ISSUE THREAD

**Issue by pdupavillon** [szokodiakos/typegoose#84]
Hello, 
I'm encountering an issue when I use the arrayProp decorator with existingMongoose option set on the getModelForClass method.

example : https://gist.github.com/pdupavillon/f6c63b451971e317d842f11c8003749f
result : 
`TypeError: Cannot read property '$globalPluginsApplied' of undefined`

mongoose version : "^4.13.6"
 
Thanks

**Comment by robypag** [comment]
Hello there,
got the same issue and fixed by looking at #78 
Hope this helps!

**Comment by pdupavillon** [comment]
Hello @robypag,
Thanks for pointing this to me, that is seems to do the job !

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" - because it didnt got an update / someone that encounterd this issue again since december 2017
