### ISSUE TITLE
Can't save a model with an updated array - TypeError: Cannot read property 'casterConstructor' of undefined 

### ISSUE THREAD

**Issue by pdupavillon** [szokodiakos/typegoose#88]
Hello,
I'm having the following issue:
When I try to push a subdocument into a model's array, I get this error :
`TypeError: Cannot read property 'casterConstructor' of undefined `

example: https://gist.github.com/pdupavillon/48f5ed66c564f2b35e595309a46c62dc

`"mongoose": "^4.11.1", "typegoose": "^3.7.0"`

Thanks

**Comment by hasezoey** [comment]
This is as far as i can tell not an issue with typegoose, in mongoose it is a known issue when using "push to array" that causes error or inconsistency

@Ben305 This can be closed as not an issue with typegoose
