### ISSUE TITLE
Optional subdocument _id

### ISSUE THREAD

**Issue by pdupavillon** [szokodiakos/typegoose#89]
Hello,
Is there any way to make subdocument _id optional for array items ?.

In the example below, I would like to avoid the history's _id creation each time I push a new history
```
class History{
  @prop() name: string;
}
class User extends Typegoose {
  @prop() name?: string;
  @arrayProp({items:History}) histories: History[];
}
```

Thanks

**Comment by kyle-mccarthy** [comment]
Have you tried to use references in your array prop instead?

```
@arrayProp({ itemsRef: History })
histories: Ref<History>[];
```

**Comment by naivefun** [comment]
@kyle-mccarthy  doesn't that affect performance? I do not see why the `_id` is generated for each subdocument. Would love to see it's optional or completely gone :)

**Comment by naivefun** [comment]
mongoose supports this option, check this  https://stackoverflow.com/questions/17254008/stop-mongoose-from-creating-id-property-for-sub-document-array-items

would be great to add to prop options:
```typescript
@prop({ _id: false})
settings: any;
```

**Comment by naivefun** [comment]
in the meanwhile this hack shall work:
```typescript
  @prop({ _id: false } as any)
  settings: Settings;

  @arrayProp({ items: Version, _id: false } as any)
  versions: IVersion[] = [];
```

**Comment by naivefun** [comment]
oops, seems it's not preventing generating _id but simply ignore _id when loading object, not a solution then ...

**Comment by ssilve1989** [comment]
I'd like to see this as well. I also don't understand why a subdocument that isn't extending typegoose is getting `_id`'s populated.

**Comment by Ben305** [comment]
Let me know if this branch works for you: _https://github.com/szokodiakos/typegoose/tree/allow-suppressing-ids-for-subdocuments_

**Comment by marcelh-gh** [comment]
@pdupavillon, @naivefun, @ssilve1989 have you tried Ben's proposal?

**Comment by pdupavillon** [comment]
@Ben305, your branch is working for me !

**Comment by ssilve1989** [comment]
I ended up changing my schemas around, but glad to hear its working.

**Comment by Ben305** [comment]
@pdupavillon Thanks for your feedback, Release 5.2.0 has been published some seconds ago.

**Comment by pdupavillon** [comment]
@Ben305, Thank you for this fix !

**Comment by gentleShark** [comment]
just in case anyone comes across this page and still wonders what the solution is. it's: `@prop({ _id: false})`

**Comment by diephil** [comment]
@pdupavillon , do you remember how you made it work with your `History[]` ?
`@prop({ _id: false })` is working great for subdocument, but I can't make it work with subdocument **array**. I even tried `@arrayProp({_id: false})` hopelessly... Am I missing something?

**Comment by hasezoey** [comment]
@diephil please open a new issue with "question" or "bug" for this and with examples of your code, otherwise i(/we) cant help you, thanks
