### ISSUE TITLE
Dependency reflect-metadata conflict

### ISSUE THREAD

**Issue by nishkarsh** [szokodiakos/typegoose#90]
I am working on a project that has a dependency that in turn has a dependency to **reflect-metadata** version **0.1.10**. While trying to use typegoose, I see a dependency to reflect-metadata version **0.1.8**, which conflicts with the already existing version and the project fails.

It would be great if typegoose can start using the latest version of reflect-metadata (0.1.10 as of now).

Thanks!

**Comment by Ben305** [comment]
You can upgrade to typegoose 5.0, _reflect-metadata_ is now a peer dependency!
