### ISSUE TITLE
TypeError when building schema for parent classes.

### ISSUE THREAD

**Issue by momothereal** [szokodiakos/typegoose#91]
Using typegoose v3.8.0.

I have a class `UserSchema` which extends `DbSchema`, which extends `Typegoose`.

Note that `DbSchema` is an abstract class.

When I try to create the model for that the UserSchema class (see code below), I get this TypeError. I added a debug print statement at the beginning of the `buildSchema` function to see which class causes the error, and it appears to be the parent (DbSchema here).

```
Building schema for: UserSchema
Building schema for: DbSchema
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Schema.add (F:\icetea\node_modules\mongoose\lib\schema.js:370:21)
    at UserSchema.buildSchema (F:\icetea\node_modules\typegoose\lib\typegoose.js:57:17)
    at UserSchema.setModelForClass (F:\icetea\node_modules\typegoose\lib\typegoose.js:33:24)
    at UserSchema.getModelForClass (F:\icetea\node_modules\typegoose\lib\typegoose.js:20:18)
```

Code used:
```js
// schema is a <T extends DbSchema>, currently UserSchema.
// schema.getClass() returns the type (here: UserSchema)
let model = schema.getModelForClass(schema.getClass(), {existingMongoose: mongoose});
```

I checked what exactly was `null` that was passed to the Schema.add function, and it looks like `data_1.schema['DbSchema']` is undefined during the second buildSchema function execution. I printed the contents of `data_1.schema` before the error occurs, and it seems to only contain the model for `UserSchema`. Why is the parent model not in that object?

**Comment by kktos** [comment]
Hi there,
I'm using typegoose 5.4.1 and I got the very same problem.
Anyone having a clue how to solve this ?
Cheers.

**Comment by hasezoey** [comment]
is this still a problem in typegoose 5.9.0 (latest) and if yes, is still still a problem when using typegoose 6.0.0-14+?

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "stale" & "no now info" (/ "probably fixed")
