### ISSUE TITLE
discriminator / model inheritance

### ISSUE THREAD

**Issue by frederik-b** [szokodiakos/typegoose#93]
This project looks alot like something I wanted to write myself to solve the same problem and I'ld really like to use this on a big project.

I am however missing the option to use Discriminators.
I'll probably find a way arround it by using schemaOptions.collection to make multiple models use the same collection but it'ld be a nice feature addition nevertheless.

**Comment by richarddd** [comment]
I've got it working, pretty straight forward using `schemaOptions.collection`

**Comment by dmoree** [comment]
I'm sorry to post on such an old post, but am I understanding correctly that discriminators work here as they do in mongoose? I am only able to do as @frederik-b did and put them in the same collection.

However, if I have a model, `Model`, and a discriminated model,`DiscriminatedModel`, they may be in the same collection using `schemaOptions.collection`, but if run `Model.findById` with an `_id` of a document made from `DiscriminatedModel` it doesn't return the document as it would using mongoose.

**Comment by neckaros** [comment]
I'm also interested to know how to really use descriminator model. i.e. how to get child classes when using parent model

**Comment by hasezoey** [comment]
this can be closed in favor of #332 
@Ben305
