### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by 8eecf0d2** [szokodiakos/typegoose#95]
Hi all, the example does not appear to be working for me, no error is produced and `mongoose.connection.on('open')` is called, however the `await u.save()` never returns.

```typescript
import { prop, Typegoose, ModelType, InstanceType } from 'typegoose';
import * as mongoose from 'mongoose';

mongoose.connect('mongodb://localhost:27017/test');

class User extends Typegoose {
  @prop()
  name?: string;
}

const UserModel = new User().getModelForClass(User);

// UserModel is a regular Mongoose Model with correct types
(async () => {
  const u = new UserModel({ name: 'JohnDoe' });
  await u.save();
  const user = await UserModel.findOne();

  // prints { _id: 59218f686409d670a97e53e0, name: 'JohnDoe', __v: 0 }
  console.log(user);
})();
```

A traditional implementation (below) does work on my system.

```typescript
import * as mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  name: String
})

const UserModel = mongoose.model('user', UserSchema)

const myUser = new UserModel({ name: 'JohnDoe' });
myUser.save()
  .then(response => {
    console.log(response)
  })
```

I've tried a mixture of syntaxes and set `(<any>mongoose).Promise = global.Promise;` to no avail.

**tsconfig.json** _Typescript v2.6.2_
```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "moduleResolution": "node",
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "sourceMap": false,
        "declaration": true,
        "outDir": "build",
        "lib": [
            "es6"
        ]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "src/**/*.spec.ts"
    ]
}
```

**Comment by JamesRArroyo** [comment]
What version of mongoose do you have installed? I had the same issue this week and I was running mongoose v5.0.1. I reverted back to version 4.11.1 and that worked for me.

**Comment by brod** [comment]
Thanks! rolling back to **4.11.1** worked and `{ existingMongoose: mongoose }` didn't seem to do anything on either version.

Unfortunately this has created a new issue since I'm using the latest mongoose in other modules typescript is complaining about a bunch of `duplicate declaration` errors - which I don't _think_ can be fixed without normalizing all `mongoose` & `@types/mongoose` versions.

**Comment by JamesRArroyo** [comment]
Ya I think that is because Typegoose has dependencies that should be listed as peer dependencies. There is a semi-related issue for that in issue #65 . For now I have just removed  `@types/mongoose` so they are not re-declared.

**Comment by marcelh-gh** [comment]
I am getting 

> DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

using the latest version of Mongoose (5.07)

**Comment by nhhockeyplayer** [comment]
this can be resolved bu rigging up a Promise library
like bluebird

install like this

npm i bluebird
npm i @types/bluebird -D

import it in your typescript code like this

import * as Bluebird from 'bluebird';

then override the global promise to mongoose as follows
        (<any>mongoose).Promise = Bluebird;

I got my promises working see the constructor below with my router


class UserRouter implements IRouter {
    private static connectString = process.env.MONGODB_URI || 'mongodb://localhost/api';

    private Router = new Router({
        prefix: '/api',
    });
    private renderCtx = new RenderCtx();

    constructor() {
        (<any>mongoose).Promise = Bluebird;
        mongoose.connect(UserRouter.connectString, {server: {poolSize: 15}})
            .then((): void => {
                console.log("MongoDB connection success Bluebird. MongoDB is running. ");
            })
            .catch((err): void => {
                console.log("MongoDB connection error. Please make sure MongoDB is running. " + err);
                process.exit();
            });
    }
}

**Comment by Mercurial** [comment]
@Ben305 Please update to latest mongo version!

**Comment by babakyakhchali** [comment]
I had the same problem. For me it was `{ existingMongoose: mongoose }`. thanks @JamesRArroyo

**Comment by JamesRArroyo** [comment]
@szokodiakos Looks like you can close this issue now :)

**Comment by hasezoey** [comment]
this can be closed, because typegoose now uses "latest" mongoose, and is not statically defining it to one specific version

@Ben305
