### ISSUE TITLE
Required enums do not work

### ISSUE THREAD

**Issue by floriansimon1** [szokodiakos/typegoose#97]
Investigating yesterday, I noticed two problems:

- The first one is Typegoose being anal about the fact that you define the prop as an enum, which does not happen when the field is not required
- I tweaked the code to make it work, but then Mongoose complains, thinking that required enums are a subschema. It does work when you add a "type: string" property though.

**Comment by marcelh-gh** [comment]
@floriansimon1 as far as I can see enums work just fine - required or not. Maybe you can post some more details about your issue including some example code...

**Comment by floriansimon1** [comment]
They work fine if `Reflect.getMetadata` can do its work, which is possible if you have the right TS config. The problem I had occurred because I was testing Typegoose code in `ts-jest`, which currently makes having the right TS config impossible, because of the way it is done. There are tickets on the `ts-jest` issue tracker to fix their implementation to no longer transpile files individually.

So this is not strictly Typegoose's fault :)

**Comment by hasezoey** [comment]
not an issue with typegoose, this can be closed
@Ben305
